### ISSUE TITLE
Mod causing evey JEI item shown being duplicated

### ISSUE THREAD

**Issue by Akaruz64** [TheCodex6824/ThaumicAugmentation#1]
After some painful hours of going trough my mod folder (150+) and checking online and various coremods, I found that when the last update of the mod is installed, it causes every jei item registry to be shown doubled, i don't have any log or crash since its only a visual, but very annoying, bug.

Thanks.
Regards!

**Comment by TheCodex6824** [comment]
Thank you so much for telling me about this! I'm sorry you had to spend hours going through all of those mods, but the update with the bugfix should be up shortly.
