### ISSUE TITLE
not necessarily an issue, but something i would like looking into

### ISSUE THREAD

**Issue by mageslayer325** [TheCodex6824/ThaumicAugmentation#103]
im not necessarily a coder, but is this mod possible to use alongside the plentiful mods of mincraft eternal modpack?
i know its being developed but i didnt necessarily see much about its compatability and id like to see if it can work with other mods as well

**Comment by TheCodex6824** [comment]
This would probably be better as a curse comment in the future, but the only mods I know of that will probably make things not work are Cubic Chunks and some bukkit-based server software. Optifine might also cause visual issues if you enable their shaders.
