### ISSUE TITLE
Elytra harness boosting with space + double jump = unexpected death

### ISSUE THREAD

**Issue by Biviho** [TheCodex6824/ThaumicAugmentation#104]
by having any type of effect that add a double jump or a boosted jump to the player, with the elytra harness + boosting augment can result in a sudden death while climbing on a hill, as after jumping, sometimes the game will take the jump input as the elytra boosting right in front of a wall.

it would be better to have the boost binded to Alt or shift, or the ability to change keybinding via config/controls menu

**Comment by TheCodex6824** [comment]
I think I was originally worried that making it a proper keybind would prevent it from being the same key as jump, which a lot of people said they like. I'll check that again, if that's the case, I'll make the keybind be a config option or something. Either way, a keybind would be a good idea.

**Comment by TheCodex6824** [comment]
Update will be available soon [here](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/3089750).
