### ISSUE TITLE
Metaspatial Extruder Not Placing Rift

### ISSUE THREAD

**Issue by polic72** [TheCodex6824/ThaumicAugmentation#106]
When trying to use the extruder, the ghost version of the rift appears but no matter how I try to right click it, the placing process won't start. I can confirm that there are no rifts remotely near where I'm trying to place it.

**Comment by TechnoMysterio** [comment]
Some questions: are you using a gauntlet when right-clicking the device? Is there anything in the space where the rift is meant to go? And if those questions don't help, could you perhaps post some pictures of what you're trying to do?

**Comment by polic72** [comment]
Using a thaumium gauntlet when right clicking (see picture). Nothing is blocking the test area I have when trying.

Gauntlet used when right-clicking:
![image](https://user-images.githubusercontent.com/28581221/96170357-7bb07080-0ef1-11eb-9e7b-1924312e209d.png)

Testing area:
![image](https://user-images.githubusercontent.com/28581221/96170161-3ee47980-0ef1-11eb-9490-074823a1c34d.png)

**Comment by TechnoMysterio** [comment]
Hmm, the only thing I can think of is that there might be a mod conflict of some kind, although I'm not a programmer so it is also quite possible that I am completely wrong. Nonetheless, if you could post a modlist that might be helpful once Codex gets a chance to look at this issue.

**Comment by TheCodex6824** [comment]
There was a bug with it not properly working on servers, the next release will have a fix for that. If that's not the problem, the only other thing I can think of is wuss mode somehow being on, which will make it not work. If both of those are not the case, I'll need to see a log to investigate this further.

**Comment by DoomRater** [comment]
Fascinatingly enough, Thaumic Wonders can tear open rifts even with Wuss Mode active.

**Comment by TheCodex6824** [comment]
> Fascinatingly enough, Thaumic Wonders can tear open rifts even with Wuss Mode active.

Yeah rifts themselves don't check for wuss mode, you need to check it manually before spawning the rift in. I'm guessing TW doesn't check for it.

As for the issue, let me know if this is still an issue @polic72 - the latest release fixed an issue where the metaspacial extruder would not work properly on dedicated servers.

**Comment by TheCodex6824** [comment]
Since I'm 90% sure this was probably fixed by #105, I'm going to close this, but if you try it again let me know if it still happens for you.
