### ISSUE TITLE
Impetus loses connection when crossing dimensions / leaving the game

### ISSUE THREAD

**Issue by Rekag** [TheCodex6824/ThaumicAugmentation#108]
Hi!
I've been having a great deal of fun with the mod, especially since the new big update came out! I did stumble upon what seems to be a bug, though the circumstances are very specific - namely, I decided to build an impetus "reactor" on the Nether's roof. The rift was placed in a chamber along with stabilizers, feeders and drainers, connected to impetus relays which transported the energy into a matrix and then into charging stations.
It does work pretty well, but I noticed that the relays disconnect whenever I go back to the overworld and decide to check up on the reactor again.
Now the way they do it isn't very consistent in my eyes, as hopefully you'll see in the screenshots I'll upload.
I am using a self-made modpack, but I did test it with only Thaumcraft, Baubles and Thaumic Augmentations and the issue persisted.

While testing the issue further, I noticed that it may not be just crossing dimensions that causes it, but also exiting the game:
I connected some relays in my system back together and reloaded the save - the relays lost connection without me leaving the Nether. What's curious is that for some reason my _line of sight_ gives the impetus connection a lifespan of sorts - if I keep the connected relays in my line of sight while reloading the game, some of them lose connection only after the second reload or so.

here's an Imgur album with my attempt to best capture the issue:
https://imgur.com/a/qU9Rldy

If I left anything too vaguely described, don't hesitate to ask further questions!

**Comment by Rekag** [comment]
also thought it would be wise to add some more context:

**my Forge version:**
14.23.5.2847
**Baubles version:**
1.5.2
**Thaumcraft version:**
6.1.BETA26
**Thaumic Augmentation version:**
2.0.8

**Comment by TechnoMysterio** [comment]
You've done a very good job at detailing the issue, especially with the picture gallery, so you certainly have not been vague at all with your description. So excellent work with that.

As for the issue itself, we did run into trouble with relays disconnecting in testing, but the specific cause was never determined. With the beams seeming to linger for a moment before they disconnect, I wouldn't be surprised if that's something to do with the server/client needing a short moment to properly sync up, so it looks like they are connected before the game catches up with itself.

One possible area that we suspected might be causing trouble was chunk borders, so could you press F3 and G in order to show the chunk overlay, and see if the disconnecting nodes cross chunks, or at the very least are near the edges of chunks? You can provide pictures if you want, but if you've had enough of doing that then you can just give a short description.

**Comment by Rekag** [comment]
https://imgur.com/a/s3BLzrP

Oh yes, chunk borders must be involved - the place the system disconnects most often is where a relay must send a beam across to a new chunk.
The rift "containment room" fits inside a single chunk, so this border between it and the matrix chunks is the first one the impetus has to cross.
What's curious is that if you compare the full view of the matrix room with my previous save reload testing, then you'll see that the beams in the chunk I stood in were not being disconnected, while the beams of the farthest matrix were being gradually disconnected.
Also probably the reason why my remodelling of the system worked for a while was because it compressed it, as you can see in the final screenshot the rechage stations fit inside the "matrix chunk".

**Comment by Rekag** [comment]
Oh I should also mention that when I loaded up the save to take the screenshots, the entire system was disconnected, all the way to the drainers in the "main" chunk. I'm pretty sure that's because I left the matrixes disconnected, almost as if the system disconnects chunk by chunk - since the matrixes were disconnected already, all that was left was the main chunk.

**Comment by Rekag** [comment]
that's alright, I know these things take time

**Comment by TheCodex6824** [comment]
I'll take a look at this later today, the next update will probably not have the fix as I have to release an emergency bugfix due to lag issues in a modpack, but the next one will. Chunk borders are always a bit tricky but I have an idea what might be going wrong.

**Comment by TheCodex6824** [comment]
I'm having trouble getting it to happen for me (no surprise there, chunkloading stuff is always this stubborn). Some other questions that could help me:
1. From what you wrote it sounds like this is in singleplayer, is that true?
2. When it happens, is it just visual or are they really disconnected for real? Try doing something that consumes impetus down the line and see if it reaches even if it appears broken.
3. If you break and replace the offending relay and reconnect things, does it still occur?

**Comment by Rekag** [comment]
> I'm having trouble getting it to happen for me (no surprise there, chunkloading stuff is always this stubborn). Some other questions that could help me:
> 
> 1. From what you wrote it sounds like this is in singleplayer, is that true?
> 2. When it happens, is it just visual or are they really disconnected for real? Try doing something that consumes impetus down the line and see if it reaches even if it appears broken.
> 3. If you break and replace the offending relay and reconnect things, does it still occur?

1. exactly, it's happening on a singpleplayer world, sometimes used for LAN if that would matter
2. the connection disappears completely, I first noticed it exactly because the item rechargers stopped working
3. I tried placing the relays down and connecting them in multiple configurations before I even considered making a GitHub post about the issue, and the problem persisted.

I could upload my save folder and share it with you if you won't have any luck with replicating the issue!

**Comment by TheCodex6824** [comment]
> I could upload my save folder and share it with you if you won't have any luck with replicating the issue!

If you're willing to upload it, the world would be extremely helpful to me. I'll keep it private, but if there's anything personal in it you might want to remove it before uploading.

**Comment by Rekag** [comment]
I have sent an Email with a download link to the address shown on your GitHub account.
I have listed the versions of required mods, and after loading the world you'll find yourself right on the spot where all the testing can be done.

**Comment by TheCodex6824** [comment]
Not sure if you saw/got my email but the world was very helpful, and I think I've fixed all the issues causing things to disconnect. The fix will be in the next public release, but in the meantime if you'd like I can email you a (signed) build for you to try out. Normally I'd say to build it from source but it looks like CurseMaven broke in the Overwolf transition so anyone that doesn't already have a build environment would have to manually download and place the build dependencies.

**Comment by Rekag** [comment]
that's great news!
I did get the Email and I'm glad I could help. I'm fine with waiting for the next public release of the mod, but thank you for offering to send me the build to try out!

**Comment by TheCodex6824** [comment]
https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/3133525
