### ISSUE TITLE
Emptiness Hedge Alchemy

### ISSUE THREAD

**Issue by DoomRater** [TheCodex6824/ThaumicAugmentation#112]
Ancient Stone cannot be easily made by the Thaumaturge, but there is enough of it once you beat the tar out of one of those towers.  Still, I'd love a way to manufacture it with alchemy. Gotta get that ancient castle aesthetic.  A builder I had playing with me on 1.7.10 built a gnarly looking castle using lots of ancient stone and it was pretty, and I think it honestly looks better than the stock Arcane Stone.

Of course I'm playing with Thaumic Wonders which already has Nether Hedge Alchemy and Alien Hedge Alchemy which is what made me think of it.

**Comment by TechnoMysterio** [comment]
The TC6 addon Crimson Revelations adds a recipe to make Ancient Stone, so you can use that if you want. That mod was also partially why we didn't add our own Ancient Stone recipe, the other was that the spire has so much of it that a recipe wasn't needed very badly.

**Comment by DoomRater** [comment]
I'll take a second look at the mod and see if it fits my needs, and if it doesn't I'll probably CT an alchemy recipe in.  Since that's all I can think of that needs Hedge Alchemy, I can just close this.
