### ISSUE TITLE
fracture rendering and optifine shaders

### ISSUE THREAD

**Issue by xemnes** [TheCodex6824/ThaumicAugmentation#113]
seems theres issues with dimensional fractures (and flux rifts) causing weird issues with shaders. i use complementary (a bsl shaderpack edit) and i have consulted the shader dev on the matter and they tried to fix the issues with no luck. 
basically when a dimensional fracture is in camera view, the shadowmap from the shader messes up and entities glow white and can sometimes be seen through blocks, the fracture/rifts can also sometimes be seen through blocks (seems to be camera angle dependant).

i tried disabling the mods shaders but to no avail. they told me i had to report the issue here to hopefully get it fixed. seems there needs to be some alternative rendering method for the rifts/fractures to stop the issue happening, its weird because the rendering looks just like end portals and they dont cause these issues.

heres a video to show what happens https://www.youtube.com/watch?v=HgB5jIG1BEA

**Comment by TechnoMysterio** [comment]
I'm not sure if much can be done to solve that issue, since OptiFine changes how Minecraft is rendered in such a fundamental way. The fractures themselves use a shader of their own for the starfield effect, likewise with normal Thaumcraft's flux rifts, so it isn't too big a surprise that they would work poorly with OptiFine and shaderpacks I'm afraid. However, I don't know much about programming or rendering, so I'd have to get a second opinion from Codex as to whether the problem can actually be mitigated somehow.

**Comment by xemnes** [comment]
heres hoping he might be able to do something then, i love thaumcraft and this mod a lot, i also love being able to play with shaders, but this issue makes it less enjoyable sadly.

**Comment by TheCodex6824** [comment]
I thought I added a config option to disable shaders, but apparently I never got around to doing that. Things will look ugly without the shaders enabled, but it will work at least.

**Comment by xemnes** [comment]
would the option only disable the shaders on rifts? or everything? the other stuff seems to render fine at least.

**Comment by TechnoMysterio** [comment]
The option would disable the effects on rifts (as long as the optimised renderer is enabled), fractures, starfield glass and probably the Emptiness skybox. Anything else would remain the same.

**Comment by xemnes** [comment]
right ok, what would they look like though?

**Comment by TechnoMysterio** [comment]
It would look like a maelstrom of chaos, a vortex of light and darkness, a window into the unspeakable, the mind could not comprehend such things, if they could be called things at all, nothing and everything and neither of the two all simultaneously, it would bring wonder and awe and despair and horror and you would be filled with these and yet there would be so much more, the shadows shining upon you through endless oceans within oceans beneath oceans and you would know that you do not know anything and nothing and everything at all.

...Either that or it'd just make rifts and fractures lose their starry effect and they'd just be solid black or purple, which would be a shame but it'd be better than having them screw up the lighting when you look at them. That's just a guess though, my first thought might be more accurate for all I know.

**Comment by xemnes** [comment]
perhaps the effect could be applied via the shaderpack, who knows

**Comment by DoomRater** [comment]
Where can I try dev out?  I've started investigating why some items in other mods (and an entire UI panel in Extra Bit Manipulation) no longer render their items.  So far reverting Thaumic Additions to 1.1.19 results in the items rendering, and I wanted to confirm if it might be the new rendering code.  For the record, I do not run Optifine.

I can also reproduce as soon as 2.0.1.

**Comment by xemnes** [comment]
@DoomRater you need to compile the source code yourself, its pretty straight forward for the most part.
install jdk 8 and download the source.

this must be added to build.gradle for it to complie
`compileJava.options.encoding = 'UTF-8'
compileTestJava.options.encoding = 'UTF-8'
javadoc.options.encoding = 'UTF-8'`

place those after line 24

then open a command prompt at the sources root folder and type gradlew build

**Comment by DoomRater** [comment]
Thankfully this isn't the first mod I've needed to recompile.  Recompilation successful, but turning off all TA renders does not affect my issue.  I probably need to refile as a separate issue then.

**Comment by xemnes** [comment]
out of curiosity, do you by chance have twilight forest? i noticed some items from that render invisible for me and werent sure if its related to your issue.

**Comment by DoomRater** [comment]
I have my custom Twilight Forest with the experimental uncrafting blacklist rolled in and I can confirm the fiery armor set does not render.  Additionally, several items in Extra Bit Manipulation do not render, including UI elements when in the Cosmetic Armor GUI.  Reverting to Thaumic Augmentation 1.1.19 seems to fix it.  Turning off TA special renders with the dev compiled version of Thaumic Augmentation does not bring them back, at least it didn't on my end.

**Comment by xemnes** [comment]
yup, i have the exact same issue, fiery armour and cosmetic armour arent rendering

**Comment by xemnes** [comment]
on the topic of the shaders though, been testing it out
starfield glass does some really weird stuff https://gfycat.com/SpitefulBlackBettong

and not sure if its intentional or not but now my flux rifts and fractures are rending almost completely invisible https://cdn.discordapp.com/attachments/714550216430321706/777679373154910208/unknown.png

**Comment by TheCodex6824** [comment]
Try the latest update with TA shaders disabled if you're using Optifine and see how things are. If things still don't look right, feel free to open a new issue, since the original one was resolved.

**Comment by xemnes** [comment]
i mean it still looks the same as what i mentioned in my previous comment with the shaders turned off but i guess thats what happens and i will have to live with it.
