### ISSUE TITLE
Bug? Morphic tool/armor recipe consumes entire pearl

### ISSUE THREAD

**Issue by Hyxaru** [TheCodex6824/ThaumicAugmentation#115]
When I did the infusion, I expected the pearl to degrade a tier, but it seems the entire pearl got consumed in a creative world. I my survival world, it did work just fine. Something is weird.

**Comment by TechnoMysterio** [comment]
Do you mean that in creative mode, the morphic tool/armour recipe consumed a full pearl, and in survival mode only a portion of the pearl was consumed? Furthermore, what was the durability of the pearl in each case (full, nodule or mote)?

**Comment by TheCodex6824** [comment]
So looking at the code it does look like I messed up and didn't account for the pearl. I'll have to check the TC code later to see what might cause it to work only sometimes.

**Comment by Hyxaru** [comment]
Now that you mention, it's possibly/likely due to ThaumTweaks; it adds a crafting recipe to combine weaker pearls to restore durability.

**Comment by DoomRater** [comment]
Ouch, I just learned my entire pearl was consumed during a morphic tool infusion.  In survival.  Thankfully I can get more easily, I'm finally at a point where I can, but that definitely hurt a bit.

**Comment by TheCodex6824** [comment]
This is 100% my fault and has nothing to do with ThaumTweaks, sorry about that
