### ISSUE TITLE
Does this mod change something in thaumcraft?

### ISSUE THREAD

**Issue by Forturian** [TheCodex6824/ThaumicAugmentation#116]
There are just some new aspects here:
Glove Augmentation System
A new dimension, the Void,
I'm wondering - will they somehow affect vanilla thaum by changing its files or something else?

**Comment by TechnoMysterio** [comment]
Thaumic Augmentation does include some fixes and improvements for Thaumcraft's base code, but aside from that it doesn't change anything in particular about the original mod's mechanics. Instead, it mostly adds new content and systems, like a new power system, gauntlets and gauntlet augments and the new dimension you mentioned. Were you having trouble installing it in an existing world or something?

**Comment by Forturian** [comment]
> Thaumic Augmentation does include some fixes and improvements for Thaumcraft's base code, but aside from that it doesn't change anything in particular about the original mod's mechanics. Instead, it mostly adds new content and systems, like a new power system, gauntlets and gauntlet augments and the new dimension you mentioned. Were you having trouble installing it in an existing world or something?

No, no, I just asked specifically about the changes that would be visible. That is, are these changes at the code level? I just want to install the mod on this and ask if it changes something GLOBALLY, that is, let's say I installed this mod and started going through taumcraft - would everything be exactly the same as if I went through vanilla thaum?
I apologize if I am not exactly expressing myself.

**Comment by TechnoMysterio** [comment]
If you ignored the Thaumic Augmentation tab in the book and stuck entirely to the vanilla stuff, nothing in the research progression would be different, and nothing would be different in terms of crafting, spell-casting, building etc.

**Comment by Forturian** [comment]
> If you ignored the Thaumic Augmentation tab in the book and stuck entirely to the vanilla stuff, nothing in the research progression would be different, and nothing would be different in terms of crafting, spell-casting, building etc.

Thank you very much for the detailed answer, I'll go install the mod.

**Comment by TechnoMysterio** [comment]
OK, unless you've got any other questions do make sure to close the issue, just to keep things tidy.
