### ISSUE TITLE
Starfield glass edges have seams

### ISSUE THREAD

**Issue by DoomRater** [TheCodex6824/ThaumicAugmentation#118]
![2020-11-09_08 43 30](https://user-images.githubusercontent.com/4010432/98548770-ebebb100-2267-11eb-9e95-b4e8518122f1.png)
I'm not using any shaders, but I do have CTM.  I only notice these seams particularly up close, but when I do it kinda ruins the effect.
I'ma post a debug crash so you can see the mods installed as well, since I have no idea if any of them could be useful in reproducing. https://pastebin.com/NTm6WnUq

**Comment by TechnoMysterio** [comment]
I can't say I noticed this problem in testing, do you use any mods that tweak Minecraft's rendering like OptiFine?

**Comment by DoomRater** [comment]
This is why I included a Debug Crash report.  Any and all potential rendering mods should be listed in the crash report.  Optifine is not in this pack, but Phosphor, Armourer's Workshop, Astral Sorcery, Dynamic Surroundings, LittleTiles, and Immersive Engineering are all part of the pack.  I do not notice this as much on Rift glass, but on Dimensional Fracture glass it is pretty visible up close.

![2020-11-11_15 22 01](https://user-images.githubusercontent.com/4010432/98860647-01143b80-2432-11eb-9b92-1ad7df89baca.png)

Above is an example of some specks in the rift glass that are visible, just barely.

![2020-11-11_15 23 55](https://user-images.githubusercontent.com/4010432/98860702-15f0cf00-2432-11eb-98b7-6f44b2ba2127.png)

Additionally there are angles where the glass fails to render, but that could be multiple renders conflicting with each other in the room I have it on.
![2020-11-11_15 23 59](https://user-images.githubusercontent.com/4010432/98860722-1ab58300-2432-11eb-9b7a-532492124ae9.png)
Moving ever so slightly like this causes it to suddenly work again.

**Comment by TechnoMysterio** [comment]
Hmm, not sure what could be causing the seams then. As for the the starfield effect vanishing, from my own experience stuff like that happens when another mod is doing fancy rendering at the same time, so is there anything in your base with unique rendering outside of the usual opaque/transparent blocks?

**Comment by TheCodex6824** [comment]
For the seams, it looks like I need to just tweak the values a bit. I have to have a tiny seam to make it not z-fight with the glass frame, but it seems like the value I picked isn't universally acceptable. As for the effect becoming transparent, another mod probably messed with the transparency state and didn't reset it when the glass effect wants to render. I have to render the glass effects during a somewhat weird time for performance reasons, so it's no surprise that it exposes some issues like that. Unfortunately, unless you can identify what block / tile / entity is causing that to happen, I can't really do anything about it.

**Comment by DoomRater** [comment]
I am not too worried about the wonky render.  I am abusing so many different renders it might not be possible to isolate which, if indeed it is only one, conflicting render.

**Comment by DoomRater** [comment]
After some testing with what I thought was an unrelated issue, there may be some wonkiness going on between Thaumic Augmentation and Connected Textures mod.  Adding CTM 1.0.2.31 to an instance with just Thaumcraft, Thaumic Augmentations 2.0.9 (and dev build) and Twilight Forest 3.11, the fiery armor no longer renders in item form.  Removing CTM OR Thaumic Augmentations allows the fiery armor to render once more.

**Comment by DoomRater** [comment]
Also, recompiled with epsilon value adjustment and seams have disappeared!
