### ISSUE TITLE
Able to craft blocks even though their research is only started

### ISSUE THREAD

**Issue by DoomRater** [TheCodex6824/ThaumicAugmentation#119]
![2020-11-09_09 10 47](https://user-images.githubusercontent.com/4010432/98551667-93b6ae00-226b-11eb-8971-f9b477920e51.png)
![2020-11-09_09 11 17](https://user-images.githubusercontent.com/4010432/98551668-93b6ae00-226b-11eb-97fd-ea3edfec314a.png)
This seems to occur for every bit of research I have started progress on, but not completed yet.  Also I'm falling behind in my artifice studies, as I can't actually unlock these guys yet.  Guess I'd better idle at my zombie pigman farm some more.

**Comment by TechnoMysterio** [comment]
Are you able to actually prepare these recipes in the workbench? Just want to make sure that Thaumic JEI isn't doing anything funky. If you are able to actually craft them, then I don't know what the cause of the problem might be since the research jsons seem to be set up correctly.

**Comment by DoomRater** [comment]
100% am able to craft it.  I did so before completing the research.  For the record, it appears that Thaumic Additions: Reconstructed is also allowing me to craft anything I have started research on but not finished.

**Comment by TechnoMysterio** [comment]
Do you have any other addons that interact with Thaumcraft, especially its research? If it's affecting other addons then something else might be changing how research progression works.

**Comment by DoomRater** [comment]
Number one mod I can think of is Dupefix Project.  I will retest with just Thaumic Augmentation and Thaumcraft in a testing instance and let you know.

**Comment by TheCodex6824** [comment]
Other questions for you:

1. Does this happen with non-table recipes, like infusion?
2. On a world without the gauntlet augmentation research, try crafting the elemental augment. Does that one work as well? (This one is special and is defined in code instead of recipe JSON, which may or may not be broken).

**Comment by DoomRater** [comment]
Okay, this is reproducible in VANILLA Thaumcraft and is actually a bug with TC6, not on your end.  Table recipes definitely reproduce this behavior- once the research is started, anything that required the research is craftable even if it hasn't been completed yet.
