### ISSUE TITLE
Boots of the Riftstrider infusion isnt working?

### ISSUE THREAD

**Issue by Latoshi121** [TheCodex6824/ThaumicAugmentation#12]
For some reason, the infusion altar is not allowing the infusion to create the boots of the riftstrider to occur. There are no errors on the server, and I'm playing on a multiplayer server. I dont have access to the error logs cus it isnt doing anything. The mods i have installed are as follows;

AbyssalCraft
AbyssalCraft Integration
AE2 Stuff
AE2 Wireless Terminal Library
Akashic Tome
AppleCore	
AppleSkin	
Applied Energistics 2	
Arcane Lamps	
Aroma1997Core	
Aroma1997s Dimensional World	
Astral Sorcery
AutoRegLib	
Barrels, Drums, Storage & More
Baubles
BdLib
BetterFps
BiblioCraft	
Blood Magic	
Bonsai Trees
Bookshelf
Botania
Chameleon
Chisel	
Chisels & Bits
ConnectedTexturesMod
Construct's Armory
Cooking for Blockheads
Cosmetic Armor 
Crafting Tweaks	
Cucumber Library
Custom Main Menu
Decocraft2	
DummyCore Unofficial
Embers Rekindled
Essentia Brazier
ExtraCells2	
Farming for Blockheads
FTB Library
FTB Utilities
FTB Utilities: Backups
GraveStone Mod
Guide-API
Hammer (Lib) Core
Ice and Fire: Dragons in a whole new light!
iChunUtil
Improvable Skills 3	
Improved Backpacks
Inventory Tweaks
Iron Backpacks
Iron Chests
JEI Villagers
JourneyMap
Just Enough Energistics (JEE)
Just Enough HarvestCraft (JEHC)
Just Enough Items (JEI)
Just Enough Resources (JER)
LLibrary
MalisisCore
MalisisDoors
Mantle
MCMultiPart
Mercurius
Morpheus
Mouse Tweaks
Mystical Agradditions
Mystical Agriculture
Neat
NotEnoughCodecs
NotEnoughIDs
OpenBlocks
OpenModsLib
p455w0rd's Library
Pam's HarvestCraft
Planar Artifice
PTRLib
Quark
ReAuth
Resource Loader	
Roots
Shadowfacts' Forgelin
Snad
Storage Drawers
Storage Drawers Extras
Storage Drawers Unlimited	
Thaumcraft	
Thaumcraft 6 Aspects for JEI	
Thaumic Additions: Reconstructed
Thaumic Arcana	
Thaumic Augmentation
Thaumic Bases 
Thaumic Brewing	
Thaumic Energistics
Thaumic Gadgets	
Thaumic Inventory Scanning (Thaumcraft Addon)	
Thaumic JEI	
Thaumic Periphery	
Thaumic Restoration	
Thaumic Wonders		
The One Probe	
The Twilight Forest	
Tinker's JEI	
Tinkers Construct	
Tinkers' Tool Leveling	
TOP Addons
Totemic	ljfa	
Waddles	Girafi	
Wearable Backpacks	
Wireless Crafting Terminal

**Comment by TheCodex6824** [comment]
I just tried the infusion on both singleplayer and a dedicated server and it's working for me. Make sure there isn't a leftover item from an infusion hiding on a pedestal somewhere, and make sure you fully completed the research (JEI will always show the recipe, even if you have not done the research for it yet). Otherwise, can I possibly see a screenshot of your setup?

**Comment by Latoshi121** [comment]
At the current moment i cannot supply a screenshot, it will have to wait till i get home. But i do know for a fact that the items where placed correctly. When i arrive home ill supply the information you need and test it with just the base thaumcraft. Though the only thing i can think of is some other thaumcraft addon i have installed messing with it.

**Comment by Latoshi121** [comment]
![my thaum setup](https://user-images.githubusercontent.com/51211889/58730530-6c8f5800-83ba-11e9-9dfe-5d8b856c3c71.png)
here is an image of my setup. I am going to troubleshoot it now with the other mods to try and figure out what is up

**Comment by Latoshi121** [comment]
Further update, it works in single player with the modlist I supplied, but for some reason on the server it wont work. This is strange.

**Comment by TheCodex6824** [comment]
I just tried it out on a dedicated server with all of the Thaumcraft addons you have, and it still worked. Other than some random mod breaking it for some reason, the only other things I can suggest are trying any other infusion to see if that setup didn't get invalidated for some weird reason, and making sure those pedestals in the other room in your screenshot (and any nearby) are empty. If all else fails, and the modpack you are running is public, if you link me to it I can try your exact pack to see if I can reproduce it.

**Comment by Latoshi121** [comment]
So i did it through creative and it worked, maybe one of the items i was using in the infusion wasnt right in some way? But regardless it worked and the problem is solved. Sorry for the headache i may have caused, Love the addon!

**Comment by TheCodex6824** [comment]
It's no problem at all, I'm glad you were able to figure it out!
