### ISSUE TITLE
The shell ring does not work. (vanilla thaum)

### ISSUE THREAD

**Issue by Forturian** [TheCodex6824/ThaumicAugmentation#121]
Maybe I don’t understand something, but I was told that this is related to thaum augmentation.

**Comment by TechnoMysterio** [comment]
The shell ring? Do you mean the cloudstepper ring perhaps? If so, then issue #117 already covers this issue, and also covers a temporary measure for how to solve it.

**Comment by Forturian** [comment]
I just changed the button in the minecraft settings: /
