### ISSUE TITLE
Player keys are not safe for the Morph-o-Tool/Names of keys reset when bound and unbound

### ISSUE THREAD

**Issue by DoomRater** [TheCodex6824/ThaumicAugmentation#122]
Binding or unbinding a key while it is attached to a Morph-o-Tool (or Akashic Tome, for those of us who are completely mad) will destroy the hooks the tool made on the item, leaving it just a key.  Probably a "don't do that" scenario as I have no idea if there's anything that can be done on either side.

**Comment by DoomRater** [comment]
Oop, spoke a bit too soon- renaming the key after it is bound will also reset the name on the key.  It looks like the item is just completely reset, including any tags about repair cost, enchantments, and even custom names.

**Comment by TheCodex6824** [comment]
Whoops yeah looks like I threw out the entire NBT tag on bind/unbind rather than just the keys I needed to, sorry about that.

**Comment by DoomRater** [comment]
Just tried in dev.  Looks like once an iron key is unbound, it can't be rebound.  It definitely doesn't destroy the tool/tome anymore though!
