### ISSUE TITLE
[Question] Flux Rifts in Wuss Mode

### ISSUE THREAD

**Issue by DoomRater** [TheCodex6824/ThaumicAugmentation#125]
My modpack progress revolves around finding a void seed from the Crimson Cult instead of from a rift, since they do not spawn from too much flux in the world anymore.  However, this means that actually getting a flux rift to spawn is more difficult than normal.  I've tried removing the rift seed recipe to instead add the creative seed instead, but that doesn't seem to work.  Without some other workaround, I'm stuck- while Thaumic Wonders can treat open rifts at will with its machinery, they require primordial pearls to make, meaning someone already had to have found one.  My current stop gap is to make it possible to synthesize a mote from basic resources, but requiring a beefy infusion recipe to do else it destabilizes and goes very wrong very fast.  Not ideal.  Plus it trivializes the mote recipes Wonders adds.

I'd rather force the player to get the pearls from a rift the old fashioned way. I just need a way to actually make the rift at will...  Any suggestions?  Say, if I were to create some sort of recipe using the seed to make one that will spawn a rift even in wuss mode, which the creative ones do...

**Comment by DoomRater** [comment]
I completely missed that the flux seeds are the ones with metadata, and the rift seeds are the ones without metadata.  I should be able to alter the recipes as necessary now.

**Comment by TheCodex6824** [comment]
They shouldn't be spawning in wuss mode (sounds like I forgot a check...), but when I do fix that, I'll add a config option to enable that behavior since you need it. I'll also add something to make the "Creative Only" thing disappear from items as well.

**Comment by DoomRater** [comment]
Oh, when creating the flux rift seed via crafttweaker, I don't see the "creative mode only" tag.  It looks like they are created with exactly the tags I specified.  The flux seeds never create rifts in Wuss Mode, only resulting in a lot of flux being created.  It is only the ones called flux rift seed that actually make rifts in Wuss Mode.  To me, it sounds like things are working as expected as can be?

**Comment by TheCodex6824** [comment]
I forgot to mention this yesterday, but the new release disables rift seeds from working in wuss mode by default. However, there is a config option under gameplay to allow them to make rifts again. I also added the config option to disable the "creative only" text, that is under client options.

**Comment by DoomRater** [comment]
Thank you for the reminder.  I figured I was going to have to look through the configs when I updated.
