### ISSUE TITLE
[Lore] Eldritch Guardians in the Emptiness vulnerable to Smite

### ISSUE THREAD

**Issue by DoomRater** [TheCodex6824/ThaumicAugmentation#126]
A realization came to me just a moment ago: the Eldritch Guardians in the Emptiness are weak to Smite.  Should they be, though?  They're not ghostly entities in the Emptiness.  It is, after all, likely where they call home.  I suppose one could say they are "evil" in a sense since they are so warped and twisted, but Smite is lorewise supposed to be effective against undead classes, not necessarily unholy classes.  Just a thought.

**Comment by TheCodex6824** [comment]
That attribute seems to be a holdover from TC. Seems like it categorizes them as undead. I don't think that really applies to them either, so I went ahead and removed that.
