### ISSUE TITLE
Construct's Armory conflict.

### ISSUE THREAD

**Issue by George0079** [TheCodex6824/ThaumicAugmentation#128]
When trying to render any completed armor piece from Construct's Armory, the game crashes. I have already tested this and found that this only happens with this mod.

I have already posted a similar report on Conarm's page, here: https://github.com/TheIllusiveC4/ConstructsArmory/issues/250

[crash-2020-12-04_06.12.04-client.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/5642645/crash-2020-12-04_06.12.04-client.txt)

**Comment by DoomRater** [comment]
My guess is something to do with Morphic Armor.  Thaumic Augmentations has a recipe that can disguise any armor as any other armor, but to do so a bit of code backend is required.  So there's likely confusion between the two mods about what is expected from the armor during setup.  If only I could recall how to add Construct's Armory items to the blacklist, we could rule this out pretty fast.

For the record, I have no idea who's mod is really at fault.

**Comment by George0079** [comment]
I have a feeling it's an unintended issue from Thaumic Augmentations, as that's the one that adds an entire item that deals with armor cosmetics.

**Comment by TechnoMysterio** [comment]
That'll probably be an issue related to morphic armour somehow, the rendering stuff seems to be causing a lot of problems with other mods and their own armour sets.

**Comment by TheCodex6824** [comment]
Yep this is an incompatibility with how I handle morphic armor. It looks like Tinker's Construct BakedToolModel has overrides that return an instance of of BakedSimpleItem, but it copies over those same overrides. They seem to only expect BakedToolModel instances to be passed, so it gets upset and crashes when it gets something else. This isn't really a Construct's Armory issue unfortunately, to make this work either Tinker's Construct would need to check the original model coming in before casting it, or I need to add another class of exemptions for models that should not be iteratively resolved.

Edit: also, the reason why I need to iteratively resolve models like that in the first place is to support special models that need to have handleItemState / applyOverrides called to work at all, as they rely on delegating to a different model that holds the actual quads.

**Comment by xemnes** [comment]
can confirm this is happening for me too, this didnt happen in the previous version before the invisible armour fix.

**Comment by TheCodex6824** [comment]
This should be fixed in the next update. I'm holding off releasing it for a bit to see if I can fix some Impetus linking issues someone is experiencing, but for anyone compiling from dev it should be good to go.

**Comment by xemnes** [comment]
nice, will compile and test.

**Comment by Aeron216** [comment]
Was about to share the same issue.

**Comment by xemnes** [comment]
the latest version of the source fixes it.

**Comment by TheCodex6824** [comment]
https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/3133525
