### ISSUE TITLE
Fortified glass and Starfield glass are opaque 

### ISSUE THREAD

**Issue by AzazelSurris** [TheCodex6824/ThaumicAugmentation#130]
downloaded the mod today and went into creative to test some stuff. i placed all 3 kinds of starfield glass and they are entirely white. but as i got some distance away from them the white textures glitched out and i could see the normal rift/void/fracture textures behind them. fortified glass is also entirely opaque. they look perfectly normal in hand and on the hotbar, but once placed they become as described.

**Comment by AzazelSurris** [comment]
sorry for the omitted details, ive been up all night. this might be a compatability issue since i installed this in the the ftb revelations modpack. all items work fine its just the glass blocks, tested it on a fresh install with only thaumcraft and thaumic augmentation loaded and the glass works fine so it could be due to whatever mod adds connected textures in ftb

**Comment by TechnoMysterio** [comment]
That doesn't sound right, CTM is used by the glass texture to have dynamic borders. Do you have anything like OptiFine installed as well? Either way, rendering issues are quite likely in larger modpacks so it can be hard to pinpoint the problem and from there actually figure out a way to solve it.

**Comment by DoomRater** [comment]
I run CTM with no Optifine and I do not have this issue.  A modlist would be quite helpful in pinpointing troublesome mods and maybe playing with configurations in said trouble mods to solve the issue.

**Comment by AzazelSurris** [comment]
a full modlist is too long to post. but i am using the ftb revelations 3.3.0 mod pack, the only extra mod is thaumic augmentation.
i tested it with ONLY thaumcraft, thaumic augmentations, and CTM installed on a fresh forge install and the rendering bug is still present.

**Comment by AzazelSurris** [comment]
oh, i solved the issue myself, turns out the modpack comes with a 2 year old versions of ctm. tested on the newer version and it works fine
