### ISSUE TITLE
Cloudstepper Ring not reducing fall damage as intended.

### ISSUE THREAD

**Issue by LightYoshiru** [TheCodex6824/ThaumicAugmentation#131]
This is a report for ThaumicAugmentation 2.0.12 for Minecraft 1.12.2

Other mods involved are:
- Thaumcraft 6.1.BETA26
- Baubles 1.5.2

Main issue with the Cloudstepper Ring provided by Thaumcraft 6; as defined by sources on wiki pages, the ring is suppose to reduce fall damage by 2/3.

Tests for Cloudstepper Ring's fall damage reduction:
Note: All tests were done at a height of 24 blocks of dirt on a flat landing surface and with the CS Ring in the first bauble slot for rings, each test was done with a new world each time. When adding and removing mods for testing, all .minecraft files were deleted to avoid any potential issues. Each tests were done with walking off edge of 24 blocks high, and repeating same except for jumping off on second attempt.

Test 1:
Only Thaumcraft and Bauble installed. Built 24 blocks high and walked/jumped off edge. Player impacted with ground and only suffered total 5 points of fall damage (2 and a half hearts).

Test 2:
All three mods installed. Checked "mod options" config to make sure that EnableImpetusThrusterKeybind=false, verified by checking in game config and .minecraft file. Built 24 blocks high and walked/jumped off edge. Player impacted with ground and instantly died.

Test 3:
All three mods installed. Checked "mod options" config to make sure that EnableImpetusThrusterKeybind=true, verified by checking in game config and .minecraft file. Did not change controls for testing purposes. Built 24 blocks high and walked/jumped off edge. Player impacted with ground and instantly died.

Test 4:
All three mods installed. Checked "mod options" config to make sure that EnableImpetusThrusterKeybind=true, verified by checking in game config and .minecraft file. Changed "Activate Impetus Thruster (Hold)" to the keybind "K". Built 24 blocks high and walked/jumped off edge. Player impacted with ground and instantly died.

Test 5:
All three mods installed. Checked "mod options" config to make sure that EnableImpetusThrusterKeybind=true, verified by checking in game config and .minecraft file. Changed "Activate Impetus Thruster (Hold)" to the keybind "K", additionally changed "Jump" to keybind "N". Testing if keybind "Space" has an issue. Built 24 blocks high and walked/jumped off edge. Player impacted with ground and instantly died.

Test 6:
All three mods installed. Checked "mod options" config to make sure that EnableImpetusThrusterKeybind=true, verified by checking in game config and .minecraft file. Changed "Activate Impetus Thruster (Hold)" to the keybind "None". Testing if unbinding the key would remove issue. Built 24 blocks high and walked/jumped off edge. Player impacted with ground and instantly died.

Test 7:
All three mods installed. Checked "mod options" config to make sure that EnableImpetusThrusterKeybind=true, verified by checking in game config and .minecraft file. Changed "Activate Impetus Thruster (Hold)" to the keybind "None". Changed "mod options" config to EnableImpetusThrusterKeybind=false, verified by checking in game config and .minecraft file. Restarted Minecraft. Built 24 blocks high and walked/jumped off edge. Player impacted with ground and instantly died.

Side notes:
While testing solo, and with a few friends on a server; it was noticed that the damage was inconsistent at different fall heights. Cloudstepper Ring seems to be in effect for only certain amounts of damage as I was notified a friend fell a few blocks and took zero damage, but then repeated the same fall location but added two blocks to the platform, suddenly taking 8 points of fall damage. They then said they did it again without the ring and took the same damage amount.
Not sure if this is useful, but thought I would add it.

**Comment by TechnoMysterio** [comment]
Thanks for the detailed description of the problem. The cloudstepper ring is quite unreliable unfortunately (a lot of things in TC6 are like that, it wasn't amazingly programmed), so this'll have to be looked into.

**Comment by LightYoshiru** [comment]
No worries, I'm thoroughly enjoying the mod as is; just takes me off guard as I'm use to taking long falls suddenly. The ring's double jump still functions normally so I can plan a fall, but I've had my grapple device suddenly detach more than once in my life, so I have unexpected return visits to my spawn.

Now, I don't know anything about legality of what you can and can't do, neither do I know fully how difficult it may be to code. But if I could make a suggestion, maybe incorporating an upgraded/altered version of the ring as a temporary solution and additional content may be possible? Like maybe a ring that could negate all fall damage, triple jump, slowfall, or maybe allows you to levitate off the ground a few seconds (like hover boots from LoZ OoT).

If you would like me to do any additional testing, or provide recorded tests; let me know and I can begin providing more information.

**Comment by TheCodex6824** [comment]
This is actually my fault, I made a mistake when adding another system with fall damage. The cloudstepper ring might have some *problems* but this isn't one of them.

**Comment by TheCodex6824** [comment]
https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/3148983
