### ISSUE TITLE
Eye of eldritch obelisk does not open

### ISSUE THREAD

**Issue by furycat78** [TheCodex6824/ThaumicAugmentation#133]
So i tried to open the eye with both types of gauntlets and it didnt work i know that is a bug.I am playing on my minecraft server with this mods:

- mysticalworld-1.12.2-1.9.2

- mysticallib-1.12.2-1.9.0

- mysticallib-1.12.2-1.9.0

- Patchouli-1.0-21

- crafttweaker2-1.12-4.1.20.602 (1)

- CustomNPCs_1.12.2_05Jul20

- Baubles-1.12-1.5.2

- Botania_1.12.2_r1.10_363

- Cucumber-1.12.2-1.1.3

- DoggyTalents-1.12.2-1.15.1.6

- ExtremeReactors-1.12.2-0.4.5.67

- Forgelin-1.8.2

- Hwyla_1.8.26_B41_1.12.2

- Mantle-1.12-1.3.3.55

- MysticalAgradditions-1.12.2-1.3.2

- MysticalAgriculture-1.12.2-1.7.5

- Pewter-1.4.3

- TConstruct-1.12.2-2.13.0.183

- Thaumcraft-1.12.2-6.1.BETA26

- ThaumicAugmentation-1.12.2-2.0.9

- ThaumicJEI-1.12.2-1.6.0-27

-TheBetweenlands-3.6.2-universal 

- TravelersBackpack-1.12.2-1.0.34

- Wawla-1.12.2-2.6.275

- astralsorcery-1.12.2-1.10.17

- conarm-1.12.2-1.2.5.9

- embers-0.230

- gokiStats-1.2.8.4

- jei_1.12.2-4.16.1.301

- journeymap-1.12.2-5.7.1

- planarartifice-0.13          (official. this mod was deleted by its owner so you can't find it on curseforge anymore)

- thaumicenergistics-2.2.4

- thaumicperiphery-0.3.1

- thaumictinkerer_1.12.2_5.0_620a0c5

- zerocore-1.12.2-0.1.2.8

- TinkerToolLeveling-1.12.2-1.1.0

- ThaumicInventoryScanning_1.12.2-2.0.10

- AppleCore_mc1.12.2_3.4.0

- appliedenergistics2-rv6-stable-7

- Pam's+HarvestCraft+1.12.2zf

- AppleSkin-mc1.12-1.0.14

- CookingForBlockheads_1.12.2-6.5.0

- foamfix_0.10.11_1.12.2

- hotbarlock_1.0_MC_1.12_1.12.2

- Rift_1.13.2_1.0.4

- solcarrot-1.12.2-1.8.4

- modtweaker-4.0.18

- MTLib-3.0.6

- ae2stuff-0.7.0.4-mc1.12.2

- bdlib-1.14.3.12-mc1.12.2

- NaturalDecorMod1.12IIV1.4.2

- Charm_1.12.2_1.3.6

- Additional_Compression_Mod_1.12.2

- UnlimitedChiselWorks_1.12.2_0.3.2

- AmbientSounds_v3.0.18_mc1.12.2

- CreativeCore_v1.10.34_mc1.12.2

- SnowRealMagic_1.12.2_0.3.2

- customsignposts_1.12.2_1.0.1

forge: forge-1.12.2-14.23.5.2854

This is a big list but i would be very thankful if solve the issue.l

**Comment by TechnoMysterio** [comment]
Thanks for posting this. There's been trouble with other mods making certain block interactions fail before, so this may very well be the result of a mod conflict.

**Comment by DoomRater** [comment]
Silly question: does opening the eye require any amount of impetus in the gauntlet?  I was under the impression it does not, but I thought I'd ask.

**Comment by TechnoMysterio** [comment]
As far as I know you don't need any power source (vis or impetus) to open the eye, you only need the gauntlet itself.

**Comment by furycat78** [comment]
oh and also is there a way to enter this eye with a command

**Comment by TechnoMysterio** [comment]
Unfortunately I don't think there is one, you'll have to wait for the meantime until Codex is available to figure out the problem.

**Comment by TheCodex6824** [comment]
I need to see your logs to check for errors, I'm not quite sure why it's deciding not to work just based off of your modlist.

**Comment by furycat78** [comment]
wich logs specifically. latest logs?

**Comment by furycat78** [comment]
or no matter which logs ?(just after the download of the mod)

**Comment by TheCodex6824** [comment]
A latest.log from a session when you tried right clicking on the altar with a gauntlet would be fine. Oh one other thing - it looks like I made it not work in peaceful, so we probably need to think of what to do in that scenario.

**Comment by furycat78** [comment]
[latest.log](https://github.com/TheCodex6824/ThaumicAugmentation/files/5740790/latest.log)

**Comment by furycat78** [comment]
i can a get a more shorter version

**Comment by furycat78** [comment]
this is smallest it can be
[latest.log](https://github.com/TheCodex6824/ThaumicAugmentation/files/5740800/latest.log)

**Comment by TheCodex6824** [comment]
That log was fine, sadly nothing jumps out at me as being wrong, so I'll take a closer look at the code to see if I messed something up. I'll have to check if Sponge could be causing issues as well. Something you can do to help - can you activate other blocks that require clicking with a caster gauntlet, such as infusion altars?

Unrelated to this issue, but it looks like you have 2 corrupted mods in your pack, Pam's HarvestCraft and mysticalworld. You might want to redownload those from the official curse pages.

**Comment by furycat78** [comment]
ok, i'll try to help.

**Comment by furycat78** [comment]
so I tried crafting on eldritch altar and ancient altar cloud steper ring it all worked just fine, I tried it with all gauntlets.
BUT I found another bug if you right click any ifusion pillar with a rift focus you get 2 pieces of the block that altar made from and infusion altar resets in back in his position wich means you can get infinite ancient stone,arcane stone eldrith stone

**Comment by TheCodex6824** [comment]
The infusion pillar issue is unfortunately one in Thaumcraft itself, so there isn't anything I can really do about it. I have no idea what the issue with the altar can be yet. Just to be sure, you're clicking on the base part with the eye on it, instead of the little circle or obelisk above it, right?

**Comment by furycat78** [comment]
yes i am clicking on altar itself i can give you the video

**Comment by furycat78** [comment]
also it does not work with ancient altar

**Comment by TheCodex6824** [comment]
The only other things I can suggest:
- Try downloading a fresh copy of the latest version of Thaumic Augmentation from Curse. I mention this because your jar name does not appear to follow the format I upload them in, suggesting it may be unofficial (which is fine, but for tracking down bugs sticking to official builds helps)
- If that doesn't fix it, try running the game without Sponge. This isn't a real fix, but if it only breaks with Sponge then that really helps me, as I then would know where to look.

**Comment by furycat78** [comment]
ok thanks.
