### ISSUE TITLE
Augments not craftable on server

### ISSUE THREAD

**Issue by Ix-risor** [TheCodex6824/ThaumicAugmentation#138]
On a server, I attempt to craft together a frenzy modifier and power effect crystal. It makes a "modular caster augment" with "effect: any" and "modifier: any". This also happened when I crafted a gelum elemental modifier and power crystal. The "modular caster augment" has a blue, sparkly texture and does not appear in JEI. It can be crafted with a caster gauntlet, but the gauntlet is unchanged and the "modular caster augment" is consumed. Both of these seem to work as expected in a singleplayer test world.

**Comment by TechnoMysterio** [comment]
Are you using any other mods? If so, could you please provide a list of them, just to make sure the bug isn't a result of incompatibility?

**Comment by Ix-risor** [comment]
mod list:
1.12.2
aether-1.12.2-v1.5.2.jar
Apotheosis-1.12.2-1.12.4.jar
Armourers-Workshop-1.12.2-0.51.0.jar
Baubles-1.12-1.5.2.jar
BiblioCraft[v2.4.5][MC1.12.2].jar
Biome_Bundle-1.12.2-v6.1.jar
Botania+r1.10-361.jar
Bountiful-2.2.2.jar
BuildingGadgets-2.8.4.jar
Cavern_1.12.2-v2.3.1.jar
cfm-6.3.0-mc1.12.2 (1).jar
Chisel-MC1.12.2-1.0.2.45.jar
CodeChickenLib-1.12.2-3.2.3.358-universal (1).jar
CoFHCore-1.12.2-4.6.6.1-universal (1).jar
CoFHWorld-1.12.2-1.4.0.1-universal (1).jar
ColossalChests-1.12.2-1.7.3.jar
CraftTweaker2-1.12-4.1.20.607.jar
CTM-MC1.12.2-1.0.2.31.jar
CyclopsCore-1.12.2-1.6.6.jar
disenchanter[1.12]1.7.jar
DoomlikeDungeons-1.13.2-MC1.12.2.jar
ElectroblobsWizardry-4.3.1-MC1.12.2.jar
Embersified-1.12.2-1.0.3.jar
EmbersRekindled-1.14-hotfix.jar
EnderStorage-1.12.2-2.4.6.137-universal.jar
ExtraSpells-1.12.2-1.2.0.jar
extrautils2-1.12-1.9.9.jar
Forgelin-1.8.4.jar
ForgeMultipart-1.12.2-2.6.2.83-universal.jar
heroicarmory-1.2.0.jar
Hwyla-1.8.26-B41_1.12.2 (1).jar
iceandfire-1.9.1-1.12.2.jar
ImprovedBackpacks-1.12.2-1.5.0.0.jar
InventoryTweaks-1.63.jar
jeiintegration_1.12.2-1.6.0 (1).jar
jei_1.12.2-4.16.1.302.jar
JustEnoughIDs-1.0.3-48.jar
levelup2-1.2.4.jar
llibrary-1.7.20-1.12.2.jar
Mantle-1.12-1.3.3.55.jar
memory_repo
modlist.txt
moreoverlays-1.15.1-mc1.12.2.jar
MrTJPCore-1.12.2-2.1.4.43-universal.jar
OpenBlocks-1.12.2-1.8.1.jar
OpenModsLib-1.12.2-0.12.2.jar
OpenTerrainGenerator
OpenTerrainGenerator-1.12.2-v9.0.jar
OptiFine_1.12.2_HD_U_F5.jar
Placebo-1.12.2-1.6.0.jar
ProjectRed-1.12.2-4.9.4.120-Base.jar
ProjectRed-1.12.2-4.9.4.120-compat.jar
ProjectRed-1.12.2-4.9.4.120-fabrication.jar
ProjectRed-1.12.2-4.9.4.120-integration.jar
ProjectRed-1.12.2-4.9.4.120-lighting.jar
ProjectRed-1.12.2-4.9.4.120-mechanical.jar
ProjectRed-1.12.2-4.9.4.120-world.jar
RandomThings-MC1.12.2-4.2.7.4.jar
RedstoneFlux-1.12-2.1.1.1-universal (1).jar
Reliquary-1.12.2-1.3.4.796.jar
RoguelikeDungeonsFnarEdition-1.12.2-2.2.0.jar
TConstruct-1.12.2-2.13.0.183.jar
Thaumcraft-1.12.2-6.1.BETA26.jar
ThaumicAugmentation-1.12.2-2.0.11.jar
ThaumicInventoryScanning_1.12.2-2.0.10.jar
ThermalDynamics-1.12.2-2.5.6.1-universal (1).jar
ThermalExpansion-1.12.2-5.5.7.1-universal (1).jar
ThermalFoundation-1.12.2-2.6.7.1-universal (1).jar
twilightforest-1.12.2-3.11.1021-universal.jar
ViesCraft-1.12.2-5.9.16.jar
Xaeros_Minimap_20.29.1_Forge_1.12.jar

**Comment by TheCodex6824** [comment]
Were you crafting them while in creative mode? If so, does crafting them in survival work?

**Comment by Ix-risor** [comment]
Crafting them in survival, using jei to get the items. I used the thaumcraft give all research command.

**Comment by Ix-risor** [comment]
Other people on the server, including an administrator, have the same results when attempting to craft these items. No combination of modifier and effect crystal works.

**Comment by DoomRater** [comment]
It sounds like the issue is using JEI to get the items.  Craft the power effect using a power modifier and a real vis crystal and see if the result actually has the essentia type listed in the arcane workbench.  The exact items in JEI have example recipes and won't do anything.

Unrelated, but I don't see Dupefix Project in your mod list and that mod specifically helps squash duplication bugs that are in Thaumcraft and others.

**Comment by Ix-risor** [comment]
> It sounds like the issue is using JEI to get the items. Craft the power effect using a power modifier and a real vis crystal and see if the result actually has the essentia type listed in the arcane workbench. The exact items in JEI have example recipes and won't do anything.

I spawned in a “modifier: frenzy” and an “effect crystal: power”, and crafted them together. This works in single player and not on the server. I will try making a “modifier: frenzy” and “effect crystal: power” from components in singleplayer, but I don’t expect it to be different than spawning them.

**Comment by TheCodex6824** [comment]
I just tried crafting augments on a server and it worked for me. I'll start checking to see if one of your mods is doing something weird, in the meantime, do you know if the server you were playing on is a regular Forge server or something like Sponge?

**Comment by Ix-risor** [comment]
I believe it uses sponge. The issue appears to have resolved itself - the “modular caster augment” has transformed into an elemental ordo focus power, which can be added to a gauntlet, crystal type changed, etc as normal. That wasn’t what I wanted, but everything seems to work now. Thanks for your effort, and I’m enjoying your mod very much.
