### ISSUE TITLE
Boots of the Riftstrider crash client on SMP

### ISSUE THREAD

**Issue by TheHaterofGravel** [TheCodex6824/ThaumicAugmentation#14]
After I crafted the boots of the riftstrider I equipped them with 0 vis charge and my client crashed. I had to use an NBT editor to remove the boots so I could join the server again. 
They appear to work fine (charged/uncharged) in single-player.

The recipe is also buggy for the boots of the riftstrider (and possibly other recipes with primordial pearls) as the boots of the traveler in the middle need to have 0 vis charge or they will not work. The primordial pearl in the recipe has to be at full durability even though it only takes a single use, tested with mote and nodule.

Using ThaumicAugmentation-1.12.2-1.0.6

Server log when I tried to connect with the boots on and crashed:
![Boots](https://user-images.githubusercontent.com/42475929/60302575-25857b80-9902-11e9-95df-1c0f22e40a00.png)

**Comment by TheHaterofGravel** [comment]
using these mods-
![mod](https://user-images.githubusercontent.com/42475929/60303717-2c61bd80-9905-11e9-8b69-eba9ae102680.png)

**Comment by TheCodex6824** [comment]
I just pushed a fix for this to CurseForge, the update should be available soon. Sorry for the trouble and thank you for reporting it!
