### ISSUE TITLE
Renamed Warded Chests don't keep their name

### ISSUE THREAD

**Issue by DoomRater** [TheCodex6824/ThaumicAugmentation#140]
Vanilla Chest Behavior is that when you rename a chest or trapped chest, the name of the chest is displayed in the inventory.  The Warded Chest doesn't do this.  Since it looks like it was never designed to, I guess this is technically a feature request?  At least, according to Mojang's trackers it would be.  It's also far from the only Chest in modded Minecraft that doesn't- even Hungry Chests don't respect this.

**Comment by TheCodex6824** [comment]
It should be easy enough for me to add this.
