### ISSUE TITLE
The Warding Focus Effect issue

### ISSUE THREAD

**Issue by Speconicci** [TheCodex6824/ThaumicAugmentation#151]
When using Warding Focus with Touch on blocks like dirt, stone or cobblestone it's playing animation, but nothing happens actually. I can break this blocks as usual with bare hands after using focus effect at once.
![2021-02-18_16 32 40](https://user-images.githubusercontent.com/42351038/108372348-63d25b80-7207-11eb-97ac-0e3352352147.png)
![2021-02-18_16 33 17](https://user-images.githubusercontent.com/42351038/108372372-6af96980-7207-11eb-8915-0643ba9b5bf6.png)

**Comment by TechnoMysterio** [comment]
Could you post your modlist please? That might help to narrow down any potential mod conflicts.

**Comment by Speconicci** [comment]
> Could you post your modlist please? That might help to narrow down any potential mod conflicts.

All these mods are for 1.12.2 version. This list may be too long. What can you say? Thanks for your attention!
![SharedScreenshot](https://user-images.githubusercontent.com/42351038/108501290-bff5b800-72b9-11eb-80d4-131294856257.jpg)

**Comment by DoomRater** [comment]
"tlskincape"?
![you_have_angered_the_gods](https://user-images.githubusercontent.com/4010432/108508087-46de6c80-7289-11eb-9422-7aa23977c374.png)
Disable this mod then try again.

**Comment by TechnoMysterio** [comment]
Can't say I've heard of tlskincape before, but you can try removing it and see if that solves the issue I suppose. If that fails, then instead remove all the mods from the pack, create a test world with a warding spell and then readd them gradually to see if you can get the problem again.

**Comment by TheCodex6824** [comment]
Based on tlskincape being in your mod list I get the feeling you may be running a "special" setup. If that is the case, you need to make sure your UUID is not set to all 0s, or warding will break.

**Comment by TheCodex6824** [comment]
I'm assuming this has been resolved by my last comment. For the record, I'm not going to be the judge. jury, and executioner and instaban people or anything the second there's an indication they *might* be using pirated minecraft, but obviously I cannot support such setups. I'll always be happy to point out what the exact technical issue is (in this case, UUIDs), but you're on your own with getting that resolved.
