### ISSUE TITLE
[SUGESSTION] Even more gauntlets

### ISSUE THREAD

**Issue by Laurys15951** [TheCodex6824/ThaumicAugmentation#152]
Something I've been considering lately would it be possible to make cross Thaumic Augmentation/[Thaumic Additions: Reconstructed](https://www.curseforge.com/minecraft/mc-mods/thaumic-additions) gauntlets for the 3 op metals( Mithrillium, Adaminite, Mithminite), maybe even adding extra augmentation slots for the better gauntlets

**Comment by TheCodex6824** [comment]
I probably won't personally be adding that to this mod, but they are welcome to use my API to do so on their end if they wish.
