### ISSUE TITLE
Strange impetus generator related crash?

### ISSUE THREAD

**Issue by DaRetroCat** [TheCodex6824/ThaumicAugmentation#156]
For some reason if I connect these two relays together in the middle in this setup
![image](https://user-images.githubusercontent.com/71947170/113139338-d60d6700-91db-11eb-87fc-a9160470670e.png)
the game will crash with this crash report: https://pastebin.com/LW7c6PfN

but it gets weirder, if I instead connect the relays together using a impetus matrix
![image](https://user-images.githubusercontent.com/71947170/113140477-56809780-91dd-11eb-972e-5a2aa52d943c.png)
it wont crash immediately like before UNLESS the generators "refill" with impetus at different times THEN it will crash with this crash report: https://pastebin.com/xJdCHFtM i don't know why,

this is honestly the weirdest crash bug I've ever seen so hopefully its easily fixable.

**Comment by TechnoMysterio** [comment]
Thanks for the report, the crash logs should be helpful but if anything else is needed (like a log file) then we'll ask for it. There's probably some edge case here in the impetus code that's been overlooked, so Codex can look into it whenever he's not horribly busy.
