### ISSUE TITLE
Emptiness Dimension causes world leaking with Aether Mod installed

### ISSUE THREAD

**Issue by TheAGamePlayer** [TheCodex6824/ThaumicAugmentation#157]
Mods Installed:
aether-1.12.2-v1.5.3.1.jar
Baubles-1.12-1.5.2.jar
OptiFine_1.12.2_HD_U_G5.jar
Thaumcraft-1.12.2-6.1.BETA26.jar
ThaumicAugmentation-1.12.2-2.0.13.jar

Debug Log:
[debug.log](https://github.com/TheCodex6824/ThaumicAugmentation/files/6300679/debug.log)

How to reproduce:
1. Go into the aether dimension
2. Set dimension to the Emptiness
3. After about a minute of exploring you'll receive error messages
"The world 34953cb0 (New World) may have leaked: first encounter (5 occurrences)."
"The world 34953cb0 (New World) may have leaked: seen 10 times."
etc...

**Comment by TheCodex6824** [comment]
I'll look into this. Do you happen to know if it happens with any other dimension mods?

**Comment by TheAGamePlayer** [comment]
After some testing, I've had this issue happen with the Aether, The Midnight, and The BetweenLands. However with The BetweenLands, it does it less often than the other 2.
Heres the Debug Log for The BetweenLands:
[debug.log](https://github.com/TheCodex6824/ThaumicAugmentation/files/6314112/debug.log)

**Comment by TheCodex6824** [comment]
So while I was able to reproduce this with the Emptiness, I also observed world leaking occurring with no mods installed and just going from the nether to the overworld. I looked into how Forge determines if a world is leaking and it seems that false positives are possible. I get the feeling that this is simply a case of the JVM not cleaning up the world immediately, so Forge thinks it leaked. I took multiple heap dumps as well and none of them had any of my code holding world references, so I don't think I messed something up. 

So from what I can tell, that message is harmless in this case. However, I'll do some more testing at some point to see if there is some really complex thing going on that does make it my fault.

**Comment by TheAGamePlayer** [comment]
In 1.12.2 World Leaking is a bug with Forge it seems. However while testing this I did seem to reduce the frequency of world leaks by adding The Aether to the "FractureDimList" in the config file.

**Comment by TheCodex6824** [comment]
Interesting that adding it to the list of dimensions to generate fractures in made it better. I looked again and I still don't see anywhere that points to this mod doing something to leak worlds, so unless someone else notices something that I missed, I don't think I can really do anything to stop the world leak messages.
