### ISSUE TITLE
Incompatibility with Tinkers' Evolution

### ISSUE THREAD

**Issue by festro** [TheCodex6824/ThaumicAugmentation#158]
When trying to load the mod with Tinkers' Evolution I get a CTD around the 3rd stage of loading the game I am directed to this mod as being the culprit with this crash report https://paste.dimdev.org/zerafafiye.mccrash, however when disabling Tinkers' Evolution the game loads fine. I'll bring this up with the other mod author too.

**Comment by TheCodex6824** [comment]
It's Tinkers' Evolution crashing things, update that and you should be fine.
Ref:
https://github.com/phantamanta44/tinkers-evolution/issues/89
https://github.com/phantamanta44/tinkers-evolution/issues/90
