### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by thedeerirty** [TheCodex6824/ThaumicAugmentation#160]
Not sure exactly the cause, but I'm having a startup crash. Something about forge energy in relation to Thaumic Augmentation
[crash-2021-04-30_21.17.55-client.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/6408703/crash-2021-04-30_21.17.55-client.txt)

**Comment by TechnoMysterio** [comment]
Not sure what could be causing that, but do make sure you've got everything updated in your pack like the Forge version and assorted mods. Codex can have a look into that when he's available, although he's been very busy as of late so it might be a while I'm afraid.

**Comment by thedeerirty** [comment]
Understandable, thanks for the reply
If it's anything, I figure it would be the forge version but I figure I'd ask the people who know first. I'll see if I need to update forge

**Comment by TheCodex6824** [comment]
It seems like what is happening is that some item with Forge Energy is incorrectly advertising itself as also being an augment, which probably means that they didn't check what capability was being asked for in `getCapability`. Unfortunately, unless the offending mod can be identified, I can't really do much about it. If you do manage to figure out which one it is, I'd be happy to see if that is indeed the problem.

**Comment by TheCodex6824** [comment]
I'm going to close this since I'm 99% sure it's not this mod's fault. It's unfortunate that a lot of mods seem to misunderstand how `hasCapability` and `getCapability` work / relate to each other, but I can't even directly see what mod is doing that so there's nothing I can really do.
