### ISSUE TITLE
The emptyness is not chunkloadable

### ISSUE THREAD

**Issue by diegoag64** [TheCodex6824/ThaumicAugmentation#161]
I am playing on MC Eternal and for some reason I am not allowed to chunkload anything in the emptyness, is this intended? I have a mob farm setup here since I liked the area but nothing chunkloads. The mob farms that I have stop working and several other mods that rely on chunkloading (like Practical Logicstics 2 for the wireless storage transmitter) dont work.

Please let me know if you need any more info, of course I checked the map and all the blocks where im at are supposed to be chunkloaded

**Comment by TechnoMysterio** [comment]
Hmm, I don't think that should be happening, that can be looked into whenever possible (Codex has been very busy lately).

**Comment by TheCodex6824** [comment]
I could not reproduce this. I generated a fresh world and put a chunkloader in the emptiness with a command block that says things, then left the emptiness. The command block continued putting messages in chat. If you chunkload things a lot, check to make sure the max allowable number of chunkloading tickets has not been exceeded (IIRC there are per mod and per player limits in forge). If that is not the case, tell me what chunkloader mod you are using and I'll look into it further.

**Comment by anabsolutesloth** [comment]
@diegoag64 
Hi there, Moderator of MC Eternal's Discord here, you can't chunkload the Emptiness on purpose, why exactly i do not know, the pack creator (Adam) hasn't exactly given a reason i understand fully :p
