### ISSUE TITLE
starfield glass edges dont connect

### ISSUE THREAD

**Issue by apache435** [TheCodex6824/ThaumicAugmentation#162]
starfield glass edges dont connect any answers?
![image](https://user-images.githubusercontent.com/83790654/117370864-04dec300-ae95-11eb-8e55-cd20f07e04d0.png)

**Comment by TechnoMysterio** [comment]
Make sure you install ConnectedTexturesMod, that'll make blocks like that form neat borders. The CurseForge page/download for it is here: https://www.curseforge.com/minecraft/mc-mods/ctm

**Comment by apache435** [comment]
thanks
