### ISSUE TITLE
[SUGGESTION] Robes of the adept texture tweak

### ISSUE THREAD

**Issue by DaRetroCat** [TheCodex6824/ThaumicAugmentation#168]
Ive found the robes of the adept texture could use alittle tweak with the thaumium not meshing that well with the actual cloth so i decided to take a crack at it:
![image](https://user-images.githubusercontent.com/71947170/120259809-78cc7b00-c249-11eb-8f8b-27dc768dd98c.png)
Original version on the left my version on the right
![thaumium_robes](https://user-images.githubusercontent.com/71947170/120260603-12e0f300-c24b-11eb-97f2-ea341a972a4f.png)
![thaumium_robes_overlay](https://user-images.githubusercontent.com/71947170/120260605-13798980-c24b-11eb-9c4c-9838649d48f2.png)

**Comment by TheCodex6824** [comment]
Yeah that is an improvement for sure! So there's 2 options for how we can add this:

1. You can open a pull request with the new texture
2. I can add it in myself and tag you in the commit

Which would you prefer?

**Comment by DaRetroCat** [comment]
Id be fine with you just adding it in yourself and tagging me in the commit
