### ISSUE TITLE
Robes of the Adept

### ISSUE THREAD

**Issue by VerySaltyOreos** [TheCodex6824/ThaumicAugmentation#172]
Hey uhhhh how come they require thaumium plates for the recipe but are repaired using brass?

**Comment by TechnoMysterio** [comment]
Huh, that's either a glitch or an oversight. I mean I never thought to try repairing them in testing, so probably the latter. Anyway, that can be looked into, so thanks for reporting.

**Comment by TheCodex6824** [comment]
Nope it's my fault, originally I used plates as the repair material but when I switched it to ingots I forgot that the metadata between plates and ingots is not the same (like metadata 2 for plates is thaumium, but 2 on ingots is brass)

**Comment by VerySaltyOreos** [comment]
Don't get me wrong, I think brass armor would be cool. something stronger than normal cloth, and better at casting, but weaker than thaumium/iron (maybe stronger than iron due to it not being normal brass?). so you still have to choose between protection or utility, but to a lesser extent.
