### ISSUE TITLE
[KINDA SUGGESTION] Adept hoods, but they don't shadow your face into nothing but void

### ISSUE THREAD

**Issue by VerySaltyOreos** [TheCodex6824/ThaumicAugmentation#174]
On Player
![image](https://user-images.githubusercontent.com/82646318/121137297-20bee700-c7fc-11eb-97b2-e1a23a98d822.png)
On Stands to show inside
![image](https://user-images.githubusercontent.com/82646318/121137423-3c29f200-c7fc-11eb-8c8d-8f311a1cb5e0.png)
Still dye compatible
![image](https://user-images.githubusercontent.com/82646318/121137496-4ea42b80-c7fc-11eb-8dda-24ade4b805fa.png)

**Comment by TheCodex6824** [comment]
I think originally the hood shadowing the face was kept for consistency with the void robes (or because nobody wanted to deal with potentially changing the model), but that's not a very good reason to not consider it.

**Comment by VerySaltyOreos** [comment]
![image](https://user-images.githubusercontent.com/82646318/121604755-b4690100-ca10-11eb-8685-5ab237cdfee5.png)
![image](https://user-images.githubusercontent.com/82646318/121604763-ba5ee200-ca10-11eb-9dbe-629164f2b5e5.png)
Here's what I did for my resourcepack, probably not perfect but I like how it turned out

**Comment by TheCodex6824** [comment]
Ideally it would be nice if there was a way to toggle the hood between blocking face and not blocking, as I can see the appeal of having that option. I'm not sure what the most not-confusing way to do that would be, though.

**Comment by VerySaltyOreos** [comment]
> Ideally it would be nice if there was a way to toggle the hood between blocking face and not blocking, as I can see the appeal of having that option. I'm not sure what the most not-confusing way to do that would be, though. Since the robes of the adept are my item I can actually add a feature like that, which seems better than having it be different than the regular TC hoods all the time.

Perhaps just an option in the config file would work?

**Comment by TheCodex6824** [comment]
That could work, but some players might want to have their face show while others not, so it would be a shame to lock everyone to a client config option. I'm thinking of just making that one of those "put in crafting grid to toggle" type items like the primal cutter. I don't really love doing that because it's not the most intuitive thing, but it should need to be done so rarely that it should be fine. However, an inventory icon with it showing maybe the cloth in the back of the hood instead of a black void would help a lot with that, although I personally have no idea how to pull that off without being a purple blob, so I would need some help with that.

**Comment by VerySaltyOreos** [comment]
I'll take a crack at making some believeable icons, I don't have experience with art so it won't be great.

**Comment by VerySaltyOreos** [comment]
![2021-06-13_11 00 04](https://user-images.githubusercontent.com/82646318/121814509-130fc400-cc37-11eb-863c-75c51ca50d03.png)
![2021-06-13_11 00 53](https://user-images.githubusercontent.com/82646318/121814513-1acf6880-cc37-11eb-9ddd-7b6c6a23759c.png)
Did this in an hr, lemme know if you want the texture files

**Comment by VerySaltyOreos** [comment]
one thing I would change is the leather guard, it's a bit dark in my example.

**Comment by TheCodex6824** [comment]
I just checked the actual model textures and it looks like to add this I'll need to move quite a few things around to make room for another hood texture. So if I do that any resource pack, like the one you made, would need to be updated. Unfortunately the vanilla model system is kind of bad for this kind of case as it's not possible to just change 1 face of a cube - I have to duplicate it and edit the face that way, which wastes tons of space. So if you're fine with that breaking change, let me know.

**Comment by VerySaltyOreos** [comment]
I don't mind that at all, more stuff to try texturing. Besides I'm not really that satisfied with how it turned out.
Btw I used the default thaumcraft goggles of revealing texture for replacing the goggles, they're the same pixel size so it worked perfectly.

**Comment by TheCodex6824** [comment]
This is actually in the latest version now, it appears I missed this one when closing all the issues resolved in the last update.

**Comment by VerySaltyOreos** [comment]
> This is actually in the latest version now, it appears I missed this one when closing all the issues resolved in the last update.

How does it work texture wise? Asking because the latest update broke my resource pack so I wanna fix it ASAP

**Comment by TheCodex6824** [comment]
> > This is actually in the latest version now, it appears I missed this one when closing all the issues resolved in the last update.
> 
> How does it work texture wise? Asking because the latest update broke my resource pack so I wanna fix it ASAP

I had to move things around to make room, but the shadowless variant is simply placed directly to the right of the normal variant.

**Comment by VerySaltyOreos** [comment]
> > > This is actually in the latest version now, it appears I missed this one when closing all the issues resolved in the last update.
> > 
> > 
> > How does it work texture wise? Asking because the latest update broke my resource pack so I wanna fix it ASAP
> 
> I had to move things around to make room, but the shadowless variant is simply placed directly to the right of the normal variant.

Oh it's all one texture? That would explain the texture break. Thanks! I'll get to work :P
