### ISSUE TITLE
essentia not visible in glass tubes

### ISSUE THREAD

**Issue by CaptainShadow5** [TheCodex6824/ThaumicAugmentation#175]
Title says it all, can confirm there is essentia flowing through them, checked with the essentia resonator, but i can't see it flowing through the tubes like your supposed to.

**Comment by TechnoMysterio** [comment]
Do you have anything like OptiFine installed? If you do it might mess with the rendering of essentia in tubes.

**Comment by CaptainShadow5** [comment]
I did at one point, but not currently

**Comment by DoomRater** [comment]
A screenshot might help.  While I don't know all of the available renders that might be visible in the scene, I've seen all sorts of wonky things before including invisible enemies blocking out the face of zombies, and a lot of the times it's just the way OpenGL is told to render things.  A screenshot might be able to tell us whether it's a problem on a mod's end, or conflicting renders.

**Comment by TheCodex6824** [comment]
Can I have your mod list? I saw this happen once in testing, but it was also while I was messing with the glass tube renderer so I thought I just messed up. Going to a new world after restarting the game also fixed it, so that leads me to think a mod is doing some weird rendering.

**Comment by CaptainShadow5** [comment]
- 

> Can I have your mod list? I saw this happen once in testing, but it was also while I was messing with the glass tube renderer so I thought I just messed up. Going to a new world after restarting the game also fixed it, so that leads me to think a mod is doing some weird rendering.

Lucraft: Core
Lucraft
LucraftCore-1.12.2-2.4.13.jar
Planar Artifice Unofficial
Zokonius
planarartifice-1.0.0.jar
AcademyCraft
weathfold
AcademyCraft-1.1.3.jar
Actually Additions
Ellpeck
ActuallyAdditions-1.12.2-r152.jar
Additional Structures
XxRexRaptorxX
Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar
Anvil Infinity Craft
AnvilcraftMC
infinity-1.12.jar
Arcanum
xHellBreecher
arcanum-1.12.2-4.3.0.0.jar
Astral Additions
ArcAios26
astraladditions-1.12.2-1.0.0.jar
Astral Sorcery
HellFirePvP
astralsorcery-1.12.2-1.10.27.jar
AutoRegLib
Vazkii
AutoRegLib-1.3-32.jar
Avaritia 1.1x
brandon3055
Avaritia-1.12.2-3.3.0.37-universal.jar
Avaritia's Complement
tfarecnim
Avaritia's Complement-1.12.2-1.4.jar
Avaritiaddons
WanionCane
Avaritiaddons-1.12.2-1.2.jar
Baubles
Azanor13
Baubles-1.12-1.5.2.jar
Bewitchment (Legacy)
sunconure11
bewitchment-1.12.2-0.0.22.64.jar
BiblioCraft
Nuchaz
BiblioCraft[v2.4.5][MC1.12.2].jar
Block Drops (JEI Addon)
KidsDontPlay
blockdrops-1.12.2-1.4.0.jar
Blood Magic
WayofTime
BloodMagic-1.12.2-2.4.3-105.jar
Botania
Vazkii
Botania r1.10-364.4.jar
Brandon's Core
brandon3055
BrandonsCore-1.12.2-2.4.19.214-universal.jar
Building Gadgets
Direwolf20
BuildingGadgets-2.8.4.jar
CB Multipart
covers1624
ForgeMultipart-1.12.2-2.6.2.83-universal.jar
Chicken Chunks 1.8.+
covers1624
ChickenChunks-1.12.2-2.4.2.74-universal.jar
Chisel
tterrag1098
Chisel-MC1.12.2-1.0.2.45.jar
Chisels & Bits
AlgorithmX2
chiselsandbits-14.33.jar
CodeChicken Lib 1.8.+
covers1624
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
CoFH Core
TeamCoFH
CoFHCore-1.12.2-4.6.6.1-universal.jar
CoFH World
TeamCoFH
CoFHWorld-1.12.2-1.4.0.1-universal.jar
ConnectedTexturesMod
tterrag1098
CTM-MC1.12.2-1.0.2.31.jar
Cosmetic Armor Reworked
LainMI
CosmeticArmorReworked-1.12.2-v5a.jar
Crimson Revelations
mobiusflip
crimsonrevelations-0.8.jar
Cucumber Library
BlakeBr0
Cucumber-1.12.2-1.1.3.jar
Cyclops Core
kroeser
CyclopsCore-1.12.2-1.6.7.jar
DimensionalDoors
DimensionalDevelopment
DimensionalDoors-1.12.2-3.1.2-UNOFFICIAL.jar
Doctor Who - Regeneration
Suff99
Regeneration-1.12.2-3.0.2.jar
Draconic Evolution
brandon3055
Draconic-Evolution-1.12.2-2.3.27.353-universal.jar
DummyCore Unofficial
TheLMiffy1111
DummyCoreUnofficial-2.4.112.5.jar
Ender IO
idontwantthisaccount4
EnderIO-1.12.2-5.3.70.jar
EnderCore
tterrag1098
EnderCore-1.12.2-0.5.76.jar
EvilCraft
kroeser
EvilCraft-1.12.2-0.10.78.jar
Expanded Arcanum
mallrat208
ExpandedArcanum-1.0.1.jar
Extra Utilities
Forge_User_06804776
extrautils2-1.12-1.9.9.jar
Fancy Lamps
a_frosted_one
fancylamps-1.2.1.jar
Forbidden and Arcanus
cesar_zorak
forbidden_arcanus-1.12.2-1.1.4.jar
Guide-API
TehNut
Guide-API-1.12-2.1.8-63.jar
Hammer (Lib) Core
Zeitheron
HammerLib-1.12.2-2.0.6.26.jar
HeroesExpansion
Lucraft
HeroesExpansion-1.12.2-1.3.5.jar
Hwyla
TehNut
Hwyla-1.8.26-B41_1.12.2.jar
IBE Editor
Franckyi
IBEEditor-1.12.2-1.0.0-alpha5.jar
Ice and Fire: Dragons
alex1the1666
iceandfire-1.9.1-1.12.2.jar
Immersive Engineering
BluSunrize
ImmersiveEngineering-0.12-98.jar
Infinity Item Editor
Ruukas
Infinity-0.14.2.jar
IronMan
Lucraft
IronMan-1.12.2-Beta-1.12.2-1.2.6.jar
JEI Integration
SnowShock35
jeiintegration_1.12.2-1.6.0.jar
JEI Villagers
Buuz135
jeivillagers-1.12-1.0.2.jar
JourneyMap
techbrew
journeymap-1.12.2-5.7.1.jar
Just Enough Items (JEI)
mezz
jei_1.12.2-4.16.1.301.jar
Just Enough Resources (JER)
way2muchnoise
JustEnoughResources-1.12.2-0.9.2.60.jar
JustEnoughIDs
Runemoro
JustEnoughIDs-1.0.3-55.jar
LibrarianLib
wiresegal
librarianlib-1.12.2-4.22.jar
Librikka API
rikka0w0
librikka-1.0.0.jar
LLibrary
_ForgeUser11902522
llibrary-1.7.20-1.12.2.jar
Lost Magic
Spiteful_Fox
lostmagic-1.0.2.jar
LunatriusCore
Lunatrius
LunatriusCore-1.12.2-1.2.0.42-universal.jar
Magic Arsenal
falkreon
MagicArsenal-MC1.12_ver1.2.5.jar
MagicalSculpture
yuriscat
magicalsculpture-1.0.0.jar
Mahou Tsukai
stepcros
mahoutsukai-1.12.2-v1.19.46.jar
Mantle
mDiyo
Mantle-1.12-1.3.3.55.jar
MC Terrain Editor
ngt5479
MCTE2.4.10-24_forge-1.12.2-14.23.2.2611.jar
MrCrayfish's Furniture Mod
MrCrayfish
furniture-6.3.1-1.12.2.jar
MrTJPCore
MrTJP
MrTJPCore-1.12.2-2.1.4.43-universal.jar
Mystical Agriculture
BlakeBr0
MysticalAgriculture-1.12.2-1.7.5.jar
New TARDIS Mod
spectre0987
tardis-0.1.4A.jar
NGTLib
ngt5479
NGTLib2.4.18-35_forge-1.12.2-14.23.2.2611.jar
Not Enough Items 1.8.+
covers1624
NotEnoughItems-1.12.2-2.4.3.245-universal.jar
Patchouli
Vazkii
Patchouli-1.0-23.6.jar
Project Red - Compat
MrTJP
ProjectRed-1.12.2-4.9.4.120-compat.jar
Project Red - Core
MrTJP
ProjectRed-1.12.2-4.9.4.120-Base.jar
Project Red - Expansion
MrTJP
ProjectRed-1.12.2-4.9.4.120-mechanical.jar
Project Red - Illumination
MrTJP
ProjectRed-1.12.2-4.9.4.120-lighting.jar
Project Red - Integration
MrTJP
ProjectRed-1.12.2-4.9.4.120-integration.jar
Psi
Vazkii
Psi-r1.1-78.2.jar
Psionic Peripherals
Dudblockman
psipherals-1.1.0.jar
PymTech
Lucraft
PymTech-1.12.2-1.0.2.jar
Quark
Vazkii
Quark-r1.6-179.jar
Random PSIdeas
kamefrede123
rpsideas-2.4.4.jar
Random Things
Lumien231
RandomThings-MC1.12.2-4.2.7.4.jar
Redstone Flux
TeamCoFH
RedstoneFlux-1.12-2.1.1.1-universal.jar
Reliquary v1.3
P3pp3rF1y
Reliquary-1.12.2-1.3.4.796.jar
Schematica
Lunatrius
Schematica-1.12.2-1.8.0.169-universal.jar
Shadowfacts' Forgelin
ShadowfactsDev
Forgelin-1.8.4.jar
Speedster Heroes
Lucraft
SpeedsterHeroes-1.12.2-2.2.1.jar
Star Tech, Man! The Legendary Mod?
nictogen
star-tech-1.1.1.jar
Structures Orb
spraxsuper
structures orbs [update 1!].jar
Thaumcraft
Azanor13
Thaumcraft-1.12.2-6.1.BETA26.jar
Thaumcraft 6 Aspects for JEI
zabi94
tc6aspects4jei-0.0.2a.jar
Thaumic Additions: Reconstructed
Zeitheron
ThaumicAdditions-1.12.2-12.6.7.jar
Thaumic Arcana
thefrontrider
Thaumic Arcana-1.3.0.jar
Thaumic Augmentation
TheCodex6824
ThaumicAugmentation-1.12.2-2.1.1.jar
Thaumic Bases Unofficial
Rumaruka
thaumicbases-3.3.500.6r.jar
Thaumic Brewing
daedalus4096
thaumicbrewing-1.0.2.jar
Thaumic Gadgets
ArcAnc
Thaumic_Gadgets_1.12.2_0.1.6_tb.26.jar
Thaumic Inventory Scanning (Thaumcraft Addon)
BlayTheNinth
ThaumicInventoryScanning_1.12.2-2.0.10.jar
Thaumic JEI
Buuz135
ThaumicJEI-1.12.2-1.6.0-27.jar
Thaumic Periphery
cadaverous_queen
thaumicperiphery-0.3.1.jar
Thaumic Restoration
Zokonius
ThaumicRestoration-1.5.0.jar
Thaumic Tinkerer
gaeakat
thaumictinkerer-1.12.2-5.0-620a0c5.jar
Thaumic Wonders
daedalus4096
thaumicwonders-1.8.2.jar
The Aether II
GildedGames
aether_ii-1.12.2-0.3.0+build411-universal.jar
The Twilight Forest
Benimatic
twilightforest-1.12.2-3.11.1021-universal.jar
Tinkering with Blood Magic
terrapin47
bloodtinker-1.0.5.jar
Tinkers Construct
mDiyo
TConstruct-1.12.2-2.13.0.183.jar
WanionLib
WanionCane
WanionLib-1.12.2-2.5.jar
Wawla - What Are We Looking At
DarkhaxDev
Wawla-1.12.2-2.6.275.jar
Waystones
BlayTheNinth
Waystones_1.12.2-4.1.0.jar

**Comment by Danymaddox** [comment]
Hi! I have the same problem but I have different modlist. I will post here all mods I have in common with CaptainShadow5:

Planar Artifice Unofficial - Zokonius - planarartifice-1.0.0.jar
Baubles - Azanor13 - Baubles-1.12-1.5.2.jar
Thaumcraft - Azanor13 - Thaumcraft-1.12.2-6.1.BETA26.jar
Thaumic Additions: Reconstructed - Zeitheron - ThaumicAdditions-1.12.2-12.6.7.jar
Thaumic Arcana - thefrontrider - Thaumic Arcana-1.3.0.jar
Thaumic Augmentation - TheCodex6824 - ThaumicAugmentation-1.12.2-2.1.1.jar
Thaumic Bases Unofficial - Rumaruka - thaumicbases-3.3.500.6r.jar
Thaumic Gadgets - ArcAnc - Thaumic_Gadgets_1.12.2_0.1.6_tb.26.jar
Thaumic Inventory Scanning (Thaumcraft Addon) - BlayTheNinth - ThaumicInventoryScanning_1.12.2-2.0.10.jar
Thaumic JEI - Buuz135 - ThaumicJEI-1.12.2-1.6.0-27.jar
Thaumic Periphery - cadaverous_queen - thaumicperiphery-0.3.1.jar
Thaumic Restoration - Zokonius - ThaumicRestoration-1.5.0.jar
Thaumic Tinkerer - gaeakat - thaumictinkerer-1.12.2-5.0-620a0c5.jar
Thaumic Wonders - daedalus4096 - thaumicwonders-1.8.2.jar
The Twilight Forest - Benimatic - twilightforest-1.12.2-3.11.1021-universal.jar
Wawla - What Are We Looking At - DarkhaxDev - Wawla-1.12.2-2.6.275.jar

**Comment by CaptainShadow5** [comment]
Mine are also working, the only thing that's changed is a windows update

**Comment by TheCodex6824** [comment]
Yeah this was a tricky one, turns out that certain blocks change something related to rendering and then don't set it back when they're done. It's so inconsistent because you need to have one of these blocks render to have the essentia become invisible. But it should be fixed for the next update.
