### ISSUE TITLE
Random entity update tick crash

### ISSUE THREAD

**Issue by bloche14** [TheCodex6824/ThaumicAugmentation#18]
This is the second time this crash happens to me - seemingly randomly. The first time it was with a bat instead of a squid:
https://paste.dimdev.org/jupiwohuxa.mccrash

**Comment by TheCodex6824** [comment]
I'm adding a check to hopefully stop you from crashing, but I was unable to reproduce this with a minimal test setup. One of your mods might be doing something weird, but either way the crashing should stop.
