### ISSUE TITLE
AutoCaster and Observer forgetting their owner

### ISSUE THREAD

**Issue by krovex101** [TheCodex6824/ThaumicAugmentation#180]
I have had a number of cases where an AutoCaster/Observer left for a while, but when I came back to move or adjust them they now say "This does not belong to you" what could cause this?

**Comment by Vapaman** [comment]
Can confirm this happens on multiplayer. My friend logged off while the observer was loaded by me. Then they came back and it reports "This does not belong to you" to both of us. Strangely, the one probe still says that the observer belongs to them.

**Comment by TheCodex6824** [comment]
I think I have an idea of what's going on - I cache the owner so I don't have to scan all the entities every time something wants to know who the owner is, but it sounds like it's holding onto old data so it doesn't recognize the "new" version of the owner. I bet that it fixes itself on a server / world restart, but sorry that it's happening!

**Comment by krovex101** [comment]
From bug being reported to a potential fix in a day I am impressed!
