### ISSUE TITLE
Optifine CTD

### ISSUE THREAD

**Issue by TheDiamondFox42** [TheCodex6824/ThaumicAugmentation#181]
I'm getting a crash involving every time I open my inventory or enter 3rd person mod. 
[crash-2021-06-19_19.30.37-client.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/6681455/crash-2021-06-19_19.30.37-client.txt)
I have the crashlog.

**Comment by TheCodex6824** [comment]
Sorry about that, this will be fixed in the next update. In the meantime, you can play the game if you add `thecodex6824.thaumicaugmentation.core.transformer.TransformerRenderCape` to the `DisabledTransformers` config option. It should be in general options.
