### ISSUE TITLE
[Improvement] Impetus bar when "dialBottom: true"

### ISSUE THREAD

**Issue by Vapaman** [TheCodex6824/ThaumicAugmentation#182]
![2021-06-20_18 22 54](https://user-images.githubusercontent.com/77460466/122679695-8cd61d80-d1f4-11eb-9ef7-82daedd119f6.png)
As you can see, when the gauntlet "dialBottom" option from TC6 config is set to true the impetus meter still stays in the upper left corner.

**Comment by TechnoMysterio** [comment]
Hmm, didn't even know that was a config option in TC6, Codex probably missed that as well. Hopefully it shouldn't be too hard to fix that.

**Comment by Vapaman** [comment]
Yeah it's quite obscure. Not too many people look into the thaumcrafts configs, but this would be nice for those who prefer the dial at the bottom.
