### ISSUE TITLE
Thaumic Augmentations Eldritch Guardians aren't considered undead

### ISSUE THREAD

**Issue by Vapaman** [TheCodex6824/ThaumicAugmentation#185]
The eldritch guardians that Thaumic Augmentation adds are not considered undead mobs, so that means that withers attack them, they can be corrupted by taint and they don't take extra damage from smite enchantment. This is inconsistent with Thaumcrafts own Eldritch Guardians which are considered undead.

**Comment by DoomRater** [comment]
The question is... are they?  Refer to #126 as to why I argued they should be not considered undead.

Also, undead monsters cannot be tainted?  That's news.

**Comment by TheCodex6824** [comment]
At this point I have to think about what to do about it, because there seem to be good arguments for both them being undead and not being undead. Apparently, while eldritch guardians are undead, eldritch *wardens* are not, which seems a bit odd. I even went back and checked TC4 and it's the same there, so I'm not sure what the reasoning is behind that difference.

**Comment by Vapaman** [comment]
Yea it seems a bit arbitary. But I would switch them to be undead, because that would be more consistent with vanilla TC6 and would prevent eldritch guardians from being tainted. It also would be consistent with the aspect they contain (examinis, the undead aspect).

![2021-06-22_22 36 20](https://user-images.githubusercontent.com/77460466/122988363-55a96d00-d3aa-11eb-8faa-03efae6973f5.png)

When the eldritch guardian is tainted they are buffed up a lot, and that can also occur naturally sometimes, when a taint seed spawn on top of a spire. I think its up to you to decide wheter you want to keep the feature.

**Comment by DoomRater** [comment]
I will say it's no big deal to me- I suggested it mainly to buff them a bit as they were too squishy with enchant restrictions off.  (In my pack, players can apply both smite AND sharpness to a weapon)

**Comment by TheCodex6824** [comment]
If they have exanimis then that's a pretty big point in favor of them being undead. As for your concerns about squishiness, normally they can't combine those enchants so it should be fine. I'll leave a config option in though to make them not undead again so modpacks can balance that as they see fit.
