### ISSUE TITLE
Adept Hood can be augmented with faceplates without the Fortress Armor faceplates research?

### ISSUE THREAD

**Issue by DoomRater** [TheCodex6824/ThaumicAugmentation#187]
This is interesting.  I haven't gotten far enough in Infusion to make Thaumium Fortress Armor or Face plates, but I have done Robes of the Adept and JEI is saying I can integrate face plates into the hood.

**Comment by Vapaman** [comment]
Can confirm. It lets me apply the faceplates as soon as I have the Robes of the Adept research.
The infusion for the Sipping fiend faceplate starts
![2021-07-01_22 06 58](https://user-images.githubusercontent.com/77460466/124177284-add22480-dab8-11eb-8f67-4ce314907fdf.png)
As you can see I dont have the research for the faceplates
![2021-07-01_22 05 37](https://user-images.githubusercontent.com/77460466/124177292-b0cd1500-dab8-11eb-8329-c8de3510272a.png)
