### ISSUE TITLE
[Bug] Impetus bar overlaps with the dial display when the gauntlet is equipped on the off-hand slot

### ISSUE THREAD

**Issue by Turkey9002** [TheCodex6824/ThaumicAugmentation#189]
![comparison](https://user-images.githubusercontent.com/86805568/124191193-0e496d80-da89-11eb-95f3-4d10573ffa7a.png)
I have it set to display the gui on the bottom rather than the top but it's the same case without that option turned on.

**Comment by Vapaman** [comment]
Can confirm this happens with me as well. This happens wheter or not dialBottom is true or not.
![kuva](https://user-images.githubusercontent.com/77460466/124195134-76707180-dad2-11eb-89db-75156bb5f64e.png)
