### ISSUE TITLE
SF with TA - onFallDamage, onTick

### ISSUE THREAD

**Issue by SSKirillSS** [TheCodex6824/ThaumicAugmentation#19]
TA simply lag on spongeforge.
Timings: https://timings.aikar.co/?id=a038ee752702463dbdeae5cf2d9f241f
Server dumps indicate problems with conservation, but no such, entity profiling also did not give results.

Versions:
TA: ThaumicAugmentation-1.12.2-1.1.2
SF: spongeforge-1.12.2-2838-7.1.7-RC3848
Forge: forge-1.12.2-14.23.5.2838-universal

Perhaps it has something to do with https://github.com/TheCodex6824/ThaumicAugmentation/issues/18

**Comment by TheCodex6824** [comment]
So I think I should have solved the performance issues you were facing (thank you for the timings by the way). If you're still running into lag issues from this mod feel free to reopen this.
