### ISSUE TITLE
Weird graphical issues on magic mirror starfield glass and reinforced/rift jars when changing resource packs

### ISSUE THREAD

**Issue by Turkey9002** [TheCodex6824/ThaumicAugmentation#190]
So this is a really strange thing that ends up happening but I wasn't entirely sure if it was actually caused by my computer, by thaumcraft, or by the addon itself. 

Changing resource packs seems to affect the appearance of magic mirror starfield glass, giving it an appearance similar to the rift starfield glass and the end portal. Magic mirrors themselves aren't affected and still have the same fancy starry look. I've also further tested this without any other mods and used smaller resource packs and it still occurs. In other instances reinforced jars and rift jars get a really messed up texture on the inventory like the one in the screenshots but I've also seen it having a taint texture a few times from testing. The jars still look normal when placed down and changing resource packs a second time reverts the messed up texture, although it still will change back when you change resource packs yet again.

I've also compared it to the jars from normal thaumcraft and they haven't been affected by this.

![2021-07-02_07 08 40](https://user-images.githubusercontent.com/86805568/124275976-d8e46480-db08-11eb-8ee7-1affb30af17d.png)
![2021-07-02_07 09 09](https://user-images.githubusercontent.com/86805568/124276135-0d582080-db09-11eb-929e-f390b1a92de1.png)

It might be hard to notice here due to the lighting but the magic mirrors are unaffected as well. Personally I wouldn't mind if this version of the glass was a feature, it could be obtained by combining magic mirror and rift together on a workbench to produce two.

![2021-07-02_07 46 39](https://user-images.githubusercontent.com/86805568/124276682-bacb3400-db09-11eb-9d81-cf993e1beeb1.png)

**Comment by TheCodex6824** [comment]
Good catch, it turns out that the blur effect on that texture gets reset when the textures get reloaded from changing resource packs (and apparently I needed to manually bind the texture, or Minecraft would happily apply the blur to the wrong one...). I couldn't get the jar to have a weird texture, but I wouldn't be surprised if this issue was actually the one that caused it.

I'll mark this as fixed for now, but if you still get the corrupted jar texture in the next update, let me know and I'll take another look.

**Comment by Vapaman** [comment]
I've noticed that the jar texture bugs out when you load a resource pack that actually changes textures (I don't know if its any textures or just augmentations textures). If it just changes sounds or something similiar, the jar texture doesn't change.

**Comment by TheCodex6824** [comment]
> I've noticed that the jar texture bugs out when you load a resource pack that actually changes textures (I don't know if its any textures or just augmentations textures). If the resource pack just changes sounds or something similiar, the jar texture doesn't change.

Interesting. I'll give that a try later today, I was just pressing f3+t to trigger the resource reload.

**Comment by VerySaltyOreos** [comment]
Are you by chance using emberturgist's standard? I've noticed a recent spike in people downloading it <3

I found where the texture is coming from btw, I think it's from the arcane pressure plate
![2021-07-04_04 41 23](https://user-images.githubusercontent.com/82646318/124380497-72835180-dc82-11eb-9b0e-2b4f08a8ccbd.png)


I was actually going to report that something in the update broke resource packs, as this is what my adept armor looks like now.
![2021-07-04_04 30 21](https://user-images.githubusercontent.com/82646318/124380431-2cc68900-dc82-11eb-8a6e-68d9dfd0a5ba.png)
I tried doing it with the default texture too, but it seems that it's just broken when loading a resource pack.

**Comment by Turkey9002** [comment]
I do have that resource pack actually! I've also used that to do some further testing and found out that changing textures aren't affecting the jar's model even if it's Thaumcraft or Thaumic Augmentation, but changing models does affect it I've had a few moments where nothing happened which is very strange I can at least say that it has something to do with changing models through resource packs. There were also a few other textures outside the arcane trapdoor that the jar changed to, the taint texture I mentioned before I think it's crusted taint and three other textures I couldn't identify. As for the armor I'm not exactly sure what's causing that but only your pack seems to affect it.
![2021-07-04_11 14 32](https://user-images.githubusercontent.com/86805568/124392661-9d8a9700-dcbc-11eb-92f2-eae253f17265.png)

**Comment by VerySaltyOreos** [comment]
I think the armor is just happening because I added a texture for it, but something in the newest update broke it.
I know it's the update because downgrading it to the previous version works fine.

**Comment by VerySaltyOreos** [comment]
> I do have that resource pack actually! I've also used that to do some further testing and found out that changing textures aren't affecting the jar's model even if it's Thaumcraft or Thaumic Augmentation, but changing models does affect it I've had a few moments where nothing happened which is very strange I can at least say that it has something to do with changing models through resource packs. There were also a few other textures outside the arcane trapdoor that the jar changed to, the taint texture I mentioned before I think it's crusted taint and three other textures I couldn't identify. As for the armor I'm not exactly sure what's causing that but only your pack seems to affect it.
> ![2021-07-04_11 14 32](https://user-images.githubusercontent.com/86805568/124392661-9d8a9700-dcbc-11eb-92f2-eae253f17265.png)

Working on a fix rn, turns out codex added something I suggested and it broke the resourcepack texture lol.
I'll be uploading it later today, just a quick fix

**Comment by TheCodex6824** [comment]
The armor is a separate issue that was caused by me changing the armor texture UVs to add a feature, so that broke the resource pack (sorry!), the jar thing I am investigating.

**Comment by VerySaltyOreos** [comment]
> The armor is a separate issue that was caused by me changing the armor texture UVs to add a feature, so that broke the resource pack (sorry!), the jar thing I am investigating.

That's fine, I already made a fix for the resource pack. Uploading today :P
![2021-07-04_20 13 14](https://user-images.githubusercontent.com/82646318/124405678-de0e0300-dd04-11eb-8ef0-b2223a4b6174.png)

**Comment by TheCodex6824** [comment]
I think I figured it out, turns out that I actually was caching the jar model somewhere and not refreshing it on resource reload...
