### ISSUE TITLE
Voidseer's Gauntlet is uncraftable

### ISSUE THREAD

**Issue by Dayyer1** [TheCodex6824/ThaumicAugmentation#2]
Not much to it. I'm using version 1.0.1. I have everything set up correctly, and I can't get the process to start. Other infusions work.
Using Forge 2836.

**Comment by TheCodex6824** [comment]
I just gave it a try and everything seemed to work for me (although I found out that it doesn't save the foci if there's one in the gauntlet, so that's bad...). Have you fully completed the research? TC6 doesn't let you craft things unless you did the research (JEI will always show it)

**Comment by Dayyer1** [comment]
I figured it out. There was a primordial mote on one of the pedestals leftover from a previous craft. It was faint, so I didn't see it. Oops :)

**Comment by TheCodex6824** [comment]
> I figured it out. There was a primordial mote on one of the pedestals leftover from a previous craft. It was faint, so I didn't see it. Oops :)

I'm glad you were able to figure it out. Me trying the infusions again did let me notice a bug I missed before, so I should be thanking you anyway :)
