### ISSUE TITLE
Crash on startup - Some kind of conflict with other mods in latest version

### ISSUE THREAD

**Issue by bloche14** [TheCodex6824/ThaumicAugmentation#20]
Here's the crash log. It started happening with the latest update:
https://paste.dimdev.org/cujavehugi.mccrash

**Comment by bloche14** [comment]
Removed Aether Legacy, now it's Earthworks:
https://paste.dimdev.org/awejezigiy.mccrash

**Comment by bloche14** [comment]
Removing both mods stops the issue from happening

**Comment by TheCodex6824** [comment]
Thanks for reporting this, there should be a fixed version at https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/2741499
