### ISSUE TITLE
Infusions

### ISSUE THREAD

**Issue by DaredEnemyKilla** [TheCodex6824/ThaumicAugmentation#200]
None of the infusions from Thaumcraft and Thaumic Augmentation work on my server after putting in augmentation. The server is just FTB Revelation with Thaumic Augmentation added

**Comment by TheCodex6824** [comment]
Did you figure this out or is it still a problem?

**Comment by DaredEnemyKilla** [comment]
I did sorry. I placed altars in my downstairs area and the infusion altar somehow reached them. Sorry for the issue
