### ISSUE TITLE
[Suggestion] Blur effect for obelisks and ancient doorways 

### ISSUE THREAD

**Issue by Turkey9002** [TheCodex6824/ThaumicAugmentation#204]
![Comparison1](https://user-images.githubusercontent.com/86805568/125039971-b5676f80-e05c-11eb-9534-0a3bac93ea70.png)
![Comparison2](https://user-images.githubusercontent.com/86805568/125039992-ba2c2380-e05c-11eb-85b3-fa61144015f4.png)
There was a blur effect used on them in older Thaumcraft versions so I thought of suggesting this.
(Comparison between Thaumcraft 5 and Thaumic Augmentation)

**Comment by Vapaman** [comment]
Yea I support this change, it even has the blur in TC4.
![2021-07-09_23 05 13](https://user-images.githubusercontent.com/77460466/125130730-26189580-e10a-11eb-993e-85bd84f45607.png)

**Comment by Vapaman** [comment]
Interestingly enough TC2 obelisks do not have the blur effect so maybe its up to which looks better.
![2021-07-09_23 10 17](https://user-images.githubusercontent.com/77460466/125131098-dab2b700-e10a-11eb-90e2-2a698b48b5a1.png)

**Comment by Turkey9002** [comment]
I think it might have been a limitation or it wasn't thought of back then until Thaumcraft 4 was made. I personally prefer it as blurred as that's what was in 4-5, but I wonder if a config is possible for preferences.

**Comment by TheCodex6824** [comment]
If you look closely you can see that the TC4 effect has particles that are more like the magic mirror effect, while the current TA ones and TC2 use the flux rift effect. I forget why I used the flux rift one specifically - it might have just been before I wired up the other effects.
