### ISSUE TITLE
[Bug] Starfield Glass: Mirror and Fracture are craftable as soon as Starfield Glass: Rift is researched

### ISSUE THREAD

**Issue by Vapaman** [TheCodex6824/ThaumicAugmentation#207]
Starfield Glass: Mirror and Starfield Glass: Dimensional Fracture are craftable despite not being researched.
![2021-07-10_20 34 29](https://user-images.githubusercontent.com/77460466/125171729-4b66db80-e1be-11eb-941e-9120505f5620.png)
![2021-07-10_20 34 38](https://user-images.githubusercontent.com/77460466/125171730-4e61cc00-e1be-11eb-93a3-0f8a39a14a44.png)
![2021-07-10_20 34 46](https://user-images.githubusercontent.com/77460466/125171732-50c42600-e1be-11eb-93dd-5fea3b942c5c.png)

**Comment by DoomRater** [comment]
Does that research say the researches have started or have not been started yet?  There's a vanilla TC6 bug that unlocks all recipes from a research category the instant it's started.

**Comment by Vapaman** [comment]
No, they haven't been started (you can see in the 3rd picture it just has the starfield glass: rift). I don't even have the requirements (Mirror and Fracture research).

**Comment by TheCodex6824** [comment]
There are some issues with vanilla TC research requirements for recipes, but in this case it was just me forgetting to change the research key on the glass recipes (I'm guessing I copied the rift one).
