### ISSUE TITLE
[Bug?] Thaumostatic Harness negates fall damage completely

### ISSUE THREAD

**Issue by Vapaman** [TheCodex6824/ThaumicAugmentation#209]
In previous versions the thaumostatic harness would reduce fall damage with the girdle equiped, but Augmentations harness seems to prevent fall damage completly as long as its charged. I think this is maybe unintentional, because there is no mention of this in the thaumonomicon. I would like to preserve some form of this possible bug in the future with implementing it to the gyroscope upgrade. This would make it a more viable choice to the girdle upgrade.

**Comment by TheCodex6824** [comment]
Always cancelling fall damage is not intentional - I have to check what might be causing that to happen. It might be because flight is enabled while wearing it, but I have to check.
