### ISSUE TITLE
Something goes too wrong(

### ISSUE THREAD

**Issue by shoverno2** [TheCodex6824/ThaumicAugmentation#21]
The coordinates of any block broken by player become warded.
Sometimes lage area become warded((
There's no crash, except log file((((

**Comment by TheCodex6824** [comment]
Are you 100% sure it's warded? It will have the special rune particle effect when punched or show sparkles when holding a caster with a ward focus. The only reason I ask is because I've been testing this version in a survival world for a little while now and haven't had this happen.

**Comment by TechnoMysterio** [comment]
What exactly is happening? Are you on a server, are you in singleplayer? Where are you breaking blocks and how? Are you using a particular mod pack? I can't seem to replicate this problem in singleplayer at least, I can break blocks freely and nothing gets warded in the process, so some extra detail on this problem would be helpful.

**Comment by shoverno2** [comment]
Well, i'm 101% sure:
1) it's glowing, when holding ward focus
2) changed world, reloaded mod, still breaking block makes block coordinates warded
I will try mod without others...

**Comment by shoverno2** [comment]
Well, still weird warding at 3 mods;
1)baubles
2)thaumcraft
3)thaumic augmentation
All at last version
It's singleplayer
No unknown mods and other mods
regular options
just fresh forge and 3 mods
That's all what i know for now...

**Comment by shoverno2** [comment]
Well, nest new news:
1) i can't see the runic ripples when hitting warded block
2) Without mod's core working any world loading will cause crash
3) After reloading world all weird wards disappear(but still appear, when block destroyed
4) Disabling warding module resolve problem(But i like new warding system)
5) warded chest\doors works perfect
6) Any "normally" warded by gauntlet wardings become bigger and bugging

**Comment by TechnoMysterio** [comment]
Would you perhaps be able to provide a video of whatever is going on here? Alternatively, a set of pictures? A visual example of some kind may help to clarify the exact problem. I'm assuming you're using Thaumic Augmentation 1.1.4 too.

**Comment by shoverno2** [comment]
of course i can:
nothing
![2019-07-16_20 03 15](https://user-images.githubusercontent.com/50020726/61314279-02653200-a805-11e9-95bf-0b8fa4b08f43.png)
breaken block
![2019-07-16_20 02 51](https://user-images.githubusercontent.com/50020726/61314280-02fdc880-a805-11e9-87d5-ca17130ff229.png)
world reload
![2019-07-16_20 02 46](https://user-images.githubusercontent.com/50020726/61314281-02fdc880-a805-11e9-9404-ae1633a53a28.png)
nothing
![2019-07-16_20 04 06](https://user-images.githubusercontent.com/50020726/61314305-0d1fc700-a805-11e9-8d16-3ddd635f7ced.png)
spell casted
![2019-07-16_20 04 05](https://user-images.githubusercontent.com/50020726/61314306-0d1fc700-a805-11e9-948e-80cb7e179aed.png)
warded
![2019-07-16_20 04 03](https://user-images.githubusercontent.com/50020726/61314307-0d1fc700-a805-11e9-8b11-c33d21d5ac5c.png)
"stranger things"(world reloaded)
![2019-07-16_20 04 01](https://user-images.githubusercontent.com/50020726/61314308-0d1fc700-a805-11e9-8abc-61dda73f12c9.png)
![2019-07-16_20 03 41](https://user-images.githubusercontent.com/50020726/61314310-0d1fc700-a805-11e9-80c4-6320a50bd157.png)
![2019-07-16_20 03 37](https://user-images.githubusercontent.com/50020726/61314311-0db85d80-a805-11e9-8e47-602e714d6f35.png)
![2019-07-16_20 03 35](https://user-images.githubusercontent.com/50020726/61314312-0db85d80-a805-11e9-84e2-e7ee6efbea86.png)

**Comment by shoverno2** [comment]
of course i can:

nothing
![2019-07-16_20 02 46](https://user-images.githubusercontent.com/50020726/61314769-08a7de00-a806-11e9-963e-441a804e3364.png)

block destroyed
![2019-07-16_20 02 51](https://user-images.githubusercontent.com/50020726/61314800-19585400-a806-11e9-8135-5a2c31a4874e.png)

world reloaded
![2019-07-16_20 03 15](https://user-images.githubusercontent.com/50020726/61314819-22e1bc00-a806-11e9-9fde-5c6f645ec6e3.png)

nothing №2
![2019-07-16_20 03 35](https://user-images.githubusercontent.com/50020726/61314840-2e34e780-a806-11e9-87b7-90584d9197f1.png)

ward casted(zap)
![2019-07-16_20 03 37](https://user-images.githubusercontent.com/50020726/61314865-3c830380-a806-11e9-8c00-02a734699e0d.png)

after cast warded block
![2019-07-16_20 03 41](https://user-images.githubusercontent.com/50020726/61314882-49075c00-a806-11e9-9db6-eef616db608b.png)

"stranger things"(world reload)
![2019-07-16_20 04 01](https://user-images.githubusercontent.com/50020726/61314912-59b7d200-a806-11e9-9cde-a945210a0253.png)
![2019-07-16_20 04 06](https://user-images.githubusercontent.com/50020726/61314921-5de3ef80-a806-11e9-885d-740872f3b3c4.png)
![2019-07-16_20 04 05](https://user-images.githubusercontent.com/50020726/61314922-5de3ef80-a806-11e9-9ac3-25cceabd9c3f.png)
![2019-07-16_20 04 03](https://user-images.githubusercontent.com/50020726/61314923-5de3ef80-a806-11e9-9134-b2d18b84d3d2.png)

**Comment by TechnoMysterio** [comment]
Hmm, this is very confusing, and I can't seem to replicate it. A few more questions:

- What happens when you cast the spell again, on the blocks that are already warded? It should remove the ward from the blocks. 
- What kind of spell layout are you using exactly? Is it a Touch -> Ward spell perhaps?
- What version of Thaumcraft and Thaumic Augmentation are you using? What about Forge?
- Is this in an old world or a new world?

**Comment by TheCodex6824** [comment]
I'm sorry that you're having these issues with the warding, but thank you for helping us out. Is there any chance I can see your full latest.log? I want to see if anything weird is going on. Thank you for mentioning the mod crashing without the coremod as well, that has been fixed.

**Comment by shoverno2** [comment]
Good questions, couse:
1)When casted again ward doesn't disappear
2)projectile, planning, touch, whatever(
3)everything is last versions, nothing outdated
4)like 2, whatever((

**Comment by shoverno2** [comment]
> I'm sorry that you're having these issues with the warding, but thank you for helping us out. Is there any chance I can see your full latest.log? I want to see if anything weird is going on. Thank you for mentioning the mod crashing without the coremod as well, that has been fixed.

you know, this addon to thaumcraft the best i ever seen, of course i will help)

**Comment by shoverno2** [comment]
Soo, any ideas?

**Comment by TheCodex6824** [comment]
> you know, this addon to thaumcraft the best i ever seen, of course i will help)

I'm glad you like the addon!

> Soo, any ideas?

I'd still like to see the log (if you're ok with sharing it), just to rule out any really weird happenings.

**Comment by shoverno2** [comment]
Well, how to find those logs, when minecraft doesn't crashing?(if you don't want to see crash without mod's core)

**Comment by TheCodex6824** [comment]
> Well, how to find those logs, when minecraft doesn't crashing?(if you don't want to see crash without mod's core)

In your logs folder in your minecraft directory, there should be a "latest.log" file, that's the log that I would like to see. It always appears, even when there isn't a crash.

**Comment by shoverno2** [comment]
[latest.log](https://github.com/TheCodex6824/ThaumicAugmentation/files/3398405/latest.log)
That?

**Comment by TheCodex6824** [comment]
That's the right file, but it looks like Thaumic Augmentation wasn't being loaded on that run. Put it back in your mods folder, do some of the stuff you did above that caused weird things, then go back to the logs folder and send me that log.
(Thank you for sticking with this by the way, it helps a lot)

**Comment by shoverno2** [comment]
alright, wait a minute...

**Comment by shoverno2** [comment]
[latest.log](https://github.com/TheCodex6824/ThaumicAugmentation/files/3398432/latest.log)

**Comment by shoverno2** [comment]
About ward only 2 research here:
1)[20:55:04] [Client thread/INFO] [THAUMCRAFT]: Loaded 1 research entries from thaumicaugmentation:research/ward_foci_coremod.json
2)[20:55:04] [Client thread/INFO] [THAUMCRAFT]: Loaded 3 research entries from thaumicaugmentation:research/warded.json

**Comment by TheCodex6824** [comment]
I've uploaded a temporary test build at https://file.io/pUOU2j (the jar is still signed by me), use that build and do what you have done before. That build will log anything that happens due to wards, so when you're done please send me your "debug.log" (same place as latest.log)

**Comment by shoverno2** [comment]
stuck at new world generation
[latest.log](https://github.com/TheCodex6824/ThaumicAugmentation/files/3398554/latest.log)
[debug.log](https://github.com/TheCodex6824/ThaumicAugmentation/files/3398555/debug.log)

**Comment by TheCodex6824** [comment]
I'm sorry, I was being stupid and forgot that the logs would probably lag worldgen to unreasonable levels. I fixed that and made another build at https://file.io/b0f8Nq can you give that a try?

**Comment by shoverno2** [comment]
i also loaded old world:
nice news: no ward after digging block
bad news: TOO LAGGY, when warded focus wearing or breaking blocks

**Comment by shoverno2** [comment]
and after leaving world minecraft crashing(first build)
[latest.log](https://github.com/TheCodex6824/ThaumicAugmentation/files/3398582/latest.log)
[debug.log](https://github.com/TheCodex6824/ThaumicAugmentation/files/3398583/debug.log)

**Comment by shoverno2** [comment]
[latest.log](https://github.com/TheCodex6824/ThaumicAugmentation/files/3398612/latest.log)
[debug.log](https://github.com/TheCodex6824/ThaumicAugmentation/files/3398613/debug.log)
One bag resolved, no weird warding №1(except no lags XD)

But still ward can't be deleted and...
that...
![2019-07-16_21 35 59](https://user-images.githubusercontent.com/50020726/61320379-f9c72880-a811-11e9-883b-1609f30c48cd.png)

**Comment by shoverno2** [comment]
Well, i just released, that after spell warding one block and reload world chank wardig, completely!

**Comment by shoverno2** [comment]
[21:35:24] [Client thread/INFO] [STDOUT]: [thecodex6824.thaumicaugmentation.api.warded.WardStorageClient:setWard:121]: [Client] setting ward at BlockPos{x=249, y=63, z=247}: OWNED_SELF
[21:35:24] [Client thread/INFO] [STDOUT]: [thecodex6824.thaumicaugmentation.api.warded.WardStorageClient:setWard:121]: [Client] setting ward at BlockPos{x=249, y=63, z=247}: OWNED_SELF

the only warding thread i have seeked

**Comment by shoverno2** [comment]
> I'm sorry, I was being stupid and forgot that the logs would probably lag worldgen to unreasonable levels. I fixed that and made another build at https://file.io/b0f8Nq can you give that a try?

this built can be uploaded for every one, who have problem with after block breaken warding, chunk warding not so annoying.
But if you resolve first two or more problems(chunk warding, unable to deward, no runic effect), that's will be much better.
I just saying that couse you maybe tired and doesn't feel you can fix everything rightnow.

**Comment by shoverno2** [comment]
As for me, 22:10, im going to bed

**Comment by TheCodex6824** [comment]
I'll probably take a little break and then get back to this, thank you for investigating this with me. So just to confirm so far:

- blocks are NOT warded after breaking them
- the wards are "spreading" to nearby blocks
- you cannot deward warded blocks
- rune effect does not display

Seems to me like there's a desync issue going on between the server data and client data (it is still separated in singleplayer)

**Comment by shoverno2** [comment]
thank you),
warding doesnt spread at nearby block, warding completely spread at chank
every other tips is right
zzz

**Comment by TheCodex6824** [comment]
So while I haven't reproduced the exact craziness that has been happening for you, it did allow me to find a whole bunch of bugs in the last version's warding, so *maybe* [this version](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/2752741) will work?

**Comment by shoverno2** [comment]
Well, i checked all. 
So...
1)Awasome animation! Finaly, non mouth spells))
2)Minor bag whith animation, it still apear after hiding gauntlet. (but can be ignored, it looks like whith gauntlet animation for little wile. Also, you can easy uderstand "why")
3)Warding still:
   1. Doesn't have rune/ripple animation
   2. Spread to local chunk FULLY
   3. Cant be removed.
4) New (and changed in this update) augmentations cant be applyed to gauntlets (tested whith mod gauntlet)
for now that's all
and im going to bed again  XD

**Comment by shoverno2** [comment]
I think it's time to stop evolving mod for wile. Every bag should be fixed. Bags may cry)))
Or this mod can die, like thaumic arcana...

**Comment by shoverno2** [comment]
Even forge 2768 showing those bags whith warding and new augmentaions(
And warding (after reload world) corrupt chunk OVER FULLY!
What the mechanic you using?


forge 2768(or upper, it's doesn't changing too much)
![2019-08-05_14 23 29](https://user-images.githubusercontent.com/50020726/62461515-c0893500-b78d-11e9-8504-e7108d44dfba.png)


from over 256 in height
![2019-08-05_14 27 21](https://user-images.githubusercontent.com/50020726/62461602-f4645a80-b78d-11e9-9c8b-bb6cdaa7c59f.png)


to deep deep down
![2019-08-05_14 28 05](https://user-images.githubusercontent.com/50020726/62461671-1d84eb00-b78e-11e9-8010-26270f015000.png)

I don't think that tere something interesting, but any way, latest logs
[latest.log](https://github.com/TheCodex6824/ThaumicAugmentation/files/3467378/latest.log)
and debug...
[debug.log](https://github.com/TheCodex6824/ThaumicAugmentation/files/3467381/debug.log)

**Comment by shoverno2** [comment]
[14:19:20] [Server thread/TRACE] [FML]:   Registry: 455 thaumicaugmentation:warded_chest Block{thaumicaugmentation:warded_chest}

[14:19:20] [Server thread/TRACE] [FML]:   Registry: 2265 minecraft:record_ward net.minecraft.item.ItemRecord@3d71e10b
(record ward XD)

[14:19:20] [Server thread/TRACE] [FML]:   Registry: 31 thaumcraft:warpward thaumcraft.common.lib.potions.PotionWarpWard@cd3d6c3

nothing interested in debug or logs((

**Comment by shoverno2** [comment]
I just thinking that somthing that prevent all block events and etc means prevent ANYTHING with that block. I mean, maybe warding system preventing unwarding system. Just mine guess-works...

**Comment by shoverno2** [comment]
In chunk warding problems has deal the ward coordinates loader, maybe. Glitch appear when loading world. Trying to load warded coordinates mod choosing chank instead block.
Another quess-works...

**Comment by shoverno2** [comment]
public abstract interface IUnwardableBlock
{
  public boolean shouldBeUnwardable(World world, BlockPos pos, IBlockState state, @Nullable Entity warder)
  {
    return true;
  }
}
@nullable Entity warder...
What is it?

**Comment by shoverno2** [comment]
ALSO!
Warding can't stand against destruction power of focus.

**Comment by TheCodex6824** [comment]
The code snippet you posted is just something applied to dedicated warded things like the Arcane Door and Warded Chest to ensure that they can't be "double warded" by the ward focus. As for your actual problem, I think I figured it out:

```Couldn't look up profile properties for com.mojang.authlib.GameProfile@4ea93835[id=00000000-0000-0000-0000-000000000000,name=Shoverno,properties={},legacy=false]```

That UUID happens to be the UUID I use internally to mark the absence of a ward. That UUID isn't even a valid version 4 UUID, so it should be impossible for a real Minecraft profile to have it. So you just need to change your UUID you use in whatever setup you have.
