### ISSUE TITLE
[Bug] Harness not producing sound

### ISSUE THREAD

**Issue by Vapaman** [TheCodex6824/ThaumicAugmentation#210]
This is a minor bug and a bit tricky to reproduce. To reproduce: Activate and deactivate the thaumostatic harness while wearing the cloudstepper ring. The harness will randomly stop producing sounds. Also this often occurs when the harness runs out of power or landing and then immediately jumping and flying again. If the cloudstepper ring is unequipped, sounds return to normal. ~~I couldn't reproduce this bug without the ring, so the ring is definitely messing with the sounds of the harness.~~

**Comment by Vapaman** [comment]
Now that I've experimented more it tends to happen when activating and deactivating while there are other sounds playing (I was in a nether fortress where there is constantly fire crackle from blazes). Also unequipping and re-equipping the harness fixes the sounds.

**Comment by Vapaman** [comment]
After playing a lot more I don't think it necessarily breaks when using the cloudstepper ring, it breaks quite randomly and inconsistently.

**Comment by TheCodex6824** [comment]
So is it only the flying loop that is not working, or does this also apply to the sound that plays when it is disabled? In any case, I have to check if there is some kind of sound limit or similar that can cause this.

**Comment by Vapaman** [comment]
After testing for some time, the sound works again after opening the baubles menu so I think your theory is correct.
