### ISSUE TITLE
[BUG] Saving Autocasters on death

### ISSUE THREAD

**Issue by Mestrophis** [TheCodex6824/ThaumicAugmentation#214]
I discovered this while testing the mod in a Creative world. Here's the issue:

During an Autocaster's death sequence, they can be dismantled, which saves the Autocaster. I feel like this should be known, as they drop various components on death and this could be abused to farm resources.

Streamable with footage of this in action: https://streamable.com/3pgkmn

**Comment by Vapaman** [comment]
This actually can be done with any TC6 golem/entity (automated crossbows, arcane bore).

**Comment by DoomRater** [comment]
If it's happening in Vanilla Thaumcraft, that sounds like a bug for the DupeFix Project.

**Comment by Vapaman** [comment]
Just reported it to them.
