### ISSUE TITLE
[Bug] Crash when trying to jar a rift

### ISSUE THREAD

**Issue by Vapaman** [TheCodex6824/ThaumicAugmentation#226]
Crash report: 
[crash-2021-08-07_19.54.52-client.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/6949441/crash-2021-08-07_19.54.52-client.txt)

Context: I was trying to jar rifts with the metaspatial accumulator, one of the rifts got stuck and wasn't shrinking, I unloaded the area and the game crashed when I tried to load it again.

**Comment by Vapaman** [comment]
Runtime log, if its any help: 
[latest.log](https://github.com/TheCodex6824/ThaumicAugmentation/files/6949448/latest.log)

**Comment by TheCodex6824** [comment]
Yeah I made a bit of a mistake in some of the loading code for the accumulator. I'm willing to bet that the rift is in a different chunk than the accumulator itself.

**Comment by TheCodex6824** [comment]
Also you mentioned the rift getting stuck - do you know a way to make that happen? I have not been able to make that happen in testing.

**Comment by Vapaman** [comment]
> 
> 
> Also you mentioned the rift getting stuck - do you know a way to make that happen? I have not been able to make that happen in testing.

I have struggled to get it to happen, it seems very inconsistent. I will try to replicate it in the meanwhile.

**Comment by Vapaman** [comment]
I might have to share the save world save if i can't replicate it,. Would that be of any use?

**Comment by TheCodex6824** [comment]
> I might have to share the save world save if i can't replicate it. Would that be of any use?

It could, although anyone with the world would be able to see absolutely everything in it, so if there is anything you don't want public in it you shouldn't share it (and don't feel like you have to either - saying no is fine).

**Comment by Vapaman** [comment]
Can confirm that it is not a compatibility issue. The issue is still present when loaded with just TA and its dependents.

**Comment by TheCodex6824** [comment]
I have to decline that invitation because I don't really want to normalize giving my IP to people by joining private repositories. You can help though by compiling the latest changes from master and seeing if you crash / if the rift is still stuck.

**Comment by Vapaman** [comment]
I can make the repository puplic, I don't have anything interesting there anyway. I can try compiling later when i have time.

**Comment by TheCodex6824** [comment]
> I can make the repository puplic, I don't have anything interesting there anyway. I can try compiling later when i have time.
> 
> Now the world can scoff at my messy ender chest all they like.

I got it so you can take it down now. I'll take a look at it tomorrow (it's late for me now).

**Comment by TheCodex6824** [comment]
Ok so it looks like the reason it is "stuck" is because the chunk ran out of vis. I have to double check if the book mentions that or not - if it doesn't, I'll be sure to add that in. That chunk has exactly 0 vis but also has 22k flux (!) so have fun with that.

**Comment by Vapaman** [comment]
Yea, i was wondering if vis affected the accumulator. Also the flux is intentional, nothing to worry about :D

**Comment by TheCodex6824** [comment]
I just pushed the update to make the machines more obviously show when they need vis, and I'll be updating the book tomorrow.
