### ISSUE TITLE
Hard dependency on forge version

### ISSUE THREAD

**Issue by SSKirillSS** [TheCodex6824/ThaumicAugmentation#23]
https://github.com/TheCodex6824/ThaumicAugmentation/blob/master/gradle.properties#L7

On this version of the forge, some mods work extremely poorly. Is it possible to install an older version as valid?

For example, on this version of the forge a lot of armor sets from the Advent of Ascension do not work at all.

**Comment by TheCodex6824** [comment]
You're not the first person to request this, I allowed the older forge versions (namely the recommended version) back in #15. I'll probably be releasing an update that includes this and more stuff soon™.

**Comment by TheCodex6824** [comment]
https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/2752741 Should work for you
