### ISSUE TITLE
[Bug] Z-fighting on the side of the obelisks

### ISSUE THREAD

**Issue by Vapaman** [TheCodex6824/ThaumicAugmentation#243]
When looking at a distance, there is noticable z-fighting between the edges and the middle void part of the obelisk.
![kuva](https://user-images.githubusercontent.com/77460466/131193137-39e175df-b202-4644-ae10-54ed0d015116.png)
This is more noticeable with the ancient variant.

**Comment by LordVertice** [comment]
Still getting the same issue.

**Comment by TheCodex6824** [comment]
I think this should be fixed now - I made it actually distance-aware in its rendering, so hopefully being really far away won't cause all that z-fighting anymore.

**Comment by Vapaman** [comment]
Works for me! Good work
