### ISSUE TITLE
Theorycrafting Lag

### ISSUE THREAD

**Issue by thedeerirty** [TheCodex6824/ThaumicAugmentation#245]
Hi! I recently updated to the current curseforge relase of the mod, and I'm noticing a lot of lag when using doing my theory crafting; was wondering if this could be linked to your mod, in anyway? Takes a bit to bring up cards, and often I need to re-enter it in order for it to let me draw more cards

**Comment by Vapaman** [comment]
Tested this with just augmentation and it's dependents. Couldn't reproduce the lag you are describing, so what other mods you have installed?

**Comment by thedeerirty** [comment]
A good deal; I'll have to test around myself. Very well could just be my server itself, I just hadn't experienced it until this world so I thought I'd check my addons and such. Thanks for checking, though.

**Comment by TheCodex6824** [comment]
This mod doesn't add much theorycrafting stuff, so it probably isn't the cause of your lag. I know that the theorycrafting code in general has some interesting design decisions that lead to inefficiencies, so it could be another addon doing something intensive in it or something like that.
