### ISSUE TITLE
Ore dict iron plate recipes

### ISSUE THREAD

**Issue by wizard1399** [TheCodex6824/ThaumicAugmentation#25]
Hello, 
I am working on a pack and noticed that you have not implemented the ore dictng of ironPlate as part of your arcane work bench recipes. In my pack, I am disabling the crafting recipes for the TC iron plate so that I can force players to use the iron plate from embers rekindled. It would be great if you included the ore dict in the recipes.

**Comment by TheCodex6824** [comment]
I went ahead and added the oredict to any recipes that didn't use it, including the iron plates. Let me know if I missed any.
