### ISSUE TITLE
[Bug] Autocasters and Celestial Observers will quickly replace blocks placed by your off-hand

### ISSUE THREAD

**Issue by Turkey9002** [TheCodex6824/ThaumicAugmentation#252]
This is a bug that affects Thaumcraft too (via Automated Crossbows, Golems, and Arcane Bores) but I'm putting this here because it also affects TA's Autocasters and Celestial Observers.

When you have a block in your off-hand slot and you place any of the above. It'll quickly place the block from your off-hand instead and then replace it with the entity, the block is gone forever and doesn't drop onto the ground.

**Comment by TheCodex6824** [comment]
I was able to reproduce the "replacing" behavior but the block wasn't actually gone forever - it was just "invisible" until the slot re-synced or I picked up the item. I'll fix it anyway because that can be confusing, but the block shouldn't actually be deleted.
