### ISSUE TITLE
Can you install mid playthrough?

### ISSUE THREAD

**Issue by iamawsome080** [TheCodex6824/ThaumicAugmentation#253]
Just the title. In the middle of a world. Already did a fair bit of thaumcraft stuff.

**Comment by DoomRater** [comment]
I've been answering this question on reddit a few times- I did exactly that and after generating some new terrain in the nether, I was able to find the necessary worldgen to progress in Thaumic Augmentation.  So it's definitely doable.

**Comment by iamawsome080** [comment]
thanks!
