### ISSUE TITLE
Impetus Drainer isn't working. Might be my stupidity, but I could be wrong.

### ISSUE THREAD

**Issue by GameRTerraria** [TheCodex6824/ThaumicAugmentation#254]
I am having a small issue with the Impetus Drainer, not sure if it's because of the fact that I haven't fully got to understand Impetus despite my research, or if I am simply doing this so morbidly wrong, that I am going to look like an idiot for posting this.

Does anyone know a solution to this?
![2021-10-06_12 13 49](https://user-images.githubusercontent.com/72883337/136242828-d2e8e190-9629-4be0-8070-0d5622af1a97.png)

**Comment by GameRTerraria** [comment]
I linked the Drainer to the Mirror, that should be Output > Input right? The Mirror is linked to another Mirror in a distance away since this acts as a flux rift farm in a way.

**Comment by SillyFrilly** [comment]
Hmm... Is the other mirror chunk-loaded (or close enough that that wouldn't be too much of a concern)?

**Comment by GameRTerraria** [comment]
Never mind, the entire area is tainted and I now have to enter the medium
