### ISSUE TITLE
[Bug]Impetus diffuser moved by dislocation core creates duplicated nodes causing crash

### ISSUE THREAD

**Issue by Fodoth-jinzi89** [TheCodex6824/ThaumicAugmentation#259]
I used a core with the function of dislocation from Thaumic Tinkerer to move an already connected impetus diffuser. The link broke normally and I reconnected the newly-placed one to the source. Everything seemed good, but when I teleport away the game crashed. I re-entered the save for some times and the game crashed with the same report:

[crash-2021-10-29_20.06.37-server.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/7442121/crash-2021-10-29_20.06.37-server.txt)

It seems that moving impetus nodes with a dislocation core won't invoke the node-removal process. The crashed save can't be re-entered unless the "throw IndexOutOfBoundsException" is deleted. (When deleted, re-enter the world, a triangle-connected impetus web will appear)
For my save I just need to delete the line. But you may have better solutions.

**Comment by TheCodex6824** [comment]
Well it's been long enough without someone reporting anything breaking, so I'd say this was safely fixed
