### ISSUE TITLE
Primal Cutter shouldn't be enchantable with Sweeping Edge 

### ISSUE THREAD

**Issue by Turkey9002** [TheCodex6824/ThaumicAugmentation#263]
It's currently possible to enchant the primal cutter with sweeping edge from the enchantment table or using enchanted books in the anvil. The problem is it would have no effect on the weapon because the weapon itself cannot do sweep attacks.

**Comment by DoomRater** [comment]
Shouldn't the bug be that the Primal Cutter doesn't do sweep attacks?  If it says it's a sword in the description, shouldn't it behave like a sword with the sweep attack?

If there's no way to fix that, then yeah, dropping the Sweeping Edge eligibility for the Primal Cutter makes sense.

**Comment by Turkey9002** [comment]
I actually thought it was intentional for it to not have sweep attacks, but now after you mention that I'm not entirely sure. XD I think it's much easier to just restrict it because the sweep attack itself is hard coded to the sword tool and the code for the cutter would have to extend it to be able to add that feature. I think doing that might affect it's multi-tool use though.

**Comment by TheCodex6824** [comment]
You are exactly right, it looks like Minecraft only enables sweep attacks for things that are swords, but technically the primal cutter is just a tool with high damage. If I'm feeling adventurous I can make a coremod patch to fix that, otherwise I might disable it.

**Comment by TheCodex6824** [comment]
I was able to add sweep attacks to the cutter, so in the next update sweeping edge will actually work as intended on it.

**Comment by Vapaman** [comment]
Should be reopened, the feature isn't working in the version downloadable on CF

**Comment by Turkey9002** [comment]
I can also confirm that the cutter from creative mode at least doesn't have the sweep working.

**Comment by TheCodex6824** [comment]
Sorry about that, I'll be reuploading that version shortly with this actually working

**Comment by Turkey9002** [comment]
Sweep attack and sweeping edge enchant both work with no issues! 👍
