### ISSUE TITLE
Snow spawns on top of spires with Snow! Real Magic! enabled

### ISSUE THREAD

**Issue by Turkey9002** [TheCodex6824/ThaumicAugmentation#266]
This was an interesting thing that happens when you have that mod installed (without any other mods other than dependencies), the very top of the spires will always generate with a layer of snow. Personally I don't mind it too much but I do still think it's a bug.

![snow](https://user-images.githubusercontent.com/86805568/147457164-a6c0ed22-2895-46c5-b3e7-273d5e6a47e0.png)

**Comment by TheCodex6824** [comment]
From a quick look, it seems like that mod only checks biome temperature when deciding to place snow, and doesn't care that the precipitation itself is not allowed in that chunk (in world provider) or biome. Unfortunately, I can't really do anything about this on my end, as it makes sense for the Emptiness to be cold.

**Comment by Hyxaru** [comment]
Of course your dimension, but I wonder, since this is a void dimension, and Azanor's entry for void metal mentions that it feels quite warm to the touch, perhaps the emtpiness might not be quite as cold?
Doesn't matter though, the thought just struck me.
