### ISSUE TITLE
Client Crash (origin uncertain)

### ISSUE THREAD

**Issue by Hyxaru** [TheCodex6824/ThaumicAugmentation#269]
[crash-2022-01-03_13.09.07-client.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/7801813/crash-2022-01-03_13.09.07-client.txt)

**Comment by TheCodex6824** [comment]
This one is probably my fault, I have to double-check if chunks unloading / loading is allowed during that rendering, although I get the feeling it is.
