### ISSUE TITLE
Textures and etc...

### ISSUE THREAD

**Issue by shoverno2** [TheCodex6824/ThaumicAugmentation#27]
I detected, that void_boots have old model texture. So... I released that i have pirate photoshop XD
And i made some new texture)))
not too many work still... Maybe in future boots will gain 3d model, like other void robe set stuff.
![boots_void_overlay](https://user-images.githubusercontent.com/50020726/62427875-79099700-b702-11e9-8ce7-8c433d46f4eb.png)
![2019-08-04_21 54 36](https://user-images.githubusercontent.com/50020726/62427879-8e7ec100-b702-11e9-9471-5c149889c6ff.png)

**Comment by TheCodex6824** [comment]
Your texture isn't bad, but TechnoMysterio recently made me [this new texture](https://raw.githubusercontent.com/TheCodex6824/ThaumicAugmentation/experimental/src/main/resources/assets/thaumicaugmentation/textures/models/armor/boots_void_overlay.png). Also, I personally can recommend the GNU Image Manipulation Program (GIMP), it's free and is quite powerful after getting the hang of it.
