### ISSUE TITLE
[Suggestion] Void Recharge Pedestal automation

### ISSUE THREAD

**Issue by Pyritie** [TheCodex6824/ThaumicAugmentation#274]
Hello, I would like to build a system where if my Impetus Cannon runs out of juice, I can send it back to my base and my setup can recharge it then send it back to me once it's finished. (I have things from other mods such as AE2 to handle the remote item retrieval)

To do this, I need a way to tell when the cannon has finished charging. Would it be possible to add a redstone comparator output for this? Like, either a straight on/off for "contains fully charged item", or the signal strength would scale to how charged it is, with 15 indicating full charge.

I think this could be a fun little contraption to build instead of carrying around a few rifts in jars!

Thank you!

**Comment by Hyxaru** [comment]
Assuming you have more impetus stored at your base than your empty cannon demands, technically it will always take a fixed time to recharge and a simple timer could be constructed to remove the item from the pedestal after a certain while.

**Comment by TheCodex6824** [comment]
An analog comparator output on the recharge pedestal corresponding to the charge of the item sounds reasonable to me.

**Comment by Pyritie** [comment]
Thank you!!
