### ISSUE TITLE
Impetus Links Not Working Correctly

### ISSUE THREAD

**Issue by Cicopath** [TheCodex6824/ThaumicAugmentation#275]
Every once in a while, the links between the Impetus Drainer, Relay, and Matrix will just... break. After a while, the links disappear, and when I try to re-link everything, the charged Impetus does not transfer. In fact, with Impetus already in the Matrix, the Impetus will not transfer even when linked to the Diffuser or the Void Recharge Pedestal,

This seems to occur when I am not around the links to keep them loaded all the time; I have not seen it occur while I have been around the links when they work properly. I tried to solve this by using an Extra Utilities 2 Chunk Loader to keep a 3x3 chunk area loaded, but to no success.

![2022-02-20_05 49 04](https://user-images.githubusercontent.com/61031176/154839028-70cc79dc-efae-484a-a986-ae94a6af088a.png)

**Comment by Cicopath** [comment]
To add to this, when I unlink the broken link, destroy the Drainer, and re-place the Drainer and re-link it to the Relay, the non-charged Impetus beam will not be shown.

**Comment by TheCodex6824** [comment]
Does anything pop up in your logs when you do any of the replacing / entering the area with the broken connections? Things still being broken even when replacing everything is not something that has been encountered before.

**Comment by Cicopath** [comment]
So, it's weird. Let me try to elaborate and re-create my steps:

When I place down the Drainer, Relay, and Matrix, and then link them all together, the Drainer properly drains and transfers the charged Impetus all the way to the Matrix.

However, when I have left the area and returned, especially through dimensions, only sometimes will the charged Impetus not be drained from the flux rift. Even when the Drainer is on, it will only show uncharged Impetus, as shown in the picture above.

Now, I will break and re-place my Drainer to see if that works. After replacing it, I try to link it to the Relay. While the Resonator shows it's linked with the highlighted boxes, the uncharged Impetus does not show. It is only when I replace _all_ blocks will it then work.

Recently, I have discovered some inconsistencies. After leaving the area, sometimes the links will disappear entirely. Like, neither the uncharged Impetus nor the highlighted links from the Resonator will be shown; I have to re-link everything. Weirdly enough, the charged Impetus will continue to properly drain.

I am unsure as to what exactly is happening, but I will continue to monitor when and how this occurs.

**Comment by Cicopath** [comment]
When you talk about logs, do you mean things like crash logs?

**Comment by TheCodex6824** [comment]
The resonator only "knows" what the client knows, so if something did not sync properly, then the resonator will be wrong. Given that Impetus is also not transferring, I think the saving/loading of links is messing up somehow.

> When you talk about logs, do you mean things like crash logs?

In your minecraft game directory, there should be a "logs" folder, with "latest.log" being the latest game log as the name suggests. If any error-looking things appear when doing Impetus stuff, that would be good to know. I'd also like your mod list, because I think there is some interaction going on (given that I am not flooded with issues about Impetus being broken for everyone).

**Comment by DoomRater** [comment]
I have had Impetus issues, but I am trying to wait until I come across them in normal play- and in only one instance do I have all the progression out of the way to even spend time on Impetus link research.  So it's possible that I might be able to replicate if I were to go into creative on my own packs.  I'll have to see.  Been working a lot of hours lately.

**Comment by Cicopath** [comment]
Once it occurs again, I will make sure to provide the latest log as soon as possible.

In the meantime, I have attached a .txt of all the mods in the modpack, derived from a .html in the modpack's zip file. Unfortunately, since it is such a large modpack, the mod causing this problem -- if there is one -- could be nearly impossible to find.

[aa.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/8120291/aa.txt)

**Comment by Cicopath** [comment]
This is my latest log. My rift randomly disappeared, so I had to get a new one. However, I know it was not working because the Matrix would not send stored Impetus to the Void Pedestal to charge my Impulse Cannon. I tried playing with the links and even breaking and replacing the pedestal, so hopefully the log has something.

[latest.log](https://github.com/TheCodex6824/ThaumicAugmentation/files/8121465/latest.log)

**Comment by TheCodex6824** [comment]
Sorry for the radio silence - the latest version (2.1.5) introduced a fix that changed how impetus nodes were unloaded to prevent a compatibility issue. If you try reverting to 2.1.4, that might stop the issue (and if it does, let me know so I can revert that and find a different solution)

**Comment by Timelife** [comment]
I wanted to bump this, playing on a server where the impetus links keep breaking or need to replace all the components, including the matrix, to make the impetus flow.

**Comment by TheCodex6824** [comment]
> I wanted to bump this, playing on a server where the impetus links keep breaking or need to replace all the components, including the matrix, to make the impetus flow.

Unfortunately I have not been able to replicate this at all - if you post your mod list, I might be able to see what you have in common and narrow down any potential compatibility issue more. My current theory is that some other mod is calling a thing that they really shouldn't, which tricks the impetus blocks into thinking they are being destroyed.

**Comment by Timelife** [comment]
https://www.curseforge.com/minecraft/modpacks/magiculture?gameCategorySlug=modpacks&projectID=241729

Here is a link to the modpack, mod list should be there.

I might also be a server thing? Perhaps some server plugins are interacting with the impetus blocks improperly?

**Comment by Timelife** [comment]
I should note that I have an automated setup that turns off the drainer when the rift gets too small or unstable. I found that when the block that the drainer is sitting on is redstone powered the drainer does not update until perhaps 20 seconds later. This requires me to redstone power the drainer itself (sticky repeater directly pointed at it). Also the drainer is the one component that is more likely to have the link break, I have had it happen many more times then the entire system unlinking. This leads me to believe it is some sort of block update issue.

**Comment by Srdjan-V** [comment]
I can also confirm that this happens. In my case it happens on world load and while crossing chunks. The bocks also need to broken and replaced to work.

After simply reconnecting they dont work. 
![After relinking](https://user-images.githubusercontent.com/78452357/180305074-095c6bdc-679e-4550-b420-a3566839615a.png)

On world load, they will disconnect, even if broken and replaced.
![On world load](https://user-images.githubusercontent.com/78452357/180305085-520add4e-4fd6-493d-85a5-14b84b461eca.png)
![Chunks](https://user-images.githubusercontent.com/78452357/180305092-4ec8b97b-a912-443a-a745-bf9d38e7a2c1.png)

This can be replicated consistently in this [modpack](https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended), as shown in the pictures blow. I found that you need a lot of connections crossing chunks for this to trigger.

Without the crossing of chunks this bug did not happen.
![Before world unload](https://user-images.githubusercontent.com/78452357/180305491-545eb059-399f-4a8e-b596-61286561c982.png)
![On world load](https://user-images.githubusercontent.com/78452357/180305497-fd7389a8-ef14-43e7-b6b4-21c497be5520.png)

Thaumic Augmentation version `2.1.7`
