### ISSUE TITLE
WIP or bug?

### ISSUE THREAD

**Issue by shoverno2** [TheCodex6824/ThaumicAugmentation#28]
I already fixed mine uuid (thanks for help). But still can't attach any new augment. Is this WIP or bug? Sorry, if i ask stupid questions.

**Comment by TheCodex6824** [comment]
Did you actually craft the augment? The new ones are modular, so you need to craft a modifier and an effect crystal together in a crafting grid to get a usable augment.

**Comment by shoverno2** [comment]
oh... OH!...
Ok, now i understand)) thanks))))

**Comment by shoverno2** [comment]
Also, Does you planing to add some infusion "rites" that adds augment slots. I just seek "slots" value.

**Comment by TheCodex6824** [comment]
> Ok, now i understand)) thanks))))

No problem :)

> Also, Does you planing to add some infusion "rites" that adds augment slots. I just seek "slots" value.

More augment slots aren't planned at the moment, as having too many will become unbalanced very quickly. Having a limited number also provides an incentive for players to have to think about the augments that would be best for them.
