### ISSUE TITLE
Game freezes upon granting full research.

### ISSUE THREAD

**Issue by rougedarkdragon** [TheCodex6824/ThaumicAugmentation#281]
I've discovered that granting the player full research can be quite dangerous. I'm not sure if this mod is the problem, but I've never had this happen without Thaumic Augmentation.

After granting myself full research with commands, began reading the research out of curiosity. But not five seconds after opening one of the discoveries, the game froze. And it never unfroze. It was eternally cursed to a life of endless stagnation until I closed Minecraft. This is annoying, but also potentially problematic. I'm not sure if this problem will emerge after gaining research without commands, which would in turn prevent anyone who progresses far enough into Thaumcraft to even open the Thauminomicon out of fear of their game eternally freezing. But then again, it could just be that my computer is unable to handle the amount of research for some reason.

What is happening?

**Comment by TheCodex6824** [comment]
Can I see your game log? I've never heard of this happening before - I'm wondering if some other addon is doing something weird.

**Comment by rougedarkdragon** [comment]
There's no crash log (I think) because I'm forced to just close the game.

**Comment by TheCodex6824** [comment]
> Where do I find the game log?

It should be called "latest.log" in the logs folder in the minecraft folder (.minecraft). Repeat the same steps you did to get the freeze, and then the latest.log should be ready to go.

**Comment by rougedarkdragon** [comment]
Sorry for the slow response.
I tried recreating the problem to produce a log, but for some reason I couldn't. The issue seems to have gone away for now. I'll see if I can get it to happen again.

**Comment by TheCodex6824** [comment]
If it does happen again, we can look into it again later.
