### ISSUE TITLE
[Bug] Incorrectly overwrites RandomTweak's compareTo command

### ISSUE THREAD

**Issue by Turkey9002** [TheCodex6824/ThaumicAugmentation#285]
![bug](https://user-images.githubusercontent.com/86805568/167334336-49e83a40-5125-467c-b2aa-fc07e08608a6.png)
This was something that popped up in the logs a lot whenever I have this installed with RandomTweaks. I assume the two commands end up conflicting with each other in the process. x.x

"The command thaumicaugmentation (thecodex6824.thaumicaugmentation.server.command.CommandTAGeneral) incorrectly overrides compareTo!" Is what it says in case the image is too small.

**Comment by TheCodex6824** [comment]
I guess RandomTweaks is trying to sort commands or something, and I don't override that comparison function. I didn't even know I was supposed to, but it makes sense. I'm not actually overriding anything in Random Tweaks itself, though.
