### ISSUE TITLE
Task 'filterTokens' does not replace placeholders

### ISSUE THREAD

**Issue by TheNullablePrototype** [TheCodex6824/ThaumicAugmentation#294]
git clone https://github.com/TheCodex6824/ThaumicAugmentation
"cd folder"
.\gradlew build

compiled classes with placeholders:
![image](https://user-images.githubusercontent.com/19995957/172128310-a025d5b8-b678-4a67-8fe0-1ec193219348.png)
![image](https://user-images.githubusercontent.com/19995957/172128340-55ed8a7f-428d-4db0-888a-d2a5bccb2f2d.png)

_Just for the record, with mcmod.info It's okay._
![image](https://user-images.githubusercontent.com/19995957/172128411-29a2c299-2cc7-43aa-8973-4c0f4541df98.png)

The same error is observed at least in the [latest version](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/3811131) on curseforge!

I think this is a mistake and I ask you to fix it

**Comment by TheCodex6824** [comment]
Thanks for catching this, I feel really stupid for not noticing that myself but at least it's fixed now
