### ISSUE TITLE
[Suggestion] Configuration enhancement: disable individual crafting/research 

### ISSUE THREAD

**Issue by LincT** [TheCodex6824/ThaumicAugmentation#303]
basically asking for a little more configuration such as being able to disable recipes so players cannot craft the items while still allowing them to progress to other research. 
Possibly even making it so disabled research doesn't show, but allows for progression to other tiers, 
One such example would be allowing one to skip the warded chest, but make arcane mechanisms.

This is a great mod and feels like it completes TC6, however on servers with multiple mods, game balance might become an issue which is why I'm proposing this feature.

**Comment by Vapaman** [comment]
This can be done with Thaumcraft research patcher and crafttweaker/modtweaker

https://www.curseforge.com/minecraft/mc-mods/thaumcraft-research-patcher

**Comment by TheCodex6824** [comment]
I would suggest Thaumcraft Research Patcher for this, as it sounds like it does exactly what you want. If you decide to use it, a quick example to remove a recipe in an entry might look like (untested, but it should be at least close):
```
[	
	{
		"key": "WARDED_ARCANA",
		"ops": [
			{
				"op": "remove",
				"path": "stages/0/recipes/1"
			}
		]
	}
]
```
Disclaimer: I am also the author of TC Research Patcher
