### ISSUE TITLE
[BUG]Using Tinkers' Construct 2 kama to right click dirt will make the game not responding and crash

### ISSUE THREAD

**Issue by mczph** [TheCodex6824/ThaumicAugmentation#306]
crash-report
https://pastebin.ubuntu.com/p/ynfR4bzk5z/

**Comment by mczph** [comment]
It the problem of ThaumicAugmentation AgriCraft Compact

**Comment by TheCodex6824** [comment]
I do see Augmentation is installed in your log, but the block that it is crashing trying to find is from Thaumic *Additions*, not Augmentation. Is this mod doing something to cause that behavior?

**Comment by mczph** [comment]
I accidentally made a mistake, this should be submitted to another mod, sorry
