### ISSUE TITLE
Issue with Gauntlet Augmentation using Default Configs on server

### ISSUE THREAD

**Issue by Pyrox115** [TheCodex6824/ThaumicAugmentation#31]
When attempting to either craft an augment like the Experience + Vis Discount making a Modular Caster Augment instead of showing the tool tip being Modifier: Experience, Effect: Vis Discount It shows up as Modifier: Elemental, Aspect: Ordo, Effect Focus Power.

Same issue with both the Thaumium Caster's Gauntlet and Voidseer Caster's Gauntlet, It will no longer show the Augment tool tip or what augments have been included in said gauntlets.
![Singleplayer1](https://user-images.githubusercontent.com/54084782/62982223-649f5b80-bde0-11e9-9132-1a082b548a76.png)
This is how I understand it to appear in single player

This one is on a server with default configs
![Multiplayer1](https://user-images.githubusercontent.com/54084782/62982384-ce1f6a00-bde0-11e9-8bcd-dc0222f1ab3f.png)
The top one is the Experience + Vis Discount modifier the bottom one is a normal elemental Ordo Focus power

Here is with both of them in the gauntlet
![Multiplayer2](https://user-images.githubusercontent.com/54084782/62982487-1fc7f480-bde1-11e9-92c3-9c1f3e924440.png)

As far as my server admins have said no error logs or the likes have shown up for me to inspect to narrow this issue down, I assume it could just be a graphical glitch or something.

**Comment by Pyrox115** [comment]
Here are some of the Errors I have obtained from the log that could be possibly relating to the issue
[error.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/3499214/error.txt)

**Comment by TheCodex6824** [comment]
This might seem like an unrelated question, but were you in creative mode when doing all of this? If so, can you try the following?

1. In creative, take some augment modifiers and effects out. Do not craft them together yet.
2. Switch to survival
3. Obtain a gauntlet **without** using the creative menu (so `/give <username> thaumicaugmentation:gauntlet 1 1` or craft it using the infusion)
4. Try to craft some modular augments
5. If that worked, try to attach them to the gauntlet
6. See if the gauntlet is working correctly
7. Switch to creative mode, open the creative inventory, and see that the gauntlet had its augments wiped

If all of the above is true, then I know what's going on.

**Comment by Pyrox115** [comment]
For the single player stuff I was in creative while the multiplayer stuff i was in survival, I will try this in survival as you have suggested and see if the issue happens and get back to you with it.

**Comment by TheCodex6824** [comment]
I did some testing myself and was able to find some workarounds for this happening. It looks like [this](https://github.com/MinecraftForge/MinecraftForge/issues/4580) was the reason why this was happening. And just to clarify, this happened from going into creative at all with the items - they didn't have to be spawned from creative for it to happen.
