### ISSUE TITLE
Research string names

### ISSUE THREAD

**Issue by NaveItzMe** [TheCodex6824/ThaumicAugmentation#314]
Mhm. Hello there. I enter to this place with one question that i really needed to know. Where i can found research string names for this Thaumcraft addon? I'm creating a modpack right now, and i need it to change some crafts. I will be really appreciate if someone help me with that problem.

I'm saying for this ones, as an example. This ones from the classic Thaumcraft 6:  https://pastebin.com/SJa31qtS

**Comment by TheCodex6824** [comment]
Sorry for taking a while to respond. You can find the raw research JSON in the [research asset folder](https://github.com/TheCodex6824/ThaumicAugmentation/tree/master/src/main/resources/assets/thaumicaugmentation/research). Each entry in the JSON will have a `key` - that is the name you are looking for.

If you're not using it already, I would also suggest using Thaumcraft Research Patcher for modifying the research entries (disclaimer: I am also the author of that mod, but people seem to find it very helpful).
