### ISSUE TITLE
Server crash on attemt to leave the Emptiness

### ISSUE THREAD

**Issue by katzenpapst** [TheCodex6824/ThaumicAugmentation#32]
Entered the Emptiness from the Nether successfully, but when I tried to leave it, everything crashed and burned:
https://pastebin.com/JyLeYte4

I can start the server back up, but this still happens whenever I try to join:
https://pastebin.com/uzf1Vb0A

Seems like it's still happening in the onCollide...

Potentially related: just after I went through, the fracture didn't react at me walking into it. I thought that maybe it has a timer, and went for a walk in the Emptiness for a while. When I returned, I rightclicked it with my thaumium casting gauntlet, which had a projectile-light focus equipped. It has no other augmentations than the impetus one.

**Comment by katzenpapst** [comment]
Addendum: I tried renaming the DIM14676 directory as a workaround. This allowed me to rejoin. The fracture through which I came was closed. I opened it again, but it was unusable. Not sure if due to the previous bug, or because it doesn't connect to the fracture in the Nether anymore.
According to the logs, it at least tries to load the nether:
```
[16:06:55] [Server thread/INFO] [FML]: Loading dimension -1 (Biome Bundle) (net.minecraft.server.dedicated.DedicatedServer@b6e720c)
[16:06:55] [Server thread/INFO] [THAUMCRAFT]: Creating aura cache for world -1
[16:06:55] [Server thread/INFO] [Dynmap]: [Dynmap] Loaded 124 pending tile renders for world 'DIM-1'
[16:06:55] [Thread-58/INFO] [THAUMCRAFT]: Starting aura thread for dim -1
[16:06:55] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world -1
[16:06:55] [Server thread/INFO] [FML]: Unloading dimension -1
[16:06:55] [Server thread/INFO] [Dynmap]: [Dynmap] Saved 156 pending tile renders in world 'DIM-1'
[16:06:57] [Thread-58/INFO] [THAUMCRAFT]: Stopping aura thread for dim -1
```

Found a fracture which leads to the Overworld in there, that opened without trouble and is bidirectional. Used that to get out at least...

**Comment by TheCodex6824** [comment]
The line that's crashing is _after_ when the player should have been teleported, but something is stopping that from happening. Making it not crash would be easy enough, but I don't know what mod is causing that to happen, as it works with just this and Thaumcraft. I'll look over your mod list and see if I can figure out what's going on.

**Comment by katzenpapst** [comment]
That would be consistent with me being unable to exit right after I entered...
Natura maybe? It does do stuff to the Nether, at least. 
I guess I can see if I can reproduce this in singleplayer

**Comment by TheCodex6824** [comment]
> And I'm almost certain it's caused by Open Terrain Generator and/or Biome Bundle. Disabled them, and it works.

I just tried OpenTerrainGenerator and while it doesn't crash, I can't go to the nether with it installed just as you observed. Thanks for figuring it out for me! I'll probably get in touch with the devs of OTG to find out what's going on - in my testing only nether portals worked, even forge's `setdimension` command didn't work.

**Comment by TheCodex6824** [comment]
My apologies for not coming back to this sooner - this was indeed an issue on OTG's end, and they fixed it in a dev build. However, I am unsure when it will end up in an official OTG release. If you're ok with running a potentially unstable build, they should have the latest dev build on their discord server.
