### ISSUE TITLE
Crash with botania

### ISSUE THREAD

**Issue by Luicuelo** [TheCodex6824/ThaumicAugmentation#321]
ThaumicAugmentation-1.12.2-2.1.8. Crash

Caused by: java.lang.ClassNotFoundException: thecodex6824.thaumicaugmentation.common.item.ItemThaumostaticHarness
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)

Caused by: java.lang.NoClassDefFoundError: vazkii/botania/api/item/IPhantomInkable
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)

**Comment by DoomRater** [comment]
What's your Botania version?  I get no crash running Augmentation with any of the last builds or even my custom builds of Botania.

**Comment by Luicuelo** [comment]
Botania r1.10-364.4

It has to be due to a change in version 2.1.8 of  ThaumicAugmentation because in the previous version it doesn't fail.
Something related to ThaumostaticHarness and IPhantomInkable interface of botania.

**Comment by DoomRater** [comment]
So that suggests something broke with Botania dependency linking on the last compile.  Fun

**Comment by TheCodex6824** [comment]
Your Botania appears to be missing API classes that should be there. [Someone else](https://github.com/TheCodex6824/ThaumicAugmentation/issues/315) apparently had the same problem, and updated Botania to make it go away. Is there some weird build of Botania floating around somewhere? The Curseforge version still seems fine.

**Comment by DoomRater** [comment]
Oh god I just realized my Mad Science modpack doesn't have Botania in it.  I need to check an actual test build really quick to see if my custom Botania build has an issue. My custom build is labelled at 366.  I seem to be able to launch a pack with that and Augmentation 2.1.8 though.

Anyway the fact the downgrading Augmentation didn't fail is super weird, the code that implements Phantom Ink is years old now.  Did the Botania JAR become corrupt somehow?

**Comment by Luicuelo** [comment]
I have downloaded the latest version of curseforge and it has been fixed. I'm pretty sure that the file I had before was also from curseforge, at some point they fixed a bug and they didn't put a different version number on it.

**Comment by TheCodex6824** [comment]
> I have downloaded the latest version of curseforge and it has been fixed. I'm pretty sure that the file I had before was also from curseforge, at some point they fixed a bug and they didn't put a different version number on it.

That makes sense. I think even the latest version of TC6 had something like that happen - I remember helping someone with some weird infusion crash, and it turned out there was a reupload to fix it.

Thanks for figuring that out though - now I have a solid solution I can give others that have the same problem.
