### ISSUE TITLE
Cant wear ThaumiumRobes on server 

### ISSUE THREAD

**Issue by GiIIox** [TheCodex6824/ThaumicAugmentation#323]
![image](https://user-images.githubusercontent.com/118012116/201398387-463d61d6-c69a-41c8-856f-4401139ace7d.png)
I've crafted a Thaumic hood with glasses, but as soon as I pick them up or put them on my head, the server kicks me and won't let me back in until I take it off or take it out of my hand. I have to kill myself constantly through the console. Please, help me and say what i need to do for fix this bug...

P.S.:
However, in a single game everything works fine.

**Comment by TheCodex6824** [comment]
Sorry about that, I just pushed an update to fix it. Once it gets approved, it will be available [here](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/4081306).

**Comment by GiIIox** [comment]
Thanks a lot
