### ISSUE TITLE
Autocaster recognize spellbat as mobs

### ISSUE THREAD

**Issue by forgottencsc** [TheCodex6824/ThaumicAugmentation#324]
An autocastor equipped with a spellbat-mediated core will repeatedly cast when encountering mobs.
I suggest adding an additional checkbox to the autocastor interface to determine whether the autocastor should target spellbats.

**Comment by TheCodex6824** [comment]
Would you rather have a checkbox for targeting spellbats, or have them just always ignore friendly spellbats?

**Comment by forgottencsc** [comment]
The latter makes more sense to me.

**Comment by forgottencsc** [comment]
> Would you rather have a checkbox for targeting spellbats, or have them just always ignore friendly spellbats?

The latter makes more sense to me.
