### ISSUE TITLE
Impetus mirror doesn't delete previous outputs & breaking flowing relays crashed game.

### ISSUE THREAD

**Issue by ModMachine626** [TheCodex6824/ThaumicAugmentation#329]
When I use the Impetus Mirrors, most times it doesn't remove the link to the second one when I break it. When I link the mirrors together again, there are more outputs than allowed and the game throws an IndexOutOfBoundsException. Breaking the original mirror temporarily fixes it as it deletes all other mirror references. Crash log and image below.

[crash-2023-01-30_23.43.13-client.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/10542887/crash-2023-01-30_23.43.13-client.txt)

![bug](https://user-images.githubusercontent.com/80303176/215669066-60c312cf-d10b-4471-bd33-19cd70f5493c.png)

After upgrading to 2.1.9 (previously 2.1.5), mirrors seem to not work at all, and breaking an active chain of relays caused a crash. Log below.

https://pastebin.com/edREyjFD

**Comment by TheCodex6824** [comment]
A few things to try:

- Try using version 2.1.8 - 2.1.9 had some invasive changes to the tile entities to try to fix some chunkloading issues. There's a chance I missed something when testing those changes.
- Try removing Optifine - I know this isn't really a permanent solution for a lot of people, but if that is causing it to happen it at least narrows it down a little for me so I can try to fix it.
- After breaking a mirror, try exiting and re-entering the world - does it still have issues after doing that?

**Comment by ModMachine626** [comment]
on 2.1.8, removed optifine and made new world. everything went smoothly at first, the node crash was gone and the mirror bug seemed fixed. But after reloading, impetus refused to flow through mirrors, and it seemed like they had trouble linking. after reloading again, the too many outputs bug happened.
[crash-2023-02-05_22.33.52-client.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/10649782/crash-2023-02-05_22.33.52-client.txt)
I tried linking a creative source directly to a matrix and it worked.
the mirrors either link together properly and throw that crash or they don't link properly and properly delete their output links.

Improperly linked
![help](https://user-images.githubusercontent.com/80303176/216879753-f576c3f1-0aa6-47a1-8a22-67d784c567f1.png)

Multiple improperly linked outputs don't throw a crash
![bro](https://user-images.githubusercontent.com/80303176/216879885-8a6c2b7b-8d93-4e09-8bc0-fe309b9c283c.png)

Breaking middle mirror successfully removes link
![pls](https://user-images.githubusercontent.com/80303176/216879933-d32c125f-152b-4cb2-8177-5e30f02bb15a.png)

**Comment by TheCodex6824** [comment]
Before I make a release with all of the bugfixes, do you mind trying the latest fixes and confirming they solve your problem? Rename the file from .zip to .jar.
[ThaumicAugmentation-1.12.2-2.1.9.zip](https://github.com/TheCodex6824/ThaumicAugmentation/files/11009626/ThaumicAugmentation-1.12.2-2.1.9.zip)

If you want to compile your own jar instead, pull the latest changes to the master branch and build that. The build instructions should be (hopefully) fully up to date and working.

**Comment by TheCodex6824** [comment]
You're welcome to report back if it fixed the issue for you, but I went ahead and made the update because I tested things and think I fixed it. If it still happens with 2.1.10, let me know.

**Comment by ModMachine626** [comment]
I found no issues from either build, looking forward to enjoying this.
