### ISSUE TITLE
Impetus Beam [Feature Suggestion] 

### ISSUE THREAD

**Issue by xRoBoTx** [TheCodex6824/ThaumicAugmentation#33]
I suggest you to add Impetus Beam focus which can fire powerful beam and inflict wither or something like that on contact. I think that would be really great :)

**Comment by xRoBoTx** [comment]
Also i think that adding a focus that can suck rift power faster would be nice.

**Comment by TheCodex6824** [comment]
I was thinking about adding an entire beam focus medium before, but I pushed that off as it would require horribly abusing Thaumcraft's casting system. I'm probably going to have to do that anyway for some planned features so I might as well add the beam too. As for the rift power thing, the entire impetus system is being greatly expanded for the next update, with faster ways of drawing power being one part of it.

**Comment by shoverno2** [comment]
If it sounds in auromancy language:
You>beam>eldrich
...
Beam - attaching shape(Maybe with options, example:homing, penetration, ricochet)
Eldrich - effect of eldriches.

**Comment by TheCodex6824** [comment]
The new Impulse Cannon in 2.0 has a beam mode that pretty much turned out to be the final version of this.
