### ISSUE TITLE
Clients kicked on server when a player has an impulse cannon

### ISSUE THREAD

**Issue by Pyro93735** [TheCodex6824/ThaumicAugmentation#330]
I've been seeing players disconnected from the server after a player crafted an impulse cannon. The following is printed to the server console when the player is disconnected: https://pastebin.com/9mFZewTg

Other players only seem to be getting disconnected if the player with the impulse cannon is online and in the same dimension as them.

**Comment by TheCodex6824** [comment]
This sounds like the same thing as #290 - update to the latest version and this should be fixed.

**Comment by TheCodex6824** [comment]
I'm assuming this is just an older version issue, if it happens on the latest version let me know.
