### ISSUE TITLE
Eldritch Spires

### ISSUE THREAD

**Issue by AutumnLor** [TheCodex6824/ThaumicAugmentation#332]
After killing the boss, the block cannot be collected. This phenomenon occurs on the server, but not on the single machine

**Comment by TheCodex6824** [comment]
By that, I'm assuming you mean that the warding on the structure is not going away? Does this happen consistently every time on dedicated servers?

In the meantime, you can use `/ta ward clear` while standing in the chunks of the spire to remove the warding manually.

**Comment by AutumnLor** [comment]
Yes, I have tried in the server. Basically, all Eldritch Spires cannot break the protection of the structure after killing the boss, but the method you provide can still work.

**Comment by TheCodex6824** [comment]
I made some changes in the latest version that should have fixed this - if they didn't, let me know and I'll look again.

**Comment by PootisManTF2** [comment]
Hello,

I would like to say that this issue doesn't seem to be patched, because I've defeated the boss of several spires and yet the warding is still active everywhere :/
