### ISSUE TITLE
[Server Crash Bug]

### ISSUE THREAD

**Issue by Satvn** [TheCodex6824/ThaumicAugmentation#333]
An interaction i think between the eldritch guardian and their void shield (or a spell casted void shield) causes an incredible amount of spells stacked up and blasted out which will instantly cause a server to permanently stall and will also crash the client near the enemy that did it

Ive spent a few hours attempting to do this bug and managed to replicate it with quite constant success. However the main problem is this can generally occur to any random player purely by accident, happening 5 times in a week on the server i play, with only 3 players causing it seperately.

the two main enemies of concern are the Eldritch Gaoler (Predominatly) and any Eldritch warden boss

Ive found that when fighting these enemies, if you attack their void shield (instigating its runic shielding effect) at the very moment it attacks you with its ranged blast attack, it will shoot hundreds, if not thousands of ranged attacks in one go shattering its own shield and sending the player into 0 fps and eventually a crash from a failure to spawn an entity. the server however goes into an infinite stall.

The bug can be on a small scale replicated with the void shield spell and casting it on any eldritch guardian.

Attatched is two videos of this, one with a player spell and one on an eldritch warden boss.
https://www.youtube.com/watch?v=4cRVaeq2eIU
https://www.youtube.com/watch?v=5Lhfd-Y1DSQ

if this is a serverside issue we would really appreciate help on how to resolve it, and if you need any more info im sure i can supply it, the pack we play on is the 1.12.2 pack

**Comment by Vapaman** [comment]
can confirm that this is happening, once had this occuring in a creative test world while testing the eldritch warden boss

**Comment by xJon** [comment]
The 1.12.2 Pack is currently not running the latest Thaumic Augmentation version (although a modpack update should be released in the next 1-2 weeks). You can try to manually update the mod and see whether that resolves the issue?

**Comment by Satvn** [comment]
Tested on a server running the latest version 2.1.9 of Thaumic Augmentation and the issue is still present

**Comment by TheCodex6824** [comment]
I've had this happen once to me while in the middle of changing things, so I thought I just broke something temporarily, but apparently not. I'll look at this and the other bugs and try to get a bugfix update out - I have had a fulltime job for a little while now so I don't have as much time/energy for this as I used to :(

**Comment by TheCodex6824** [comment]
I think I fixed this, but can someone either try this version or compile the latest master and try seeing if it still happens?
[ThaumicAugmentation-1.12.2-2.1.10.zip](https://github.com/TheCodex6824/ThaumicAugmentation/files/11011952/ThaumicAugmentation-1.12.2-2.1.10.zip)

(Rename from zip to jar)

**Comment by Satvn** [comment]
Testing on a server running the 2.1.10 version file, i was completely unable to replicate the crash, tried on both gaolers and the boss and i could not initiate a crash, the projectiles seem to be interacting as normal again

**Comment by TheCodex6824** [comment]
> Testing on a server running the 2.1.10 version file, i was completely unable to replicate the crash, tried on both gaolers and the boss and i could not initiate a crash, the projectiles seem to be interacting as normal again

Thank you for testing! Latest version should be available soon, in the meantime the version you should be identical to the curseforge version so you can keep using it.
