### ISSUE TITLE
Research Category: Thaumic Augmentation

### ISSUE THREAD

**Issue by LincT** [TheCodex6824/ThaumicAugmentation#340]
I wanted to verify if thaumic augmentation should come up in cards or be given points under research totals?

**Comment by TheCodex6824** [comment]
There isn't a real research category for it, so it shouldn't come up if you're making new cards. With how Thaumcraft works, every addon that registers a Thaumonomicon tab for itself has to get a research category, even if they don't plan on using it. So even though I don't use a TA category, it still technically exists, and can be randomly selected by some cards. I made the TA research cards not give research in addons like this, but I can't do much about other cards.
