### ISSUE TITLE
[Suggestion] Morphic Tubes

### ISSUE THREAD

**Issue by LincT** [TheCodex6824/ThaumicAugmentation#347]
I got the idea from EnderIO. what if there was a way to run tubes through blocks so you have less of the setup showing or could put blocks on top of the tubes that require a full block for support. maybe even a way to make them look like other blocks

**Comment by Vapaman** [comment]
Something similiar was already suggested:
https://github.com/TheCodex6824/ThaumicAugmentation/issues/198

**Comment by LincT** [comment]
good catch, closing in favor of [#198 ](https://github.com/TheCodex6824/ThaumicAugmentation/issues/198)
