### ISSUE TITLE
Entering Emptiness crashes my game, and breaks the modpack.

### ISSUE THREAD

**Issue by OverOcto** [TheCodex6824/ThaumicAugmentation#349]
Every time I enter the dimensional fracture my game crashes and when I try to re-open it it crashes again.

Tried rebuilding the pack, same issue. Seems to have trouble loading the dimension, but that doesnt explain the inability to load my game anymore.
I've attached the crash report I keep getting, please help.

[crash-2023-07-12_04.34.14-server.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/12025804/crash-2023-07-12_04.34.14-server.txt)

**Comment by DoomRater** [comment]
The crash appears to be with TickDynamic, a coremod designed to keep the game running at a smooth 20 tics per second.  Something it is trying to do is interfering when stepping into the new dimension.  Try disabling it and see if you can load the world.

**Comment by OverOcto** [comment]
That fixed it! Thanks! :D
