### ISSUE TITLE
Eldritch Guardian Crash

### ISSUE THREAD

**Issue by Crazy-Barks** [TheCodex6824/ThaumicAugmentation#355]
Good Afternoon,

I'm having issues that whenever the Eldritch Guardian spawns it immediately crashes my game. i have a work around but its very time consuming. Currently i have to toggle on and off the remove error entities in the forge config. this requires me to start up Minecraft twice and with over 100 mods it takes some serious time. I've attached a copy of the crash report. any help would be appreciated.

[crash-2023-09-09_21.52.55-server.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/12567014/crash-2023-09-09_21.52.55-server.txt)

**Comment by TheCodex6824** [comment]
That sounds really annoying, sorry you have to deal with that. Unfortunately, this is the classic case of some unknown mod messing things up enough to cause a seemingly impossible condition to be come possible on my end. If you manage to figure out which mod it is I would be very grateful, but I understand if you're not willing to spend time on that.

I can make it stop crashing in the next update, but until then you can also fix it by putting this in the "disabledTransformers" section of your config:
`thecodex6824.thaumicaugmentation.core.transformer.TransformerEldritchGuardianFog`

Note that this disables the code responsible for making eldritch guardians not create fog in some places, so some are going to be harder / more annoying.

**Comment by Crazy-Barks** [comment]
Hopefully i put that code in right, i put it between the <Chevrons>, I'm not sure how it'll be harder or more annoying. And i really appreciate the help, and yeah i totally understand with 100+ mods some of them are gonna cause issues.
