### ISSUE TITLE
The thaumostatic harness breaks if used with creative mode flight, and potentially other flight mods

### ISSUE THREAD

**Issue by xxXCuriositykilledthecatXxx** [TheCodex6824/ThaumicAugmentation#358]
I've noticed that you can functionally permenantly break your thaumostatic harness by flying in creative mode with it on. It seems to happen randomly when you start flying/stop when you're low of vis. As far as I know this doesn't effect never charged harnesses. 
The easiest way to replicate this is to grab a harness and a method to charge one. You then charge the harness a small amount, then use it until it's out of vis. Then you go into creative and just spam jump for a few seconds. It appears that when spamming jump you go into the negative with charge, while because you're in creative the tool tip says you're not. 
From what I understand you can fix your harness, but that requires your harness to have enough room left to go back into the positive. For example if you managed to do this enough with a fully charged thaumostatic harness it would be permanently broken as there's not enough space to get another 200 charge.

**Comment by TheCodex6824** [comment]
Yep some stuff is definitely broken here. I didn't get it to display a negative charge, but the NBT tag that tracks the accumulated vis cost went to a number way higher than it should have been.
