### ISSUE TITLE
Dimensional doors and emptyness

### ISSUE THREAD

**Issue by shoverno2** [TheCodex6824/ThaumicAugmentation#36]
Two mods adding void dimensions.
Why not to make some compability between your mod and dim doors?
You can add something simple, like better chance to seek door in emptyness(For example, 1 door for every 5-10 chunk in emptyness).
Or you can add some useful stuff(limbo escape stuff, thaumic dim door stuff, warded dim door(will be pretty COOL) and other interesting stuff)
Also, there sould be some equality of dim doors dimension with emptyness. For emptyness augment, of course...

**Comment by TheCodex6824** [comment]
With how much we have planned, I don't think we're going to have time to do this. Of course, you're always welcome to make your own addon (an addon-addon), including letting me know if there's something missing from the API.
