### ISSUE TITLE
Warding doesn't prevent fire damage

### ISSUE THREAD

**Issue by xxXCuriositykilledthecatXxx** [TheCodex6824/ThaumicAugmentation#360]
I warded a couple greatwood planks, and a few slabs only for them to catch fire and break which as stated in the entry shouldn't happen.

**Comment by TheCodex6824** [comment]
Apparently this happens for Thaumcraft planks, but not others I have tried. Vanilla planks and Botania living wood work properly, silverwood and greatwood planks do not.
