### ISSUE TITLE
Can you release a new version?

### ISSUE THREAD

**Issue by mczph** [TheCodex6824/ThaumicAugmentation#369]
I have encountered a issue and it was fixed by  this [comment](https://github.com/TheCodex6824/ThaumicAugmentation/commit/282c473f97eb0c6d1361dfe03ad7152545695fa6) but it hasn't been released on Curseforge or any other platform.

**Comment by LincT** [comment]
I'm a huge fan as well, and I've seen many things fixed/implemented in the issues tracker that I look forward to.

However it might be best if we are patient as the developer is probably making sure the next release is well organized and properly ready.

If I could, I'd support the dev by showing appreciation for what is, or maybe [buy them a cup of coffee](https://www.buymeacoffee.com/)?

**Comment by mczph** [comment]
I understand, I just wish to remind the author if he has the will, luckily it's [very promising](https://github.com/TheCodex6824/ThaumicAugmentation/commit/c75253837ad8dc2f41fd37d2a099c950f9638d40). Regarding sponsorship, my region and currency are not supported by the platform, but there is no denying that ThaumicAugmentation is one of the best Thaumcraft addons.

**Comment by TheCodex6824** [comment]
Thanks for your patience. As you noticed, I attempted to release an update a few nights ago, but ran into some buildscript issues that I resolved today. Update will be [here](https://legacy.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/5106451) once it's approved. Note that it is a beta, since between the bugfixes being more complex than usual, the build breaking, and me not having much time to test, I'm being cautious.

I also appreciate the sentiment behind wanting to donate. I'm not sure if I talked about this before, but I don't accept donations for this project because I work on it on an irregular schedule (as you can tell from this issue existing) and would feel bad if I took people's money for that. I also am doing well enough financially from $DAYJOB, so I would rather people either keep their money for themselves or give it to someone else that needs it more than I do.

**Comment by mczph** [comment]
Hello, I was happy to receive the update this morning, but it looks like the new version and [AquaAcrobatics](https://github.com/embeddedt/aquaacrobatics) have a mixin load order issue that prevents the game from starting
Here's the [debug.log](https://mclo.gs/71Rpy2T) (I tested it in the minimum modlist)

**Comment by TheCodex6824** [comment]
> Hello, I was happy to receive the update this morning, but it looks like the new version have a mixin load order issue with [AquaAcrobatics](https://github.com/embeddedt/aquaacrobatics) and any mods mods modifier the same content as ThuamicAugmentation(like EntityCulling) which prevents the game from starting,this reminds me of this [comment](https://github.com/TheCodex6824/ThaumicAugmentation/commit/282c473f97eb0c6d1361dfe03ad7152545695fa6) Here's the [debug.log](https://mclo.gs/71Rpy2T) of AquaAcrobatics (I tested it in the minimum modlist) After thinking about it for a while, I think this problem is also related to AquaAcrobatics because its random crashes even in older versions and I'll report it as well

Yeah... this is the kind of thing I was afraid of. I guess there is a chance it could be AquaAcrobatics' fault here, but one of the changes that made me make the update a beta was a coremod change that could potentially be causing this (namely the change to check class hierarchy to determine which classes to modify in some cases). 

If TA and AquaAcrobatics worked together before and only broke on this update, it's probably my fault and I need to go back to the drawing board on that change with a new approach.

**Comment by mczph** [comment]
> > Hello, I was happy to receive the update this morning, but it looks like the new version have a mixin load order issue with [AquaAcrobatics](https://github.com/embeddedt/aquaacrobatics) and any mods mods modifier the same content as ThuamicAugmentation(like EntityCulling) which prevents the game from starting,this reminds me of this [comment](https://github.com/TheCodex6824/ThaumicAugmentation/commit/282c473f97eb0c6d1361dfe03ad7152545695fa6) Here's the [debug.log](https://mclo.gs/71Rpy2T) of AquaAcrobatics (I tested it in the minimum modlist) After thinking about it for a while, I think this problem is also related to AquaAcrobatics because its random crashes even in older versions and I'll report it as well
> 
> Yeah... this is the kind of thing I was afraid of. I guess there is a chance it could be AquaAcrobatics' fault here, but one of the changes that made me make the update a beta was a coremod change that could potentially be causing this (namely the change to check class hierarchy to determine which classes to modify in some cases). 
> 
> If TA and AquaAcrobatics worked together before and only broke on this update, it's probably my fault and I need to go back to the drawing board on that change with a new approach.

They were able to work together before the update

**Comment by Krutoy242** [comment]
Can approve - on version prior `2.1.12` game launched normaly, now its crashing with AquaAcrobatics mixins https://mclo.gs/qgpvcKW

**Comment by ALJ323** [comment]
Also crashing with BetterThirdPerson
Never had AquaAcrobatics installed, but its throwing the same/similar error as in the other logs.

**Comment by SettingDust** [comment]
I'm facing a problem with the beta version. But it's fine with the modified version by myself with only the lazy loaded config commit.
I think it's caused by this check changed https://github.com/TheCodex6824/ThaumicAugmentation/commit/508999a2daee3efa89db5cbe187adb4c7db695f6#diff-a5db0991041ade883d045fe1c948fdcbbe68dadbedd3514dcb362a9b91658413L153-R192

```
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer thecodex6824.thaumicaugmentation.core.TATransformer@70798698 from coremod Thaumic Augmentation Core Plugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 28 more
Caused by: java.lang.NullPointerException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168)
	at thecodex6824.thaumicaugmentation.core.TATransformer.transform(TATransformer.java:194)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 30 more
```

**Comment by TheCodex6824** [comment]
Sorry everyone, looks like I needed to throw more mods that use mixins into my testing modpack. I submitted an update (also a beta) to CurseForge but apparently it "failed processing" and is under manual review. I'm not sure why it failed given that it worked fine in testing and I'm not obfuscating code or anything stupid like that, but please let me know ASAP as usual if it's not working.

**Comment by TheCodex6824** [comment]
> > Sorry everyone, looks like I needed to throw more mods that use mixins into my testing modpack. I submitted an update (also a beta) to CurseForge but apparently it "failed processing" and is under manual review. I'm not sure why it failed given that it worked fine in testing and I'm not obfuscating code or anything stupid like that, but please let me know ASAP as usual if it's not working.
> 
> It seems that there are some problems in the review. Can you upload a mod file to github first so that I can do a quick test?

Done, check the releases section. Still nothing from CurseForge.

**Comment by mczph** [comment]
> > > Sorry everyone, looks like I needed to throw more mods that use mixins into my testing modpack. I submitted an update (also a beta) to CurseForge but apparently it "failed processing" and is under manual review. I'm not sure why it failed given that it worked fine in testing and I'm not obfuscating code or anything stupid like that, but please let me know ASAP as usual if it's not working.
> > 
> > 
> > It seems that there are some problems in the review. Can you upload a mod file to github first so that I can do a quick test?
> 
> Done, check the releases section. Still nothing from CurseForge.

It's fine now

**Comment by SettingDust** [comment]
Fine now
