### ISSUE TITLE
Warding indicator

### ISSUE THREAD

**Issue by xxXCuriositykilledthecatXxx** [TheCodex6824/ThaumicAugmentation#392]
The current warding indicator is difficult to look at, and makes it frustrating to avoid holes when you're warding larger structures. Please consider changing it to something easier to read.

**Comment by LincT** [comment]
I think there's an open issue for warding management already

**Comment by LincT** [comment]
https://github.com/TheCodex6824/ThaumicAugmentation/issues/293
