### ISSUE TITLE
architect with new gloves

### ISSUE THREAD

**Issue by shoverno2** [TheCodex6824/ThaumicAugmentation#4]
Well, this mod like from mine dream.
But there some bad news about using architecting focuses.
Game crashes, when trying to use those focus.
there's crash report
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  ClientFixer (clientfixer-1.12.2-1.9.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.9.43_mc1.12.2.jar)
  HCASM (HammerCore-1.12.2-2.0.4.4.jar)
  DCLoadingPlugin (DummyCoreUnofficial-2.4.112.5.jar)
  ShoulderPlugin (ShoulderSurfing-1.12.2-1.15.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.19_mc1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 4/26/19 3:53 PM
Description: Unexpected error

java.lang.ClassCastException: thaumcraft.api.casters.FocusPackage cannot be cast to thaumcraft.api.items.IArchitect
	at thecodex6824.thaumicaugmentation.common.item.ItemTieredCasterGauntlet.getArchitectBlocks(ItemTieredCasterGauntlet.java:232)
	at thaumcraft.client.lib.events.WandRenderingHandler.handleArchitectOverlay(WandRenderingHandler.java:341)
	at thaumcraft.client.lib.events.RenderEventHandler.renderLast(RenderEventHandler.java:583)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_85_RenderEventHandler_renderLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
	at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1951)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at thecodex6824.thaumicaugmentation.common.item.ItemTieredCasterGauntlet.getArchitectBlocks(ItemTieredCasterGauntlet.java:232)
	at thaumcraft.client.lib.events.WandRenderingHandler.handleArchitectOverlay(WandRenderingHandler.java:341)
	at thaumcraft.client.lib.events.RenderEventHandler.renderLast(RenderEventHandler.java:583)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_85_RenderEventHandler_renderLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
	at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1951)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['_Tulio_'/334, l='MpServer', x=-1961.10, y=65.00, z=520.74]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1959,65,517), Chunk: (at 9,4,5 in -123,32; contains blocks -1968,0,512 to -1953,255,527), Region: (-4,1; contains chunks -128,32 to -97,63, blocks -2048,0,512 to -1537,255,1023)
	Level time: 547451 game time, 842929 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 4 total; [EntityGate['Gate'/213, l='MpServer', x=-1958.50, y=65.00, z=529.50], EntityGate['Gate'/214, l='MpServer', x=-1958.50, y=64.00, z=530.50], EntityLlama['Лама'/200, l='MpServer', x=-1984.55, y=65.00, z=465.45], EntityPlayerSP['_Tulio_'/334, l='MpServer', x=-1961.10, y=65.00, z=520.74]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 847555008 bytes (808 MB) / 2315288576 bytes (2208 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx4096M -XX:+UseConcMarkSweepGC
	IntCache: cache: 4, tcache: 0, allocated: 0, tallocated: 70
	FML: MCP 9.42 Powered by Forge 14.23.5.2825 Optifine OptiFine_1.12.2_HD_U_E4_pre1 62 mods loaded, 62 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                       | Version                     | Source                                        | Signature                                |
	|:------ |:------------------------ |:--------------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                | 1.12.2                      | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                      | 9.42                        | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                      | 8.0.99.99                   | forge-1.12.2-14.23.5.2825.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                    | 14.23.5.2825                | forge-1.12.2-14.23.5.2825.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy        | 1.0.0                       | minecraft.jar                                 | None                                     |
	| LCHIJA | itemphysic               | 1.4.0                       | minecraft.jar                                 | None                                     |
	| LCHIJA | ClientFixer              | 1.12.2-1.9                  | minecraft.jar                                 | None                                     |
	| LCHIJA | ambience                 | GRADLE:VERSION-GRADLE:BUILD | Ambience+1.1-10 (1).jar                       | None                                     |
	| LCHIJA | ambientsounds            | 3.0                         | AmbientSounds_v3.0.4_mc1.12.2.jar             | None                                     |
	| LCHIJA | codechickenlib           | 3.2.2.353                   | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | ancientwarfare           | 1.12.2-2.7.0.574            | ancientwarfare-1.12.2-2.7.0.574.jar           | None                                     |
	| LCHIJA | ancientwarfarestructure  | @VERSION@                   | ancientwarfare-1.12.2-2.7.0.574.jar           | None                                     |
	| LCHIJA | ancientwarfarevehicle    | 1.12.2-2.7.0.574            | ancientwarfare-1.12.2-2.7.0.574.jar           | None                                     |
	| LCHIJA | ancientwarfarenpc        | 1.12.2-2.7.0.574            | ancientwarfare-1.12.2-2.7.0.574.jar           | None                                     |
	| LCHIJA | ancientwarfareautomation | 1.12.2-2.7.0.574            | ancientwarfare-1.12.2-2.7.0.574.jar           | None                                     |
	| LCHIJA | antiqueatlas             | 4.5.0                       | antiqueatlas-1.12.2-4.5.0.jar                 | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCHIJA | antiqueatlasoverlay      | 1.2                         | antiqueatlas-1.12.2-4.5.0.jar                 | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCHIJA | baubles                  | 1.5.2                       | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | bibliocraft              | 2.4.5                       | BiblioCraft[v2.4.5][MC1.12.2].jar             | None                                     |
	| LCHIJA | biomesoplenty            | 7.0.1.2427                  | BiomesOPlenty-1.12.2-7.0.1.2427-universal.jar | None                                     |
	| LCHIJA | bookshelf                | 2.3.577                     | Bookshelf-1.12.2-2.3.577.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | ctm                      | MC1.12.2-0.3.3.22           | CTM-MC1.12.2-0.3.3.22.jar                     | None                                     |
	| LCHIJA | chisel                   | MC1.12.2-0.2.1.35           | Chisel-MC1.12.2-0.2.1.35.jar                  | None                                     |
	| LCHIJA | cosmeticarmorreworked    | 1.12.2-v4a                  | CosmeticArmorReworked-1.12.2-v4a.jar          | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | creativecore             | 1.9.9                       | CreativeCore_v1.9.43_mc1.12.2.jar             | None                                     |
	| LCHIJA | forgelin                 | 1.8.2                       | Forgelin-1.8.2.jar                            | None                                     |
	| LCHIJA | thaumcraft               | 6.1.BETA26                  | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |
	| LCHIJA | thaumic_arcana           | 1.2.0                       | Thaumic+Arcana-1.2.0.jar                      | None                                     |
	| LCHIJA | jei                      | 4.15.0.277                  | jei_1.12.2-4.15.0.277.jar                     | None                                     |
	| LCHIJA | darkutils                | 1.8.226                     | DarkUtils-1.12.2-1.8.226.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | dimdoors                 | 3.0.9+287                   | DimensionalDoors-3.0.9-287.jar                | None                                     |
	| LCHIJA | dummycore                | 2.4.112.5.                  | DummyCoreUnofficial-2.4.112.5.jar             | None                                     |
	| LCHIJA | dynamictrees             | 1.12.2-0.9.4                | DynamicTrees-1.12.2-0.9.4.jar                 | None                                     |
	| LCHIJA | dynamictreesbop          | 1.12.2-1.4.1e               | DynamicTreesBOP-1.12.2-1.4.1e.jar             | None                                     |
	| LCHIJA | dynamictreestc           | 1.12.2-1.4.1e               | DynamicTreesTC-1.12.2-1.4.1e.jar              | None                                     |
	| LCHIJA | fancylamps               | 1.1.0                       | fancylamps-1.1.0.jar                          | None                                     |
	| LCHIJA | forbidden_arcanus        | 1.12.2-0.6                  | forbidden_arcanus-1.12.2-0.6.jar              | None                                     |
	| LCHIJA | hammercore               | 2.0.4.4                     | HammerCore-1.12.2-2.0.4.4.jar                 | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | thaumadditions           | 13r                         | ThaumicAdditions-1.12.2-13r.jar               | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | llibrary                 | 1.7.18                      | llibrary-1.7.18-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire               | 1.7.1                       | iceandfire-1.7.1-1.12.2.jar                   | None                                     |
	| LCHIJA | mantle                   | 1.12-1.3.3.49               | Mantle-1.12-1.3.3.49.jar                      | None                                     |
	| LCHIJA | moreplayermodels         | 1.12.2                      | MorePlayerModels_1.12.2(18jan18).jar          | None                                     |
	| LCHIJA | mowziesmobs              | 1.5.4                       | mowziesmobs-1.5.4.jar                         | None                                     |
	| LCHIJA | uteamcore                | 2.2.4.94                    | u_team_core-1.12.2-2.2.4.94.jar               | None                                     |
	| LCHIJA | musicplayer              | 1.2.0.5                     | music_player-1.12.2-1.2.0.5.jar               | None                                     |
	| LCHIJA | nospawnzone              | 1.12.2.1.3                  | NoSpawnZone-1.12.2.1.3.jar                    | None                                     |
	| LCHIJA | nei                      | 2.4.2                       | NotEnoughItems-1.12.2-2.4.2.240-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | tconstruct               | 1.12.2-2.12.0.135           | TConstruct-1.12.2-2.12.0.135.jar              | None                                     |
	| LCHIJA | planarartifice           | 0.13                        | planarartifice-0.13.jar                       | None                                     |
	| LCHIJA | plustic                  | 7.0.5.2                     | plustic-7.0.5.2.jar                           | None                                     |
	| LCHIJA | shouldersurfing          | 1.15                        | ShoulderSurfing-1.12.2-1.15.jar               | d6261bb645f41db84c74f98e512c2bb43f188af2 |
	| LCHIJA | silentlib                | 3.0.13                      | SilentLib-1.12.2-3.0.13+167.jar               | None                                     |
	| LCHIJA | tc6aspects4jei           | 0.0.2a                      | tc6aspects4jei-0.0.2a.jar                     | None                                     |
	| LCHIJA | tg                       | 0.1.5.0                     | Thaumic_Gadgets_1.12.2_0.1.5.1_tb.26.jar      | None                                     |
	| LCHIJA | thaumicaugmentation      | 1.12.2-1.0.3                | ThaumicAugmentation-1.12.2-1.0.3.jar          | None                                     |
	| LCHIJA | thaumicbases             | 3.3.310.5r                  | thaumicbases-3.3.345.6r.jar                   | None                                     |
	| LCHIJA | thaumicperiphery         | 0.3.0                       | thaumicperiphery-0.3.0.jar                    | None                                     |
	| LCHIJA | thaumicrestoration       | 1.3.1                       | ThaumicRestoration-1.3.1.jar                  | None                                     |
	| LCHIJA | thaumictinkerer          | 1.12.2-5.0-353c71c          | thaumictinkerer-1.12.2-5.0-353c71c.jar        | None                                     |
	| LCHIJA | thaumicwonders           | 1.3.0                       | thaumicwonders-1.3.0.jar                      | None                                     |
	| LCHIJA | torohealthmod            | 1.12.2-11                   | torohealth-1.12.2-11.jar                      | None                                     |

	Loaded coremods (and transformers): 
ClientFixer (clientfixer-1.12.2-1.9.jar)
  com.gamerforea.clientfixer.asm.ASMTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CreativePatchingLoader (CreativeCore_v1.9.43_mc1.12.2.jar)
  
HCASM (HammerCore-1.12.2-2.0.4.4.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
DCLoadingPlugin (DummyCoreUnofficial-2.4.112.5.jar)
  DummyCore.ASM.DCASMManager
ShoulderPlugin (ShoulderSurfing-1.12.2-1.15.jar)
  com.teamderpy.shouldersurfing.asm.ShoulderTransformations
ForgelinPlugin (Forgelin-1.8.2.jar)
  
ItemPatchingLoader (ItemPhysic_Full_1.4.19_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.4.13283 Compatibility Profile Context 14.501.1003.0' Renderer: 'AMD Radeon HD 5700 Series'
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 645 names; 3693 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KDQogICAgIyBSZXBsYWNlIHZhbmlsbGEgZnVybmFjZSBhbmQgYnJld2luZyBzdGFuZCBwcm9ncmVzcyBiYXJzIHRvIHVzZSBzbW9vdGggcmVuZGVyaW5nPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJTbW9vdGggVmFuaWxsYSBHdWlzIj10cnVlDQp9DQoNCg0KaXdyZW5jaCB7DQogICAgIyBXaGF0IGlzIHRoZSBjb2xvciB3aGVuIHRoZSBob3ZlcmVkIGJsb2NrIGlzIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6R3JlZW49MjJGRjIyDQoNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgTk9UIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6UmVkPUZGMjIyMg0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
Pastebin Connection: Okay.
Dependent Mods:
    -Thaumic Additions: Reconstructed (thaumadditions) @13r

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	[DummyCore]: 'Special case ASM modification mods: ''Note, that these mods might not be involved in the crash in ANY WAY!''DummyCore just prints some known mods for a lot of ASM modifications''dummycore''CodeChickenLib'
	Launched Version: GTI
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 5700 Series GL version 4.4.13283 Compatibility Profile Context 14.501.1003.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: AntiqueAtlasExtra-v1.2.zip
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM)2 Quad CPU Q9300 @ 2.50GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E4_pre1
	OptiFine Build: 20181218-105534
	Render Distance Chunks: 7
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.13283 Compatibility Profile Context 14.501.1003.0
	OpenGlRenderer: AMD Radeon HD 5700 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4`
Also, i thing it can be happen cause of vis discount and more chank vis drain.
Please, fix it, mod too beautiful)

**Comment by TheCodex6824** [comment]
So this was a simple thing that will be fixed in the next release (which should be up on CurseForge soon). However, while testing I ran into something that prevents the exchange focus from currently working with my custom gauntlets, which I have not fixed yet (and I need to think about how I want to handle that). So the game shouldn't crash anymore, but exchange will not work still.
