### ISSUE TITLE
Dimensional compatibility

### ISSUE THREAD

**Issue by shoverno2** [TheCodex6824/ThaumicAugmentation#41]
Your dim-augments support only 3 vanilla dimensions and one of yours. But there so many mods that adding dimensions. So, why not to add configuration list of:
1) overworld like dimensions
2) nether like dimensions
3) end like dimensions
4) void dimensions
That will provide compatibility to many mods.

**Comment by TheCodex6824** [comment]
Not a bad idea, it'll probably have to be another config option list though. There doesn't seem to be any sort of registry for dimension types like BiomeDictionary, so that's a shame.

**Comment by shoverno2** [comment]
And...
What about this?
https://www.curseforge.com/minecraft/mc-mods/accidentally-circumstantial-events-ace
I see there something about tracking what the dim.

**Comment by TheCodex6824** [comment]
That's kinda what I mean by a config; dimension IDs identify individual dimensions, but what I meant was there are no nice types they can register to like "forest" or "void".

**Comment by TheCodex6824** [comment]
The latest update added config options to specify which dimensions should count for each of the augments. You will have to add them manually, but I feel like that was the best option as people's expectations of what dimensions should count or not are probably vastly different and will differ from modpack to modpack.
