### ISSUE TITLE
Thaum key disfunction. Logs included.

### ISSUE THREAD

**Issue by shoverno2** [TheCodex6824/ThaumicAugmentation#45]
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 2019-09-21 22:10:36 MSK
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:256)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at thecodex6824.thaumicaugmentation.common.item.ItemKey.onItemUseFirst(ItemKey.java:123)
    at net.minecraft.item.ItemStack.onItemUseFirst(ItemStack.java:200)
    at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:439)
    at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_211, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 387103136 bytes (369 MB) / 2089058304 bytes (1992 MB) up to 3742629888 bytes (3569 MB)
  JVM Flags: 3 total; -Xmn128M -Xmx3582M -XX:+UseConcMarkSweepGC
  IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 73
  FML: MCP 9.42 Powered by Forge 14.23.5.2844 Optifine OptiFine_1.12.2_HD_U_E4_pre1 108 mods loaded, 108 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                                           | Version                     | Source                                        | Signature                                |
       |:------ |:-------------------------------------------- |:--------------------------- |:--------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                                    | 1.12.2                      | minecraft.jar                                 | None                                     |
       | LCHIJA | mcp                                          | 9.42                        | minecraft.jar                                 | None                                     |
       | LCHIJA | FML                                          | 8.0.99.99                   | forge-1.12.2-14.23.5.2844.jar                 | None                                     |
       | LCHIJA | forge                                        | 14.23.5.2844                | forge-1.12.2-14.23.5.2844.jar                 | None                                     |
       | LCHIJA | creativecoredummy                            | 1.0.0                       | minecraft.jar                                 | None                                     |
       | LCHIJA | itemphysic                                   | 1.4.0                       | minecraft.jar                                 | None                                     |
       | LCHIJA | betterfonts                                  | 1.9.1                       | minecraft.jar                                 | None                                     |
       | LCHIJA | com.elytradev.movingworld.common.asm.coremod |                             | minecraft.jar                                 | None                                     |
       | LCHIJA | ClientFixer                                  | 1.12.2-1.9                  | minecraft.jar                                 | None                                     |
       | LCHIJA | foamfixcore                                  | 7.7.4                       | minecraft.jar                                 | None                                     |
       | LCHIJA | dsurroundcore                                | 3.5.4.3                     | minecraft.jar                                 | None                                     |
       | LCHIJA | ambience                                     | GRADLE:VERSION-GRADLE:BUILD | Ambience+1.1-10.jar                           | None                                     |
       | LCHIJA | codechickenlib                               | 3.2.2.353                   | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | ancientwarfare                               | 1.12.2-2.7.0.772            | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
       | LCHIJA | ancientwarfarestructure                      | 1.12.2-2.7.0.772            | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
       | LCHIJA | ancientwarfarevehicle                        | 1.12.2-2.7.0.772            | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
       | LCHIJA | ancientwarfarenpc                            | 1.12.2-2.7.0.772            | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
       | LCHIJA | ancientwarfareautomation                     | 1.12.2-2.7.0.772            | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
       | LCHIJA | antiqueatlas                                 | 4.5.0                       | antiqueatlas-1.12.2-4.5.0.jar                 | e631d7254e451d0360d0148cb21407d5511d45e9 |
       | LCHIJA | antiqueatlasoverlay                          | 1.2                         | antiqueatlas-1.12.2-4.5.0.jar                 | e631d7254e451d0360d0148cb21407d5511d45e9 |
       | LCHIJA | anvilfix                                     | 1.0.3                       | AnvilFix-1.12.2-1.0.3.jar                     | None                                     |
       | LCHIJA | jei                                          | 4.15.0.277                  | jei_1.12.2-4.15.0.277.jar                     | None                                     |
       | LCHIJA | appleskin                                    | 1.0.9                       | AppleSkin-mc1.12-1.0.9.jar                    | None                                     |
       | LCHIJA | baubles                                      | 1.5.2                       | Baubles-1.12-1.5.2 (3).jar                    | None                                     |
       | LCHIJA | artifacts                                    | 1.12.2-1.1.0                | Artifacts-1.12.2-1.1.0.jar                    | None                                     |
       | LCHIJA | astikorcarts                                 | 1.12.2-0.1.2.7              | astikorcarts-1.12.2-0.1.2.7.jar               | None                                     |
       | LCHIJA | quark                                        | r1.6-177                    | Quark-r1.6-177.jar                            | None                                     |
       | LCHIJA | autoreglib                                   | 1.3-32                      | AutoRegLib-1.3-32.jar                         | None                                     |
       | LCHIJA | betterinvisibility                           | 1.0                         | betterinvisibility-1.12-1.0.jar               | None                                     |
       | LCHIJA | betterthanmending                            | 1.1.1                       | BetterThanMending-1.1.1.jar                   | None                                     |
       | LCHIJA | biomesoplenty                                | 7.0.1.2441                  | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None                                     |
       | LCHIJA | blockdrops                                   | 1.4.0                       | blockdrops-1.12.2-1.4.0.jar                   | None                                     |
       | LCHIJA | bonsaitrees                                  | 1.1.2                       | bonsaitrees-1.1.2-b144.jar                    | None                                     |
       | LCHIJA | bookshelf                                    | 2.3.585                     | Bookshelf-1.12.2-2.3.585.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | bmtr                                         | 0.4                         | BringMeTheRings-0.4.jar                       | None                                     |
       | LCHIJA | kjlib                                        | 1.0.4                       | kjlib-1.0.4.jar                               | None                                     |
       | LCHIJA | caveroot                                     | 1.1.1                       | caveroot-1.1.1.jar                            | None                                     |
       | LCHIJA | chameleon                                    | 1.12-4.1.3                  | Chameleon-1.12-4.1.3.jar                      | None                                     |
       | LCHIJA | ctm                                          | MC1.12.2-0.3.3.22           | CTM-MC1.12.2-0.3.3.22.jar                     | None                                     |
       | LCHIJA | chisel                                       | MC1.12.2-0.2.1.35           | Chisel-MC1.12.2-0.2.1.35.jar                  | None                                     |
       | LCHIJA | comforts                                     | 1.4.1.2                     | comforts-1.12.2-1.4.1.2.jar                   | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | cosmeticarmorreworked                        | 1.12.2-v4a                  | CosmeticArmorReworked-1.12.2-v4a.jar          | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | cosmiclib                                    | 0.4.0                       | CosmicLib-1.12.2-0.4.0.BETA.jar               | d3974446c00f9f1d275edce305771eeddf30c658 |
       | LCHIJA | creativecore                                 | 1.9.9                       | CreativeCore_v1.9.45_mc1.12.2.jar             | None                                     |
       | LCHIJA | movingworld                                  | 1.12-6.342                  | movingworld-1.12-6.342-full.jar               | None                                     |
       | LCHIJA | davincisvessels                              | @DVESSELSVER@               | davincisvessels-1.12-6.340-full (2).jar       | None                                     |
       | LCHIJA | dimdoors                                     | 3.0.9+287                   | DimensionalDoors-3.0.9-287.jar                | None                                     |
       | LCHIJA | dummycore                                    | 2.4.112.5.                  | DummyCoreUnofficial-2.4.112.5.jar             | None                                     |
       | LCHIJA | eplus                                        | 5.0.176                     | EnchantingPlus-1.12.2-5.0.176.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | minerva                                      | 1.0.13                      | minerva-library-1.0.13.jar                    | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
       | LCHIJA | extraalchemy                                 | 0.5.1                       | extraalchemy-0.5.1.jar                        | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
       | LCHIJA | familiarfauna                                | 1.0.11                      | FamiliarFauna-1.12.2-1.0.11.jar               | None                                     |
       | LCHIJA | fancylamps                                   | 1.1.0                       | fancylamps-1.1.0.jar                          | None                                     |
       | LCHIJA | fantasticlib                                 | 1.12.2.021                  | FantasticLib-1.12.2.021.jar                   | None                                     |
       | LCHIJA | fastleafdecay                                | v14                         | FastLeafDecay-v14.jar                         | None                                     |
       | LCHIJA | foamfix                                      | 0.10.5-1.12.2               | foamfix-0.10.5-1.12.2.jar                     | None                                     |
       | LCHIJA | forgelin                                     | 1.8.4                       | Forgelin-1.8.4.jar                            | None                                     |
       | LCHIJA | globalxp                                     | v1.4.3                      | globalxp-1.12.x-v1.4.3.jar                    | None                                     |
       | LCHIJA | hammercore                                   | 2.0.5.0                     | HammerCore-1.12.2-2.0.5.0.jar                 | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCHIJA | hardcoredarkness                             | 2.0                         | HardcoreDarkness-MC1.12.2-2.0.jar             | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | thaumcraft                                   | 6.1.BETA26                  | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |
       | LCHIJA | thaumadditions                               | 20r                         | ThaumicAdditions-1.12.2-20r.jar               | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCHIJA | llibrary                                     | 1.7.18                      | llibrary-1.7.18-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | iceandfire                                   | 1.8.1                       | iceandfire-1.8.1.jar                          | None                                     |
       | LCHIJA | jeresources                                  | 0.9.2.60                    | JustEnoughResources-1.12.2-0.9.2.60.jar       | None                                     |
       | LCHIJA | lostmagic                                    | 1.0                         | lostmagic-1.0.1.jar                           | None                                     |
       | LCHIJA | radixcore                                    | 1.12.x-2.2.1                | RadixCore-1.12.x-2.2.1-universal.jar          | None                                     |
       | LCHIJA | mca                                          | 1.12.2-5.3.1                | MCA-1.12.x-5.3.1-universal.jar                | None                                     |
       | LCHIJA | testdummy                                    | 1.12                        | MmmMmmMmmMmm-1.12-1.14.jar                    | None                                     |
       | LCHIJA | guilib                                       | $version                    | morepaintings-paintings-1.12.2-5.0.1.2.jar    | None                                     |
       | LCHIJA | paintingselgui                               | $version                    | morepaintings-paintings-1.12.2-5.0.1.2.jar    | None                                     |
       | LCHIJA | morepaintings                                | $version                    | morepaintings-paintings-1.12.2-5.0.1.2.jar    | None                                     |
       | LCHIJA | moreplayermodels                             | 1.12.2                      | MorePlayerModels_1.12.2(18jan18).jar          | None                                     |
       | LCHIJA | mowziesmobs                                  | 1.5.4                       | mowziesmobs-1.5.4.jar                         | None                                     |
       | LCHIJA | mysticalmechanics                            | 0.10                        | Mystical+Mechanics-0.10.jar                   | None                                     |
       | LCHIJA | thaumicperiphery                             | 0.3.1                       | thaumicperiphery-0.3.1.jar                    | None                                     |
       | LCHIJA | mystgears                                    | 1.0.5                       | mystgears-1.0.5.jar                           | None                                     |
       | LCHIJA | nospawnzone                                  | 1.12.2.1.3                  | NoSpawnZone-1.12.2.1.3 (1).jar                | None                                     |
       | LCHIJA | nei                                          | 2.4.2                       | NotEnoughItems-1.12.2-2.4.2.240-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | pcb                                          | 1.5.0                       | portablecraftbench-1.12.2-1.5.1.jar           | None                                     |
       | LCHIJA | rfp2                                         | 1.12.2-1.1.0                | RealFirstPerson2-1.12.2-1.1.0.jar             | None                                     |
       | LCHIJA | ruins                                        | 17.1                        | Ruins-1.12.2.jar                              | None                                     |
       | LCHIJA | rustic                                       | 1.1.1                       | rustic-1.1.1.jar                              | None                                     |
       | LCHIJA | rusticthaumaturgy                            | 4.4a                        | Rustic+Thaumaturgy-4.4a.jar                   | None                                     |
       | LCHIJA | sereneseasons                                | 1.2.15                      | SereneSeasons-1.12.2-1.2.15-universal.jar     | None                                     |
       | LCHIJA | silentlib                                    | 3.0.13                      | SilentLib-1.12.2-3.0.13+167.jar               | None                                     |
       | LCHIJA | simplemagnet                                 | 1.12.2-1.3.12               | simplemagnet-1.12.2-1.3.12.jar                | None                                     |
       | LCHIJA | somanyenchantments                           | 0.4.3                       | somanyenchantments+V0.4.31.jar                | None                                     |
       | LCHIJA | soundfilters                                 | 0.11_for_1.12               | SoundFilters-0.11_for_1.12.jar                | None                                     |
       | LCHIJA | tc6aspects4jei                               | 0.0.2a                      | tc6aspects4jei-0.0.2a.jar                     | None                                     |
       | LCHIJA | tg                                           | 0.1.5.0                     | Thaumic_Gadgets_1.12.2_0.1.5.1_tb.26.jar      | None                                     |
       | LCHIJA | thaumicaugmentation                          | 1.12.2-1.1.9                | ThaumicAugmentation-1.12.2-1.1.9.jar          | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
       | LCHIJA | thaumicbases                                 | 3.3.400.6r                  | thaumicbases-3.3.352.6r.jar                   | None                                     |
       | LCHIJA | thaumicjei                                   | 1.6.0                       | ThaumicJEI-1.12.2-1.6.0-27.jar                | None                                     |
       | LCHIJA | thaumicrestoration                           | 1.3.1                       | ThaumicRestoration-1.3.1a.jar                 | None                                     |
       | LCHIJA | thaumicwonders                               | 1.8.2                       | thaumicwonders-1.8.2.jar                      | None                                     |
       | LCHIJA | tlauncher_custom_cape_skin                   | 1.3                         | tlskincape_1.12.2-1.3.jar                     | None                                     |
       | LCHIJA | trashslot                                    | 8.4.6                       | TrashSlot_1.12.1-8.4.6.jar                    | None                                     |
       | LCHIJA | twilightforest                               | 3.9.984                     | twilightforest-1.12.2-3.9.984-universal.jar   | None                                     |
       | LCHIJA | uteamcore                                    | 2.2.4.94                    | u_team_core-1.12.2-2.2.4.94.jar               | None                                     |
       | LCHIJA | vanillafix                                   | 1.0.10-SNAPSHOT             | VanillaFix-1.0.10-99.jar                      | None                                     |
       | LCHIJA | walljump                                     | 1.12.2-1.2.3                | walljump-1.12.2-1.2.3.jar                     | None                                     |
       | LCHIJA | warpbook                                     | @VERSION@                   | Warpbook-1.12.2-3.2.0.jar                     | None                                     |
       | LCHIJA | waystones                                    | 4.0.72                      | Waystones_1.12.2-4.0.72.jar                   | None                                     |
       | LCHIJA | worleycaves                                  | 1.5.1                       | worleycaves-1.5.1.jar                         | None                                     |
       | LCHIJA | orelib                                       | 3.5.2.2                     | OreLib-1.12.2-3.5.2.2.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround                                    | 3.5.4.3                     | DynamicSurroundings-1.12.2-3.5.4.3.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | lemonlib                                     | 1.3.0                       | lemonlib-1.12.2-1.3.0.jar                     | None                                     |
  Loaded coremods (and transformers): ClientFixer (clientfixer-1.12.2-1.9.jar)
                                        com.gamerforea.clientfixer.asm.ASMTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-1.1.9.jar)
                                        thecodex6824.thaumicaugmentation.core.TATransformer
                                      CreativePatchingLoader (CreativeCore_v1.9.45_mc1.12.2.jar)
                                        
                                      Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      DCLoadingPlugin (DummyCoreUnofficial-2.4.112.5.jar)
                                        DummyCore.ASM.DCASMManager
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      TLSkinCapeHookLoader (tlskincape_1.12.2-1.3.jar)
                                        gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      BetterFontsCore (TTFR-1.12.1-1.9.1.jar)
                                        cubex2.ttfr.BFClassTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      CosmicLibFakeCoreMod (CosmicLib-1.12.2-0.4.0.BETA.jar)
                                        
                                      BringMeTheRings plugin (BringMeTheRings-0.4.jar)
                                        zabi.minecraft.bmtr.core.BaublesTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      ItemPatchingLoader (ItemPhysic_Full_1.4.21_mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
                                        lumien.hardcoredarkness.asm.ClassTransformer
                                      HCASM (HammerCore-1.12.2-2.0.5.0.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      MovingWorldCore (movingworld-1.12-6.342-full.jar)
                                        
                                      DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
                                        org.orecruncher.dsurround.asm.Transformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
                           OreDictionary Info: Registered 516 names; 3850 stacks.
                           Pastebin Connection: Okay.
                           Dependent Mods:
                               -Thaumic Additions: Reconstructed (thaumadditions) @20r
  [DummyCore]: 'Special case ASM modification mods: ''Note, that these mods might not be involved in the crash in ANY WAY!''DummyCore just prints some known mods for a lot of ASM modifications''dummycore''CodeChickenLib'
  Suspected Mods: Thaumic Augmentation (thaumicaugmentation)

**Comment by shoverno2** [comment]
Nice)

**Comment by TheCodex6824** [comment]
The new version [here](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/2811488) has a fix for this (and the Voidseer's Casting Gauntlet bug as well).
