### ISSUE TITLE
Crash on Startup - Hardness issue again

### ISSUE THREAD

**Issue by googlepox** [TheCodex6824/ThaumicAugmentation#47]
Hello! 

I recently crashed on startup and the [crash log](https://paste.dimdev.org/olahakecid.mccrash) points to Warp Drive and Thaumic Augmentation, specifically regarding TAHooks.checkWardHardness. Looking in past issues brought me to [this bug](https://github.com/TheCodex6824/ThaumicAugmentation/issues/20) but it says it was solved. Am I doing something wrong?

EDIT: It seems to be trying to load a chunk during startup?

**Comment by TheCodex6824** [comment]
It looks like Warp Drive was trying to be a good citizen and use a fake world and position while trying to adjust block hardness and such during startup - which ironically meant it bypassed my check for mods trying to get hardness during startup, as the mods in the issue you found didn't bother with that. So yeah, this is definitely my bad, I'll have a fix for this soon.

**Comment by TheCodex6824** [comment]
You should be able to get a new version of the mod [here](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/2811488) that fixes this issue. Thanks for reporting it!
