### ISSUE TITLE
graphical error with void thaumatage's hood

### ISSUE THREAD

**Issue by Zeinoth** [TheCodex6824/ThaumicAugmentation#51]
https://cdn.discordapp.com/attachments/337734764461162498/638964791880318977/latest.log in this log, it says something about a client error. The whole screen goes black a split second after logging in, and i cant see anything, even in the escape menu.

**Comment by TheCodex6824** [comment]
You're using an old version (1.1.9), this was an incompatibility with Optifine that was fixed in 1.1.11.
