### ISSUE TITLE
Crash with Mine Trading Cards Open Source

### ISSUE THREAD

**Issue by ireece1** [TheCodex6824/ThaumicAugmentation#52]
Game won't start with Mine Trading Cards and Thaumic Augmentation in the same pack; VanillaFix blames TA.

https://paste.dimdev.org/uzotizudut.mccrash

**Comment by Powerthegreat** [comment]
This is an issue with hasCapability on the binder in MTC, fixing now

**Comment by Powerthegreat** [comment]
Fixed with https://github.com/Powerthegreat/Mine-Trading-Cards-Source-1.12.2/commit/3789b59b9656b4551a02b3325890682c03431837, this issue can be closed

**Comment by TheCodex6824** [comment]
Thanks for figuring this out so quickly :)
