### ISSUE TITLE
Issue with ladders

### ISSUE THREAD

**Issue by Elphoenix** [TheCodex6824/ThaumicAugmentation#53]
Hey, bit of a bug here, sadly. I was using Thaumic Augmentation all fine for a long while, no bugs at all, but then this happened:

I was going down a ladder, in a vertical tunnel of white glass all warded with the Warding Focus, and switched to hold the gauntlet (with the Warding Focus as active). The game froze and crashed, and from what I gathered with my very limited knowledge from this crash report, it has something to do with the position of cursor. Crash report available below:

[crash-2019-11-23_22.53.38-client.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/3883106/crash-2019-11-23_22.53.38-client.txt)

Hope this helps! (and gets fixed soon, really really like everything about this mod)

**Comment by TheCodex6824** [comment]
I was able to fix this really quickly, an update with the fix should be available [here](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/2831667l) once it gets approved. Thanks again for reporting!
