### ISSUE TITLE
Primal Cutter Config

### ISSUE THREAD

**Issue by BoyarRex** [TheCodex6824/ThaumicAugmentation#55]
While it is as expensive as the Crusher, the Cutter receiving 12 damage and greater sapping on top of all the combined effects makes it a bit too effective.
 Couldn't find the damage/speed values to edit, it'd be good for modpacks and such if you implemented a few config options for it, primarily attack speed and damage.

**Comment by TheCodex6824** [comment]
I'll add config options for the 1.2 update, which I'm working on the last few parts of. I might also nerf the Primal Cutter's damage a bit, as you make a good point that the damage + greater sapping is quite a lot better than the Primal Crusher. I added more damage as the cutter has less utility as a tool than the crusher, but 12 damage might be a bit too high.

**Comment by TheCodex6824** [comment]
This should be in the latest update.
