### ISSUE TITLE
[Bug][v1.12.2-1.1.13] Thaumium Caster's Gauntlet loses NBT when leaving End

### ISSUE THREAD

**Issue by Shazuli** [TheCodex6824/ThaumicAugmentation#58]
***Hi***

I had some modifiers on the Gauntlet when I entered the End to beat the Dragon. When I respawned afterwards I noticed all the Augmentations were gone but the Foci I had selected was still there.

**Comment by TheCodex6824** [comment]
This may sound like a weird question, but were you in creative mode during your fight and/or when you came back?

**Comment by Shazuli** [comment]
Umm, no. I was playing in survival the whole time. On further testing it doesn't seem to happen anymore, it only happened once when I had beaten The End the first time.

**Comment by TheCodex6824** [comment]
The only other question I could ask then is if you were on a server, as I just gave it a try and it seemed ok for me.

Either way, the next update will massively improve NBT/Capability reliability on dedicated servers, so things like this hopefully won't be an issue anymore.

**Comment by Shazuli** [comment]
I was in single player, and the modlist is:
* Thaumcraft (6.1.BETA26)
* Thaumic Augmentation (latest I as of when I opened this issue)
* The Betweenlands (3.5.6)
* JEI (4.15.0.291)

**Comment by TheCodex6824** [comment]
So I just pushed an update with all of the NBT fixes. Since it's much more reliable now than it used to be I'm going to close this, but if it happens again you can leave another comment / reopen this and I'll take another look.
