### ISSUE TITLE
[SUGGESTION] Ancient Stone + extended "The Empty" lore and devices

### ISSUE THREAD

**Issue by Shazuli** [TheCodex6824/ThaumicAugmentation#59]
***Hi***

I like that you've allowed for a way to get Eldritch Stone which normally is inaccessible right now. You *could* add a research for crafting Ancient Stone, but that doesn't really make sense. New Ancient Stone? My suggestion is to add ruins in the Empty dimension with parts having Ancient Stone and its sub-types. Lore wise could be along the lines of; Thaumaturges in the past who dwelled upon the same research as you but tried to open it by force where the time-and-space were not weak. They put way too much power into it and *sucked* them and their entire base along with them before it closed itself and stranded them there.
These *failed* attempts can probably be a continued research tree of "Entering the Emptiness" where you can learn to maybe make new devices and augments and follow the dairy of a lost Thaumaturge. As the story progress, you see him lose his sanity over time trapped there in the darkness searching for a way out while hiding from Eldritch Guardians and fighting Taint creatures.
These attempts are re-invented by you and put in practical uses such as Augmentations, Arcane devices and Foci Mediums, for weapons and dimensional manipulation. One of them could be a Bauble or Chestplate Item called "Personal Stabilizer" or something along those lines. Have you read the story of [SCP-3001 (Red Reality)](http://www.scp-wiki.net/scp-3001)? It's about a scientist who gets trapped in a "non-dimension" with no way out where he slowly becomes less "real". It would be pretty neat with a similar concept of any living thing entering slowly becoming less real over time until they fade into nothing. A Personal Stabilizer will prevent this if charged with Vis, it would be pretty neat if it had a render on the player.

I could go on forever, but I noticed the wall of text so I decided to stop there. :P

**Comment by TechnoMysterio** [comment]
While not exactly the same as what you've just written, we are already working on additional world-gen for the Emptiness which uses Ancient Stone, but I'll hold off on the details for spoiler reasons.

It might be a while before that's all implemented, however, so if you need a way to get Ancient Stone right now, a different Thaumcraft 6 addon was recently uploaded to CurseForge called Crimson Revelations, which adds a recipe for it.

**Comment by Shazuli** [comment]
A bit out of context here, but what's the scale of the Emptiness? The Nether is 1:8 and Overworld is 1:1.

**Comment by TechnoMysterio** [comment]
The movement factor is 1:16 in the Emptiness by default, but can be changed in the config.

**Comment by TheCodex6824** [comment]
It's been summarized above, but we are adding structures to the Emptiness that will have more than enough ancient stone for building / infusion purposes. There *might* be a crafting recipe if it makes sense to do so, but I'm not sure if that will happen, especially since there is another addon that adds a recipe already.

I do hope to get some structures out with the alpha version of 1.2 when that's finished, while it's not done yet good progress is being made.

**Comment by TheCodex6824** [comment]
As promised, the new structure has what should be more than enough ancient stone for anyone that needs it.
