### ISSUE TITLE
seal copier doesn't copy all settings on server (Thaumic Augmentation 1.1.14)

### ISSUE THREAD

**Issue by jdratlif** [TheCodex6824/ThaumicAugmentation#61]
Thanks for the quick fix on getting the seal copier not to crash on servers, but there is another issue with the copier. It still doesn't quite work. It copies some settings, but others aren't quite working.

Example: I have a use seal for a tree farm. I set the item to a sapling with a whitelist. I set click empty air and request provisioning from whitelist. I change the color. Copy this seal to a freshly placed use seal. I see no color change. If I go edit the settings with the bell, some of them were copied, others were not. The sapling is in the item slot, but it's still a blacklist. The empty air and request provisioning settings are still false. The color is right, and when I leave the interface now, I see the color reflected in the world.

It still works fine in single player.

I made a video showing the exact problem I'm seeing with the most basic mod pack possible (Forge, JEI, Thaumcraft 6 BETA 26, and Thaumic Augmentation 1.1.4) on a brand new world in both single player (where it works so you can see what I expect) and on the server to demonstrate the problem.

http://games.technoplaza.net/minecraft/ta114/ta-seal_copier_issue.mp4

Thanks.

**Comment by TheCodex6824** [comment]
There should be another update that actually fixes it [here](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/2880368) once it gets approved. Hopefully this time everything is actually working.

**Comment by jdratlif** [comment]
Thanks. I'll test it out when I get home.

I love golems, but the repetitive motion of clicking all the seals really hurts my hand, so I was so happy to find a mod that added something like this.

Glad the video helps. I know how hard it can be to convey a problem with just text, especially when at a glance, it looks like it's working. I appreciate that you do all this for free, so if I can save you some time on tracking down an issue, it's just easier all around.

**Comment by jdratlif** [comment]
I've only done one test so far, but it works as far as I can tell. The problem I had with copying the use seal is gone now.

Thanks.

**Comment by TheCodex6824** [comment]
Since it seems to be working now I'm going to close this, but if you encounter any more issues with it you can leave a comment here and I'll reopen it and take another look.
