### ISSUE TITLE
Primal Cutter function cannot seem to be swapped on a crafting table

### ISSUE THREAD

**Issue by DoomRater** [TheCodex6824/ThaumicAugmentation#62]
I tried with v14, saw it wasn't working, checked to see there was an update 2 days ago for fixing the seals and.... after downloading v15, tried putting the primal cutter in a 2x2 crafting grid to no effect.  Mind it was taken from JEI rather than created on an infusion table, but the research is unlocked in the testing world I tried this in and nothing occurred.

**Comment by TheCodex6824** [comment]
Well this is a bit awkward, looks like when I copied over that change from the newer version I'm working on I forgot to copy the recipe... I'll have an update out soon.

**Comment by TheCodex6824** [comment]
There should be another update [here](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/2881949) once it gets approved. Thanks for letting me know about this!

**Comment by DoomRater** [comment]
Confirmed working now.  Thanks a bunch!
