### ISSUE TITLE
Silk Touch Exchange focus not silk touching blocks when replacing them in Voidseer Caster's Gauntlet

### ISSUE THREAD

**Issue by DoomRater** [TheCodex6824/ThaumicAugmentation#63]
What's odd about this is at first I thought it might be an augment, but then I tried my Silk Touch Breaking Focus and that silk touched blocks just fine, with or without augments.  This seems to happen regardless of which hand the gauntlet is in.

Edit: The Thaumium Caster's Gauntlet seems to suffer from this too.

**Comment by TheCodex6824** [comment]
[This](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/2882356) should fix it, feel free to keep the bug reports coming :)
