### ISSUE TITLE
Issues from a Reddit Post

### ISSUE THREAD

**Issue by TechnoMysterio** [TheCodex6824/ThaumicAugmentation#7]
I noticed this post on the FTB Subreddit that mentioned your addon, saying that it has some bugs:
https://old.reddit.com/r/feedthebeast/comments/bk08vt/im_working_on_a_modpack_with_thaumcraft_as_a_core/

It's not particularly clear as to what it's getting at, but I did some testing to see what was wrong.

The biggest problem it points out is that once you place a warded object, whether a chest or door, you cannot remove it. Not by breaking, not by shift-right-clicking the object (which just opens the chest/door), outside of creative mode I cannot remove that object at all.

Secondly, as for what it says about 'the light creation focus is borked', I've no idea what that means, but I think the post-maker may be running an older version of the addon where the light was still temporary.

While I'm here, did you get my Discord DMs with the art I've been working on? I redid the Warded Chest and worked on some other stuff too.

**Comment by TheCodex6824** [comment]
Thank you for making me aware of that post, I'll be fixing the warded object issue (and give the light focus another try soon). As for the stuff on discord, I've been super busy with finals this week so I haven't really gotten much time to work on the mod, but after today things will slow down for me so I'll be more active.

**Comment by TechnoMysterio** [comment]
The bit in the book on keys is a little unclear as well, where the iron key part implies that you right-click on a warded object with it to bind it to that object, so you might wanna tweak that bit as well. Also, let me know on Discord when you get the art assets I did.

**Comment by TheCodex6824** [comment]
As I addressed the issue with the Thaumonomicon entries being unclear, and the light focus issue probably just the fact that they disappeared in the update where they were introduced, I'm going to go ahead and close this. If the light focus is still an issue mechanically, I'll reopen this.
