### ISSUE TITLE
Chunks not unloading

### ISSUE THREAD

**Issue by Flemmli97** [TheCodex6824/ThaumicAugmentation#70]
Version: ThaumicAugmentation-1.12.2-1.1.17
Forge: 1.12.2-14.23.5.2847

Every chunk thats been loaded does not get unloaded again.
How to test: 
Setup repeating command block with e.g. "say loaded" and fly away.
normally if you fly away out of render distance the command block stops but instead its still going meaning the chunk is also still loaded.

Installed mods are only thaumcraft, baubles and thaumic augmentation

**Comment by TheCodex6824** [comment]
By "every chunk", have you tried many that are far away from each other? I just ask because if you tried just once you may have picked the spawn chunk, which IIRC stays loaded all the time. Either way, I'll probably check on this later today.

**Comment by Flemmli97** [comment]
tested same world same place and setup. no mods (or only thaumcraft) when i flew away the command block stopped

**Comment by TheCodex6824** [comment]
https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/2962468
