### ISSUE TITLE
Crashing when loading world

### ISSUE THREAD

**Issue by NobleGaming** [TheCodex6824/ThaumicAugmentation#73]
After downloading v2.0, I've been unable to load into a world without crashing.
[crash-2020-07-26_17.52.46-client.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/4978900/crash-2020-07-26_17.52.46-client.txt)

**Comment by TheCodex6824** [comment]
The crash log you gave me shows the game crashing in something ASMC is doing. However, I just booted up a pack with my mod and ASMC and everything worked fine, so something odd is happening.

**Comment by NobleGaming** [comment]
Nope, it's still crashing after I disabled the coremod. Also, it was originally crashing and was saying it had something to do with Better Diving so I removed that and it was still crashing and that's when I sent that log where it said it had something to do with ASMC, which I also removed and it still crashed. I guess I'm just gonna have to do the good ol' add 10 mods at a time until it crashes.

**Comment by TheCodex6824** [comment]
This is going to sound weird, but I think the problems are that the "Disable coremod" toggle doesn't work, and my coremod conflicts with colytra. Removing that might work for now, but either way there will be a hotfix ASAP.

**Comment by NobleGaming** [comment]
So I didn't get very far because I just loaded it with Baubles, Thaumcraft, and Thaum Augmentation and it's crashing
[crash-2020-07-26_20.26.30-client.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/4979354/crash-2020-07-26_20.26.30-client.txt)

**Comment by lag42** [comment]
i also got the crash with just thaumic augmentations and it's dependencies https://gist.github.com/lag42/5a49af235e19149095dcda440a1d5162 
specific versions: 
baubles: 1.12-1.5.2
thaumcraft: 1.12.2-6.1.BETA26
thaumic augmentation: 1.12.2-2.0.0

**Comment by TheCodex6824** [comment]
Yeah that's a different crash that was just me being stupid, I'm in the process of getting a hotfix ready to publish to Curse

**Comment by TheCodex6824** [comment]
Once it's done processing / approved the hotfix is [here](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/3015785). Sorry for the trouble everyone!
