### ISSUE TITLE
Game Hangs on Startup

### ISSUE THREAD

**Issue by ScienceDrummer** [TheCodex6824/ThaumicAugmentation#74]
Log: https://hastebin.com/tihohuvaci.md
Mod Version: 2.0.1
Forge Version: 14.23.5.2854

**Comment by TheCodex6824** [comment]
There is certainly a mod in there that is causing a conflict, but I can't determine what it is from the log. Unless you can narrow it down by removing mods until there is just the culprits, there isn't much I can do at the moment.

**Comment by ScienceDrummer** [comment]
I found that the issue was between this mod and an unreleased 1.12.2 mod called PlayerAPI which is used for SmartMoving mod.

**Comment by TheCodex6824** [comment]
That would explain why I had no luck figuring it out. Seems like there's multiple versions of PlayerAPI floating around the internet, are you using the [Player API 2019](https://www.curseforge.com/minecraft/mc-mods/playerapi2019/) one?

**Comment by ScienceDrummer** [comment]
Oh I see you fixed it, but just to make sure, it was this version I was using
[PlayerAPI.zip](https://github.com/TheCodex6824/ThaumicAugmentation/files/5471378/PlayerAPI.zip)
