### ISSUE TITLE
Urns walk sound

### ISSUE THREAD

**Issue by SSKirillSS** [TheCodex6824/ThaumicAugmentation#76]
Rn urn walk sound hears like urn break sound. It's a bit weird =\

Thaumcraft-1.12.2-6.1.BETA26
ThaumicAugmentation-1.12.2-2.0.2

**Comment by SSKirillSS** [comment]
Also mining-tool for urns sometimes works weird. I can't break urns and crystals with ChaosStaff from DraconicAdditions D:

**Comment by TheCodex6824** [comment]
So the sound I can't really do anything about, TC only has a single sound for urns and it also uses it for both breaking and walking. As for the tool thing, I don't want to require people to use a pickaxe to get the drops, so I can't assign it as the tool. However, I did make breaking urns and crystals a bit faster, so hopefully that helps.
