### ISSUE TITLE
Mod Incompatibility 

### ISSUE THREAD

**Issue by FriesBeforeGuyz** [TheCodex6824/ThaumicAugmentation#77]
I don't know if this is the right place to put this. If it isn't, my apologies!

I've played with this mod before, the modpack mentioned was made slowly by adding mods little by little, just to make sure there weren't many problems. (it's not as "little" anymore tbh)

I decided to add Thaumic Augmentation (and a few other Thaumcraft mods) to a modpack that me and my friends made/use. 
As soon as I added the mods, the game started crashing, saying that Galacticraft Core was the issue. 
(I have Vanilla Fix which says what [Most Likely] causes the crash).

Galacticraft was working perfectly before adding the Thaum mods. 
I found that Thaumic Augmentation and Thaumic Additions: Reconstructed were the only mods that were causing problems; (each causing there own respective problem). There are 4 other Thaum mods that work just fine.

I suppose what I'm reporting is a mod incompatibility with Galacticraft Core.

Here is the Crash Report:
[crash-2020-07-28_11.28.49-client.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/4989375/crash-2020-07-28_11.28.49-client.txt)

Apologies if the mistake is something on my end! 

-FriesBeforeGuyz

Edit: I just realized, this problem could be on Galacticraft's end. (Pretty dumb of me not to think of that, sorry!). If it is, I'll make a bug report with them as well. I might make a bug report with them regardless right now. Sorry again for the trouble!

**Comment by SSKirillSS** [comment]
You just installed to many mods and reached IDs limit. Remove some useless mod.

**Comment by FriesBeforeGuyz** [comment]
Oof, I'm an idiot. Thank you for your time and I'm sorry for waisting it!

**Comment by SSKirillSS** [comment]
No problem. If your issue was resolved - please, close it.

**Comment by TechnoMysterio** [comment]
If you need to go beyond the ID limit, then it might be worth looking into mods such as JustEnoughIDs on CurseForge, they might be able to help you.

**Comment by TheCodex6824** [comment]
As everyone else said, it was just an ID limit issue, not really a problem with any individual mod. JustEnoughIDs is helpful for this, but keep in mind you can't remove it once it is used on a world.
