### ISSUE TITLE
Random server crash

### ISSUE THREAD

**Issue by SSKirillSS** [TheCodex6824/ThaumicAugmentation#78]
Idk what can cause this issue. I just stay afk and server is simply crashes.

Crash-Log: https://pastebin.com/tHzhp5vj
Thing from logs before crash: https://pastebin.com/iVrxLuFS
My config: https://pastebin.com/1tYdWwBk

Thaumcraft-1.12.2-6.1.BETA26
ThaumicAugmentation-1.12.2-2.0.2
Mohist-1.12.2-310ebdb-server

**Comment by SSKirillSS** [comment]
Looks like I found problem. If I do something like this:

```    fracturedimlist {
        I:-1=0
        I:0=0
        I:1=100
        I:111=0
        I:17=0
        I:20=0
        I:33=0
        I:66=0
        I:7=0
    }```

Server just crashes. But.. Idk how to allow fractures only for DIM1 in other way

**Comment by TheCodex6824** [comment]
Unfortunately there are two bugs here:

- The fracture code should just exclude dimensions if they are 0, but it tries to do stuff instead. Normally you can just remove the dimension, but...
- The code that populates the default list ends up running every time, not just for an empty list

So yeah, I'll be fixing these later. Thank you for reporting them

**Comment by TheCodex6824** [comment]
https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/3019140
