### ISSUE TITLE
Way to create fractures

### ISSUE THREAD

**Issue by SSKirillSS** [TheCodex6824/ThaumicAugmentation#79]
P.S. - I don't found mod discord, so, I just ask it here.

I'm using skyblock-styled server, so, I can't explore world due a limited island size. Is there a way to create fractures without finding it in a world?

**Comment by TheCodex6824** [comment]
If you have cheats on / are on a multiplayer server, there is the thaumicaugmentation makefracture command. The syntax for it is: /thaumicaugmentation makefracture x1 y1 z1 dim1 x2 y2 z2 dim2, where the xyz coords are for the locations of the linked fractures, and dim1/2 are the dimension ids. In normal cases, the dimension ID for the overworld is 0 and the Emptiness dimension ID is 14676.

**Comment by SSKirillSS** [comment]
Interesting, but, looks like I need more complicated way, cuz player can use cheat-commands.

**Comment by isaaachipkiss** [comment]
No Idea how to use this command, even still the mod has issues with generating fractures and I have yet to get it to work.

**Comment by TheCodex6824** [comment]
> No Idea how to use this command, even still the mod has issues with generating fractures and I have yet to get it to work.

With cheats on / op privileges, enter:
`/ta makefracture x1 y1 z1 dim1 x2 y2 z2 dim2`
Where x1,y1,z1,dim1 are the coordinates and dimension ID of where one fracture should be, and the others for the second fracture. 

Example:
`/ta makefracture 0 64 0 1 0 64 0 0`
would make fractures linked to each other at (0, 64, 0) in the end and (0, 64, 0) in the overworld.

As for issues, are you just having trouble finding them or are they actually broken? Other than their rarity, the only issue I know of is them having trouble spawning with Cubic Chunks, but last time I checked there's wasn't anything I could do about that.
