### ISSUE TITLE
Feedback and Thoughts from 1.0.6

### ISSUE THREAD

**Issue by TechnoMysterio** [TheCodex6824/ThaumicAugmentation#8]
Did some further testing, figured I'd put the issues/suggestions here for the sake of convenience.

- New light effects are good, but the central item still really needs to be a particle effect instead of a block. Also, the new effects tend to drift away from the centre a bit too far, maybe keep them a little more constrained to the middle.
- Rift seeds can spawn rifts right next to each other, which is something that base Thaumcraft tries to avoid, and even other addons. Probably doesn't matter too much if you're eventually gonna move onto the other ideas we discussed, but it's worth thinking about at least.
- Warded Chest animation is stiff and prone to jittering around. Could you perhaps nick code from the Hungry Chest to improve the animation, since that works pretty well?
- Thaumium Gauntlet starting colour is a bit off, the blue doesn't work well with the purple Thaumium stuff. I'd suggest that you'd make it look more like the Enchanted Fabric Robes texture. I managed to get this kind of colour in-game with purple and magenta dye.
- Arcane Doors of both kinds don't work with Quark's double door opening feature, which is slightly annoying. I also need to improve the side of the wood door a little, to make it fully brass, so I'll do that for you at some point.
- Some suggestion for new warded blocks. I already mentioned warded glass for decorative purposes, but perhaps also warded trapdoors, for wood and thaumium? Shouldn't be too tricky to whip up a texture for these.
- Some thoughts regarding getting primordial pearls. I understand that getting these in base TC is very annoying, especially since the end-game wasn't properly implemented before it was handed off to KingLemming, so there needs to be a better way to get them. Blowing up rift after rift just isn't a fun way to get them, and making loads of rift seeds just makes that even more of a chore. As such, an idea I just thought of: a device that increases the chances of getting a pearl when blowing up rifts. It'd probably take the six primal essentia types, shoot energy into a rift and when blowing it up it'd be much more likely to drop a pearl. It'd probably work better with larger rifts. It should probably have downsides, however, like making the rift unstable or causing nasty effects directly, perhaps if not regularly supplied essentia. It'd work well with the other rift management tool ideas we talked about, and it'd probably be a little more interesting than just making lots of rift seeds and blowing them all up.

**Comment by TheCodex6824** [comment]
As usual, thank you for the feedback :)

- I plan on replacing the light model to be a sphere of particles, the current particles were more of an experiment with it (and the particle drift just needs to be turned down a bit)
- I should probably prevent multiple rifts spawning in a single chunk, at least to keep things the same as base TC
- I'm working on making the animations less jittery on transitions
- I didn't know what purple color to use for the gauntlet to make it look good with the already purple thaumium bits, I just need to give it a try
- I'll look into the issue with Quark (no promises though, since I have to do special things to check permission for the warding part)
- I agree, trapdoors would be a nice addition
- Once I get around to implementing some rift manipulation machines, I will probably add a primordial pearl helper machine like you described

**Comment by TechnoMysterio** [comment]
- Multiple rifts can get weird when they're close together, so that'd be good for a quick fix until the fancier stuff is done.
- The animations are jittery, but also not as smooth as a normal chest's. There's probably some code from Hungry Chests you can nick somewhere to make them a bit smoother, maybe something that just repurposes vanilla stuff.
- As I recall the Thaumaturge's Robes can be dyed, like the Void Robes. If you can figure out what the base colour of the Thaumaturge's Robes are, maybe you can use that as a basis for the Thaumium Gauntlet, same for the Void Gauntlet/Void Robes if that hasn't already been done.
- Double door opening could be it's own feature of course, mentioning it in the book that that's a bonus the doors have.
- Some things to consider for the pearl helper device: for base TC it should probably need the pearl research to discover but not need a pearl to make, and if my dubious plans for another addon ever come into action then perhaps that research could require a more end-game Eldritch research instead, so that getting pearls is tricky to start with but gets easier as you progress.
- We should discuss the rift manipulation stuff a bit more perhaps, maybe consider what the models should look like or what particular gameplay quirks they could have. I'll be busy throughout the month, but hobby stuff does break up the tedium of work nicely at least.

**Comment by TheCodex6824** [comment]
Just a progress checklist for me:

- [ ] Light model
- [ ] Rift seed spawning
- [ ] Animations
- [ ] Gauntlet color
- [ ] Double door opening
- [ ] Trapdoors

Rift manipulation is in the pipeline, not sure when it will be done however.

**Comment by TechnoMysterio** [comment]
I've sent you some Warded Trapdoor textures in Discord DMs, just to let you know.
