### ISSUE TITLE
Construct's Armory Texture Issue

### ISSUE THREAD

**Issue by Lucky-Red** [TheCodex6824/ThaumicAugmentation#80]
Upon updating to version 2.0.2, any modular armor from the Construct's Armory mod loses its material textures, appearing as plain white armor.
![image](https://user-images.githubusercontent.com/68577998/88751211-fc8a7800-d10b-11ea-948f-880378dc8aaa.png)

**Comment by TheCodex6824** [comment]
https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/3019140
