### ISSUE TITLE
"Stucking" in fracture

### ISSUE THREAD

**Issue by SSKirillSS** [TheCodex6824/ThaumicAugmentation#81]
After teleporting through fracture I just can't leave it. If I stop colliding with fracture entity - it trying to teleport me back, that cause a lot of issues with plugins. So, if I go away from fracture bounding box, it teleport me to default world with bugged sky and world rendering.
Video-demo: https://www.youtube.com/watch?v=_nARKEyq6FA

Also want to notice that this issue was already fixed, as I remember.

Thaumcraft-1.12.2-6.1.BETA26
ThaumicAugmentation-1.12.2-2.0.2
Mohist-1.12.2-310ebdb-server

**Comment by TheCodex6824** [comment]
Well, I've never seen this one before. I'll look into it to see if I messed something up, although I wonder if its a plugin causing issues.

**Comment by SSKirillSS** [comment]
New video-demo: https://www.youtube.com/watch?v=NvVKT4pfSrE

**Comment by TheCodex6824** [comment]
So the fix for getting stuck in fractures is in the latest version. Since the other issues are due to bukkit-based servers not dealing with changing dimensions properly, I'm going to close this.
