### ISSUE TITLE
New gauntlet xp augment config scaling issue

### ISSUE THREAD

**Issue by Ridley11** [TheCodex6824/ThaumicAugmentation#84]
Since the addition of the config settings to change the scaling of the xp augment, the augment seems to be at it's maximum as long as the player has 1 level. 
The setting in question is the ExperienceModifierCap, which I tested with both the default 2.0 and also larger numbers, it automatically will be at the max it can climb to instead of detecting how much xp the player actually has.

**Comment by TheCodex6824** [comment]
Should be fixed [here](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/3020883).
