### ISSUE TITLE
Possible bug with Thaumostatic Harness Achievement (be lifted into the air by an external force.)

### ISSUE THREAD

**Issue by Lightone** [TheCodex6824/ThaumicAugmentation#87]
Forge 1.12.2-14.23.5.2854
Thaumcraft 1.12.2-6.1 Beta 26
ThaumicAugmentation-1.12.2-2.0.4

i try do a few thing in my survival with the object and weapon and monster has the capability lift you in the air and nothing happened:

Arcane Levitator (setup 32 block)
Cloud Stepper Ring
Sword of the Zephyr
Boots of the Traveller

And other way:

Creeper
Villager Golem
TNT
Arcane Grappler

Nothing happend

**Comment by TheCodex6824** [comment]
The trigger for it is the levitation potion effect, but the description is a bit generic and I could see how any of those other things could apply. I'll have to think about a better way to word it and/or add some extra things in that also fulfill the requirement.

**Comment by TheCodex6824** [comment]
I made the description much clearer in the [latest update](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/3023506).
