### ISSUE TITLE
Eldritch Guardians stay permanently after dying right next to the boss pillar

### ISSUE THREAD

**Issue by EnderdragonLord** [TheCodex6824/ThaumicAugmentation#88]
![2020-08-03_01 08 37](https://user-images.githubusercontent.com/58011699/89151199-035b2580-d526-11ea-88c2-a56ba6604b2d.png)
Seems like right after they die while being close to it, they stay stuck and heal forever.

Only way to then get rid of them is to simply change to Peaceful which forces them to despawn.

**Comment by TheCodex6824** [comment]
It should be fixed in the [latest update](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/3023506), hopefully the Eldritch Guardians aren't immortal anymore.

**Comment by Vapaman** [comment]
You might want to reopen this issue, it still happens in the latest release for eldritch guardians from augmentation and vanilla tc.
![2021-08-13_19 54 48](https://user-images.githubusercontent.com/77460466/129393518-88d298db-021c-47d9-b809-ca94f322a644.png)
