### ISSUE TITLE
Cannot craft Elemental Augment Base

### ISSUE THREAD

**Issue by TheQuantumRuby** [TheCodex6824/ThaumicAugmentation#89]
Hi, I cannot craft the elemental augment's base (IE the part without the power/vis/speed crystal), even with the recipe found in the source code (thaumium plate, vis crystal, and a vis resonator), and was wondering if this was a bug or if I was reading the recipe incorrectly. Either way, could you possibly add a dummy recipe to JEI for it, like the other modular bases? Perhaps use a 'blank' vis crystal like the Arcane Stone recipe from vanilla Thaumcraft.

**Comment by TechnoMysterio** [comment]
Looks like an oversight there, we probably missed something with the elemental augment when the other augments were being added/organized.

**Comment by TheCodex6824** [comment]
Fixed [here](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/3023506), sorry about that!
