### ISSUE TITLE
Casting animation

### ISSUE THREAD

**Issue by shoverno2** [TheCodex6824/ThaumicAugmentation#9]
Just looked at player, when he casting...
Well, casting animation not bad, couse there's no this animation)))
this looks like player make spells from his mouth)))
So, why no to add cast animation?
This pretty simple, couse it's animation of bow.
This will be much better, then cast spells from head))
...
Also, i know that maybe you cant modify vanilla gauntlet, but can you make cast animation at least for your new gauntlets?

**Comment by TheCodex6824** [comment]
If by "bow animation" you mean the player holding their arm out when drawing it back, I can probably make something similar to that for my gauntlets. I'm not planning on modifying the vanilla gauntlet, as I don't want to break anything else that does similar things to it.
