### ISSUE TITLE
Terraformer issues

### ISSUE THREAD

**Issue by Ridley11** [TheCodex6824/ThaumicAugmentation#90]
Having trouble getting the arcane terraformer to do it's thing. Gave a longer description of my setup in the comments section. However it's all set up and areas are chunk loaded, but right clicking the terraformer with my gauntlet only briefly has any effect, makes the start-up sound and the impetus beam grows wide, but then stops and doesn't seem to do anything. Also doesn't take any vis essentia from the jars, though I hear the pipes make their rumbling noise. The charged Impetus Cells also do not diminish at all, which are within render distance nearby so are loaded and not an issue with the chunk loader. I have tried other biomes too, same issue. I will add that other impetus powered things work fine, like the void recharge pedestal I can recharge my impetus items on that using the same setup no problem.

Below is my whole setup, from the source of my impetus power currently, a huge rift, to the matrix with 3 impetus cells fully charged, and then to where my terraformer is currently set up. The aura is over 100 in the chunk of the terraformer. The focus is set to the Extreme Hills Biome and I'm currently in the biomes o plenty Grove biome, if that matters at all.

![2020-08-10_20 16 48](https://user-images.githubusercontent.com/32041768/89776163-7e38c780-db48-11ea-88ad-7d9b79ecd386.png)
![2020-08-10_20 14 49](https://user-images.githubusercontent.com/32041768/89776168-809b2180-db48-11ea-833f-3c0d6a8d64a2.png)
![2020-08-10_20 15 07](https://user-images.githubusercontent.com/32041768/89776170-8133b800-db48-11ea-9bac-dabd020304de.png)
![2020-08-10_20 15 20](https://user-images.githubusercontent.com/32041768/89776174-81cc4e80-db48-11ea-8d12-9b5adcb762d7.png)

**Comment by TechnoMysterio** [comment]
Few extra questions for you: firstly, when using an essentia resonator on the terraformer's different sides, what values do you get? Secondly, are the impetus beams all flowing in the right direction? And finally, what other mods do you have installed?

**Comment by Ridley11** [comment]
I checked through the things you said. I got it working in the end but tbh I'm not sure how, I just took it all apart and set it up again and its working, so I guess maybe a beam was going the wrong way, though I didn't notice when I checked over them. 

Thanks :)
