### ISSUE TITLE
Certain particles/effect from this mod cause other mods' particles to render in white

### ISSUE THREAD

**Issue by SeriousCreeper** [TheCodex6824/ThaumicAugmentation#91]
Heya,

i noticed that certain effects and particles of this mod will render other mods particles in white (even if they were originaly in color). 

Here is a quick video of demonstrating the issue: https://streamable.com/josz8e 

The other particles in this are from Roots and Embers Rekindled.

Using Thaumic Augmentation 2.0.5

**Comment by TheCodex6824** [comment]
Normally it would probably be a TC issue, but all of those particles are mine, so it is indeed an issue in TA. I haven't had a chance to look into this yet (very busy with school), but I have a feeling I know what this is

**Comment by SeriousCreeper** [comment]
Thanks a bunch! :D

**Comment by TheCodex6824** [comment]
In case you were waiting for a proper update, the fix is in [here](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/3057908)
