### ISSUE TITLE
Metaspatial extruder with empty reinforced jar will release flux rift

### ISSUE THREAD

**Issue by Dawnwalker666** [TheCodex6824/ThaumicAugmentation#94]
When using an empty **reinforced jar** with **metaspatial extruder**, it will release a flux rift . And it is the most largest rift that I have ever seen.

Version: ThaumicAugmentation-1.12.2-2.0.7
(Maybe the previous version also has this problem. )

![02](https://user-images.githubusercontent.com/49862610/93660095-2150fb00-fa7e-11ea-8385-1b9183359e0a.gif)
When this GIF was recorded, the metaspatial extruder was still running.

![001](https://user-images.githubusercontent.com/49862610/93660156-91f81780-fa7e-11ea-9bbb-73eeb67b8ccf.png)
STILL RUNNING.

![002](https://user-images.githubusercontent.com/49862610/93660171-b94ee480-fa7e-11ea-9ddf-df37dc144a4e.png)
The empty jar

When the flux rift disappears due to stability, metaspatial extruder will still continue to work, and then continue to play the working animation.(Purple lightning and black smoke)

**Comment by Dawnwalker666** [comment]
Another thing worth paying attention to is that this device can release multiple flux rifts in a chunk. This can cause a variety of weird things to happen.

**Comment by TheCodex6824** [comment]
The update with the fixes will be [here](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/3061434) once it gets approved. You probably want to update or break the machine ASAP, as that rift will grow forever in the old version...
