### ISSUE TITLE
(Minor suggestion) Biome colors for TA's custom biomes

### ISSUE THREAD

**Issue by Hyxaru** [TheCodex6824/ThaumicAugmentation#95]
Hey, really enjoying your mod currently. I just found out the updates after version 19 which added the spires, I got soo much to explore!

I noticed that TA (re)adds the tainted lands biome. However, the natural overworld fractures that spawned in the emptiness dimension within one of the tainted lands biomes all seemed to have such vivid green grass.

Would it be possible to get the purple biome hue back as it were in previous thaumcraft versions?

There was once a moment in TC5 gameplay I made a custom biome with it, letting tainted blocks grow over a safe platform high up in the sky to change the biome. Then destroyed it without letting the taint wither from blooms or shortage of flux. This retained the biome without having any of the nasty corruption affecting the biome I made below.

**Comment by TheCodex6824** [comment]
Yeah it seems like I forgot to change the grass color specifically, water and such are already there. Should be easy enough to change though.

**Comment by TheCodex6824** [comment]
Update with this is out [here](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/3089750).
