### ISSUE TITLE
Game crash when attempting to use a Fracture (Likely Cubic Chunks interaction)

### ISSUE THREAD

**Issue by Hyxaru** [TheCodex6824/ThaumicAugmentation#96]
To my excitement, it seems I got atleast one fracture so far to link up to the emptiness within a Cubic Chunks world (also the first one I tried so far).

In using it however, I receive the following crash. Would you perhaps be able to see on what end the issue occurs, and if it's worth fixing?

Sincerely,
Hyxaru
[crash-2020-09-22_21.48.42-server.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/5267722/crash-2020-09-22_21.48.42-server.txt)

**Comment by TheCodex6824** [comment]
Can you post your debug.log (redacting any information from it as needed)? It might have some extra information for me about what the fracture was trying to do.

**Comment by Hyxaru** [comment]
It appears it was indeed connected to dim4, a non existent dimension. A leftover from some meddling I did in the config a long time ago. Since the mod updated, I went through the configuration again. I thought the config had entirely refreshed due to new entries, but apparently not.

**Comment by Hyxaru** [comment]
I have no idea which supposed old version of CC did allow me to travel through fractures btw. I am not entirely sure if it ever did. The links are always invalid.

If I manually change the nbt data of a fracture to linkinvalid:0, and have the last configuration entry set to true so that they ignore checking again, it should work right? Although who knows where the player ends up.

**Comment by TheCodex6824** [comment]
The mod checks if the worlds actually exist on world load before adding them to the list of dimensions available for fractures to go to - that's how I can ship a default config with a whole bunch of modded dimensions in them. And yes, if you reset that flag on the fracture back to 0 and enable that config option it will take you somewhere, but no promises on whether that somewhere is anywhere safe or not.

**Comment by Hyxaru** [comment]
Currently my emptiness dimension is set as cubic, and the fracture locator and warding seem to work just fine.
Also indeed changing that configuration and manually securing the link with nbt edit worked.
The fracture in question would send me to the correct x and z, but the placed me at y0. Very likely due to CC. I editted the linkpos to the propper y value and it works smoothly.
