### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Hyxaru** [TheCodex6824/ThaumicAugmentation#97]
In a creative world, I am suddenly encountering the following crash. I was previously fiddling with the elytra harness and booster.
[crash-2020-09-28_20.26.43-client.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/5294295/crash-2020-09-28_20.26.43-client.txt)

**Comment by TheCodex6824** [comment]
That crash was actually from a stability field generator animation being weird. Eventually I'm planning on switching how block animations are done to something that won't do that, in the mean time that should hopefully be a one time crash.

**Comment by TheCodex6824** [comment]
Update with the fix will be available soon, get it [here](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/3089750).
