### ISSUE TITLE
denied research category not working as intended (maybe?)

### ISSUE THREAD

**Issue by Biviho** [TheCodex6824/ThaumicAugmentation#98]
hi, i was testing some functionality for my pack, and it seems like the config option denied research category is not really working:

if i have understood correctly, all the category put in this list will not be given from a research in the research table, right? if so, the option is not really working as intended, as i'm actually able to get knowledge on rustic thaumaturgy, thaumic augmentation and periphery from the table even if those are in the list by default, tell me if i interpreted this config option in a wrong way.

also, on another note, it would be great to extend this config option also on research and observations obtained from the use of curios

**Comment by TheCodex6824** [comment]
That config option is only for cards added by Thaumic Augmentation, not all cards in general. Making it work for all cards would require lots of coremodding, which I've been trying to limit as more addons with coremods have been popping up recently, and this is more of a content addon than a fix one. I guess I can think about doing it, but no promises.

**Comment by Biviho** [comment]
oh, so i understood it wrongly indeed, no problem.
If you will consider to do a mod to fix that i would personally be very happy, as it would make thaumcraft research and curio to be more consistent, otherwise is not a problem, maybe someone else will do it
