### ISSUE TITLE
Missing experience from flying with Elytra

### ISSUE THREAD

**Issue by DoomRater** [TheCodex6824/ThaumicAugmentation#99]
I learned how to fly with the elytra but gained a generic tag message upon learning how to do so.  Upon looking through the lang file, I think the entry wasn't added...

**Comment by TheCodex6824** [comment]
I knew I forgot to add the text for something...

**Comment by TheCodex6824** [comment]
Update will be [here](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/3089750) once it gets approved.
